// ==UserScript==
// @name         Burger Flipper Idle 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.1
// @description  网页游戏 Burger Flipper Idle (https://burgerflipperidle.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Burger Flipper Idle.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://burgerflipperidle.com/assets/standardburgers/classic.png
// @license      MIT
// @include      *https://burgerflipperidle.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/burger-flipper-idle-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/burger-flipper-idle-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/11/07 22:22
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "🎮 Guest Account": "🎮 游客账户",
    "🎮 Keep Playing": "🎮 继续游戏",
    "🎯 Specials": "🎯 特殊",
    "💾 Save": "💾 保存",
    "Cloud Saves:": "云存档:",
    "Coming Soon": "敬请期待",
    "COMING SOON": "敬请期待",
    "ComingSoon": "敬请期待",
    "🧪 Research Shop": "🧪 研究商店",
    "🧪 Research Lab": "🧪 研究实验室",
    "🔒 MILESTONES": "🔒 里程碑",
    "🔒 LOCKED (Income Too Low)": "🔒 未解锁 (收入太低)",
    "🔒 Locked (Income Too Low)": "🔒 未解锁 (收入太低)",
    "🔒 LOCKED": "🔒 未解锁",
    "🔒 OPERATIONS": "🔒 运营",
    "🔒 UPGRADES": "🔒 升级",
    "🔒 R&D": "🔒 R&D",
    "MEAT": "肉",
    "PACKAGING": "打包",
    "QUALITY": "质量",
    "SPECIALS": "特殊",
    "INGREDIENTS": "食材",
    "ADVERTISING": "广告",
    "🛒 Burger SHOP": "🛒 汉堡商店",
    "🛒 Research SHOP": "🛒 研究商店",
    "🛒 SHOP": "🛒 商店",
    "WELCOME BACK!": "欢迎回来！",
    "Welcome to Burger Flipper Idle!": "欢迎来到汉堡反转放置!",
    "When you buy a meat upgrade, prices don't update until the next market refresh! \n    Grab the multiplied quantities at current prices before the market refreshes! ": "当你购买肉类升级，价格不会更新，直到下一次市场刷新！在市场恢复之前，以当前的价格获取成倍的数量！",
    "": "",
    "You'll receive:": "你将收到:",
    "Your Data": "你的数据",
    "You agree NOT to:": "你同意不：",
    "Wipe Save": "擦除存档",
    "Why?": "为什么?",
    "Upgrades": "升级",
    "UPGRADES": "升级",
    "Upgrade": "升级",
    "Upgrade - $": "升级 - $",
    "Version": "版本",
    "Vampire Burger": "吸血鬼汉堡",
    "View all employees →": "查看所有员工 →",
    "View all ingredients →": "查看所有原料 →",
    "Website: muckduckmedia.com - Coming Soon": "网站: muckduckmedia.com - 敬请期待",
    "Wholesale Pack": "批发包装",
    "👨‍🍳 Auto-Buy Employees": "👨‍🍳 自动购买员工",
    "💰 Bulk Sell": "💰 批量出售",
    "💰 Pricing": "💰 价格",
    "💻 Fira Code": "💻 Fira代码",
    "📥 Import": "📥 导入",
    "Invest": "投资",
    "Investment Amount:": "投资数量:",
    "Just now": "刚刚",
    "King Burger": "汉堡王",
    "Learn More": "了解更多",
    "Leaderboards:": "排行榜:",
    "Low": "低",
    "Low (No animations)": "低 (无动画)",
    "MAX": "最大",
    "MONEY:": "金钱:",
    "MEAT:": "肉:",
    "MY ACCOUNT": "我的账号",
    "Never": "从不",
    "NET INCOME": "净收入",
    "No Lab": "无实验室",
    "Offline": "离线",
    "Offline Efficiency": "离线效率",
    "Prestige": "声望",
    "Prestige: ×": "声望: ×",
    "/sec": "/秒",
    "/s": "/秒",
    "% Demand": "% 需求",
    "👤 My Account": "👤 我的账户",
    "👥 Employees": "👥 员工",
    "▶ Right Side": "▶ 右侧",
    "◀ Left Side": "◀ 左侧",
    "🎓 Game Help": "🎓 游戏帮助",
    "Sign In": "登入",
    "Sign Out": "登出",
    "SHOP": "商店",
    "SETTINGS": "设置",
    "Sell Burgers": "出售汉堡",
    "⚠️ Loading this will REPLACE your current game!": "⚠️ 加载后将替换当前游戏进度！",
    "⚠️ Warning:": "⚠️ 警告:",
    "⚠️Maximum demand reached! Consider raising prices.": "⚠️ 需求已达上限！考虑提高价格。",
    "⏰ Time": "⏰ 时间",
    "☁️ Cloud Save": "☁️ 云存档",
    "☁️ Cloud Save Found": "☁️ 发现云存档",
    "☁️ Looking for Cloud Saves or Backups?": "☁️ 寻找云存档或备份？",
    "✖️ Close": "✖️ 关闭",
    "Offline Time": "离线时间",
    "🎮 Current Game": "🎮 当前游戏",
    "🎨 Premium Themes": "🎨 高级主题",
    "🎨 Interface Themes": "🎨 界面主题",
    "🎁 Owned Items": "🎁 拥有物品",
    "🎁 New Bonuses You'll Get:": "🎁 你将获得新奖励:",
    "🎁 Redeem Code": "🎁 兑换代码",
    "🍪 Cookie Policy": "🍪 Cookie策略",
    "Playing now": "当前游戏",
    "Privacy": "隐私",
    "Quick Settings": "快速设置",
    "Quick Unlocks": "快速解锁",
    "Quick Actions:": "快速动作:",
    "Seeds": "种子",
    "Seeds:": "种子:",
    "Secrets": "秘密",
    "Save/Load": "保存/加载",
    "Save to Cloud": "保存到云",
    "Save Management": "存档管理",
    "Save Game": "保存游戏",
    "Save Config": "保存配置",
    "Save & sync your progress": "保存并同步您的进度",
    "Theme:": "主题:",
    "Time Played": "游戏时长",
    "Total": "总计",
    "TOTAL": "总计",
    "Total Clicks": "总计点击",
    "Total Sold": "总计出售",
    "Total SELLING": "总计出售",
    "Total Purchased": "总计购买",
    "Total Logins": "总计登录",
    "Total RP:": "总计RP:",
    "Total Prestiges:": "总计声望:",
    "Total oints Spent:": "总计花费点数:",
    "Total Prestiges Done": "总计完成声望",
    "UI Settings": "界面设置",
    "Upgradeable:": "可升级:",
    "Producing:": "生产:",
    "Production": "生产",
    "PRODUCTION": "生产",
    "Purchase history": "购买历史",
    "Normal": "普通",
    "Not signed in": "未登录",
    "Money:": "金钱:",
    "Net Burgers:": "净汉堡:",
    "Net": "净",
    "HELP": "帮助",
    "Font:": "字号:",
    "Font Family:": "字体:",
    "Final: $": "最终: $",
    "EQUIPMENT": "装备",
    "Equipment Purchased": "购买的装备",
    "Export Save": "导出存档",
    "Export your game data": "导出你的游戏数据",
    "Export/Import Save Data": "导出/导入 存档",
    "EMPLOYEES": "员工",
    "Employees": "员工",
    "Employees Hired": "雇佣的员工",
    "Employees are hired 50% faster": "雇佣员工的速度提升50%",
    "Effects Quality:": "影响质量:",
    "Duration:": "持续时间:",
    "Donut Burger": "甜甜圈汉堡",
    "DISABLED": "禁用",
    "Discord:": "Discord:",
    "Download My Data": "下载我的数据",
    "Download Save File": "下载存档文件",
    "Dragon Burger": "龙堡",
    "Earn": "获得",
    "Diner": "晚餐",
    "Demand": "需求",
    "Sesame Seeds:": "芝麻种子:",
    "Session Time": "会话时间",
    "Show Hints": "显示提示",
    "Shop not loaded yet...": "商店还未加载...",
    "Service providers that help operate the game": "帮助运营游戏的服务提供商",
    "Send updates & news": "发送更新和新闻",
    "SELLING": "出售",
    "Selling": "出售",
    "Rookie Training": "新人培训",
    "Rookie Squad": "新人小队",
    "Rookie Production:": "新人生产:",
    "Rookie": "新人",
    "Robot Enhancement ": "机器人增强",
    "Risk Level:": "风险等级:",
    "Lowest Price": "最低价",
    "Loss of progress, virtual items, or account data": "丢失进度、虚拟物品或帐户数据",
    "MAIN": "主要",
    "MANAGERS": "经理",
    "MANUAL": "手动",
    "Manual Backups": "手动备份",
    "Manual Flips": "手动翻转",
    "Master Control": "控制大师",
    "Burgers Sold": "售出汉堡",
    "Burgers Sold:": "售出汉堡:",
    "BURGERS::": "汉堡:",
    "BURGERS/SALE": "汉堡/出售",
    "burgers/sec": "汉堡/秒",
    "burgers per click": "汉堡每次点击",
    "Burgers Flipped": "翻转的汉堡",
    "Buy lots of meat before going offline": "在离线前多买些肉",
    "Cancel": "取消",
    "Continue with current game": "继续当前游戏",
    "📥 Load Cloud Save": "📥 加载云存档",
    "📜 Purchase History": "📜 购买历史",
    "📜 History": "📜 历史",
    "📋 Activity Log": "📋 活动日志",
    "📊 Statistics": "📊 统计",
    "📊 Market": "📊 市场",
    "📊 Game Statistics": "📊 游戏统计",
    "📊 Stats & Visualizations": "📊 统计和可视化",
    "📢 Auto-Buy Advertising": "📢 自动购买广告",
    "📈 Progress": "📈 进度",
    "📈 Visualizations": "📈 可视化",
    "📈 Meat Purchase Efficiency": "📈 买肉效率",
    "📦 Auto-Buy Packaging": "📦 自动购买包装",
    "📦 Backup Manager": "📦 备份管理",
    "📦 Purchasing": "📦 采购",
    "📈 Market Stats": "📈 市场统计",
    "💾 Create Backup": "💾 创建备份",
    "💰 Economy": "💰 经济",
    "💰 Economy Upgrades": "💰 经济升级",
    "💫 Neon": "💫 霓虹灯",
    "♿ High Contrast": "♿ 高对比度",
    "⚙️ Steampunk": "⚙️ 蒸汽朋克",
    "⚙️ Employee Hiring Settings": "⚙️ 员工雇佣设置",
    "⚙️ Steampunk (Premium)": "⚙️ 蒸汽朋克 (高级)",
    "⚙️ Idle Path": "⚙️ 放置之路",
    "⚙️ System Upgrades": "⚙️ 系统升级",
    "⚡ Click & Hold Upgrades": "⚡ 点击 & 按住升级",
    "⚡ Efficiency Upgrades": "⚡ 效率升级",
    "⚡ Performance": "⚡ 性能",
    "⚡ Time Control": "⚡ 时间控制",
    "⚡ Neon (Premium)": "⚡ 霓虹灯 (高级)",
    "✨ Full Account - FREE": "✨ 完整账户 - 免费",
    "✨ Prestige Now! ✨": "✨ 立即声望! ✨",
    "❄️ Arctic": "❄️ 北极",
    "❄️ Arctic (Premium)": "❄️ 北极 (高级)",
    "✨ Quality Upgrades": "✨ 质量升级",
    "Replace current game with cloud save": "用云存档覆盖本地进度",
    "Must be signed in to earn daily rewards": "必须登录才能获得每日奖励",
    "💡 Pro Tip:": "💡 高级提示:",
    "💡 How Meat Prices Work:": "💡 肉类价格是如何运作的：",
    "💡 Production Upgrades": "💡 生产升级",
    "💡 Tip: Auto-buyers respect money buffers and meat minimums to prevent overspending": "💡 提示：自动购买者尊重金钱增益和肉类最低限度，以防止超支",
    "🔄 Upgrading from Guest": "🔄 通过游客升级",
    "🔄 Restore Purchases": "🔄 恢复购买",
    "Click here to go to Settings": "点这里前往设置",
    "Click Mastery": "点击精通",
    "Click to dismiss": "点击驳回",
    "Close": "关闭",
    "Cloud save functionality": "云存档功能",
    "Click \"Upgrade\" next to \"Temporary Account\"": "点击“临时帐户”旁边的“升级”。",
    "Clear All": "清除全部",
    "Classic Burger": "经典汉堡",
    "Claim Today's Reward!": "领取今日奖励!",
    "Claim daily rewards from the calendar": "从日历中领取每日奖励",
    "Cheese:": "芝士:",
    "Change Password": "修改密码",
    "CHALLENGES": "挑战",
    "CC Earned": "赚取的CC",
    "CATERING:": "餐饮:",
    "Company Name": "公司名称",
    "Confirm\n                                    Investment": "确认投资",
    "Connect With Us": "联系我们",
    "Consuming": "消耗",
    "Consuming:": "消耗:",
    "Cost Exponent:": "成本指数:",
    "I Understand": "我了解了",
    "Hybrid Mastery": "混合精通",
    "This game uses Google Analytics to understand usage patterns and improve the game experience. No\n                        personal information is collected.": "这款游戏使用谷歌Analytics来了解使用模式并改善游戏体验。不收集任何个人信息。",
    "This game uses your browser's local storage to save your progress, preferences, and provide a\n                        better gaming experience. By continuing to play, you agree to our use of storage and our": "这个游戏使用你的浏览器的本地存储来保存你的进度，偏好，并提供更好的游戏体验。继续游戏即表示您同意我们使用存储和我们的",
    "Research Points:": "研究点数:",
    "Resend Email": "重发验证邮件",
    "Reset to Default": "重置为默认",
    "Statistic": "统计",
    "HOME": "首页",
    "MILESTONES": "里程碑",
    "Midnight Green": "午夜绿",
    "Achievement Earned": "获得成就",
    "ACHIEVEMENTS": "成就",
    "Achievements, Settings, Golden Spatulas": "成就，设置，黄金抹刀",
    "Active Bonus": "活跃加成",
    "ACTIVE": "活跃",
    "Active": "活跃",
    "Account Types": "账户类型",
    "Account System": "账户协同",
    "Account Security:": "账户安全:",
    "Account Security": "账户安全",
    "Account & Cloud Sync": "账户 & 云同步",
    "Alien Burger": "外星人汉堡",
    "LEADERBOARD": "排行榜",
    "PATCH\n                    NOTES": "更新日志",
    "Packs": "包装",
    "Overview": "概览",
    "Next Gain": "下一个增益",
    "Next reward in:": "距离下一个奖励:",
    "Money Earned:": "赚取的金钱:",
    "Money Earned": "赚取的金钱",
    "Money Spent": "花费的金钱",
    "BURGERS:": "汉堡:",
    "AUTOMATED": "自动化",
    "RATE": "速率",
    "TOTAL CONSUMPTION": "总消费",
    "Price per burger:": "汉堡单价:",
    "Price Multiplier:": "价格乘数:",
    "Price Changes": "价格变化",
    "Price Breakdown:": "价格细分:",
    "Sign in to earn": "登录以获得",
    "Sign in to enable cloud saves and sync your progress across devices. Your\n                                            sesame seeds and game data will be securely stored.": "登录以启用云保存并跨设备同步您的进度。您的芝麻和游戏数据将被安全存储。",
    "Sell burgers in bulk at a reduced rate": "以折扣价批量出售汉堡",
    "CASHIERS": "收银员",
    "Cashiers Hired": "雇佣的收银员",
    "Cannot earn daily reward": "无法获得日常奖励",
    "Candy Burger": "糖果汉堡",
    "CATERERS": "餐饮承办商",
    "CATERING": "餐饮服务",
    "TOTAL SELLING": "总计出售",
    "INCOME": "收入",
    "Ingredients": "食材",
    "GROSS INCOME": "毛收入",
    "WAGES": "工资",
    "FLIP BURGER": "翻转汉堡",
    "Game Settings": "游戏设置",
    "⏰ Inactivity Detected": "⏰ 检测到不活跃",
    "Resume Playing": "回到游戏",
    "🏆 Global Leaderboard": "🏆 全球排行榜",
    "🏆 Foundation": "🏆 基金会",
    "🏆 Leaderboard": "🏆 排行榜",
    "Choose Your Username": "选择你的用户名",
    "You need a username to appear on the leaderboard!": "你需要一个用户名才能出现在排行榜上！",
    "Rank": "排名",
    "Player": "玩家",
    "Score": "积分",
    "Actions": "动作",
    "Refresh": "刷新",
    "Refresh Backups": "刷新备份",
    "Last saved:": "最近保存:",
    "Access your cloud saves, automatic backups, and purchase history in your account settings.": "在您的帐户设置中访问您的云保存，自动备份和购买历史记录。",
    "Access all shop items": "访问全部商店物品",
    "Access or correct your data": "访问或更改您的数据",
    "Go to My Account": "前往我的账户",
    "Go to Settings Save/Load": "前往设置 保存/加载",
    "Golden Mastery": "黄金精通",
    "Golden Spatulas": "黄金抹刀",
    "Ingredients: +$": "食材: +$",
    "INDUSTRIES": "行业",
    "👥 Flippers": "👥 翻转者",
    "🍔 Production": "🍔 生产",
    "🍔 Game\n                                    Basics": "🍔 游戏基础",
    "🍔 Golden Spatula Architect 🍔": "🍔 黄金抹刀建筑师 🍔",
    "🍽️ Catering": "🍽️ 餐饮",
    "🌸 Vaporwave": "🌸 蒸汽波",
    "👤 Account System": "👤 账户系统",
    "👥 Auto-Hire Employees": "👥 自动雇佣员工",
    "👥 Workforce": "👥 劳动力",
    "👥 Workforce Upgrades": "👥 劳动力升级",
    "💜 Vaporwave (Premium)": "💜 蒸汽波 (高级)",
    "🎮 In the meantime, you can earn sesame seeds through achievements and spend them in other shop tabs!": "🎮 在此期间，你可以通过成就获得芝麻，并在其他商店标签中消费！",
    "🔰 Matrix": "🔰 矩阵",
    "This action is permanent and cannot be undone.\n                                        All your game data, achievements, and account information will be permanently\n                                        deleted.": "这个动作是永久性的，不能撤消。您的所有游戏数据、成就和帐户信息将被永久删除。",
    "Reduces animations and visual effects for smoother gameplay on slower devices.\n                                        This will disable most animations, shadows, and particle effects.": "减少动画和视觉效果，使游戏在较慢的设备上更流畅。这将禁用大多数动画，阴影和粒子效果。",
    "By clicking \"Accept\" or by playing Burger Flipper Idle, you acknowledge that you have\n                            read, understood, and agree to be bound by these Terms of Service.": "点击\“接受\”或玩 Burger Flipper Idle，即表示您已阅读、理解并同意接受本服务条款的约束。",
    "By accessing and playing Burger Flipper Idle (\"the Game\"), you agree to be bound by these Terms\n                        of Service (\"Terms\"). If you do not agree to these Terms, please do not play the Game.": "通过访问和玩Burger Flipper Idle（“游戏”），您同意受这些服务条款（“条款”）的约束。如果您不同意这些条款，请不要玩游戏。",
    "Auto-buyers only purchase when you have 110% of the cost and at least 100 meat.\n                                        This prevents overspending and ensures you always have resources for manual purchases.": "只有当你有110%的成本和至少100块肉时，自动购车者才会购买。这可以防止超支，并确保你总是有资源进行手动购买。",
    "(2x upgrade = 2x meat for 1.9x the price)": "(2x 升级 = 2x 肉以 1.9x 价格)",
    "±15-20% random fluctuation": "±15-20% 随机波动",
    "⭐ Auto-Buy Quality": "⭐ 自动购买质量",
    "🌌 Synthwave": "🌌 合成波",
    "🌟 Talent Tree": "🌟 天赋树",
    "+1 burger per manual flip per level": "每一级手动翻转+1个汉堡",
    "+10% Golden Spatula gain per level": "每级+10%的黄金刮刀增益",
    "+20% offline efficiency per level": "每级+20%离线效率",
    "+25% employee efficiency per level": "每级+25%的员工效率",
    "+25% to active OR idle bonuses based on activity per level": "+25%的活动或空闲奖励根据活动每级",
    "+50% presence multiplier effectiveness per level": "+50%的存在乘数效果每级",
    "+50% recruitment speed per level": "每级增加50%招募速度",
    "⚖️ Balance Configuration": "⚖️ 平衡配置",
    "⚖️ Hybrid Path": "⚖️ 混合路径",
    "✨ All upgrades are permanent and persist through prestiges!": "✨ 所有升级都是永久性的，并通过声望持续存在！",
    "✨ QUALITY OF LIFE UPGRADE ✨": "✨ 生活质量提升 ✨",
    "🌆 Synthwave (Premium)": "🌆 合成波（高级）",
    "🌌 Cosmic (Premium)": "🌌 宇宙（高级）",
    "🌙 How Offline Time Works": "🌙 线时间如何工作",
    "🌙 Offline Progression": "🌙 离线进程",
    "🌟 Cosmic": "🌟 宇宙",
    "🌟 Premium Burger Skins": "🌟 高级汉堡皮",
    "🌱 Sesame\n                                    Seeds": "🌱 芝麻种子",
    "🍅 Ingredients": "🍅 食材",
    "🍔 Burger Skins": "🍔 汉堡皮",
    "🎮 nicedonut296": "🎮 nicedonut296",
    "🏢 Burger Stock Market": "🏢 汉堡股票市场",
    "🏭 Burger Industries": "🏭 汉堡行业",
    "👆 Active Path": "👆 活动路径",
    "💰 Economic Upgrades": "💰 经济升级",
    "💰 Transactions": "💰 事务",
    "🔄 Infinite Architecture System unlocks at Prestige 5!": "🔄 无限建筑系统在威望5解锁！",
    "🔋 Matrix (Premium)": "🔋 矩阵（高级）",
    "🔤 JetBrains Mono": "🔤 JetBrains Mono",
    "🔥 Inferno": "🔥 地狱",
    "🔥 Inferno (Premium)": "🔥 地狱（高级）",
    "🔧 Specific Values": "🔧 具体数值",
    "🔮 Cyberpunk": "🔮 赛博朋克",
    "🔮 Cyberpunk (Premium)": "🔮 赛博朋克（高级）",
    "🗑️ Clear Cache": "🗑️ 清除缓存",
    "🤖 Auto Buyer System": "🤖 自动购买者系统",
    "🤖 Auto-Buyer:": "🤖 自动购买者：",
    "🥄 Golden Spatula System": "🥄 黄金抹刀系统",
    "🥄 Ready to Prestige?": "🥄 准备好声望了吗？",
    "🥄 Spatula Upgrades": "🥄 抹刀升级",
    "🥩 Meat Management": "🥩 肉类管理",
    "🥩 Meat Market": "🥩 肉类市场",
    "🥩 Resources": "🥩 资源",
    "🥫 Turbo Sauce Remaining:": "🥫 涡轮酱剩余：",
    "🥬 Auto-Buy Ingredients": "🥬 自动购买食材",
    "🧀 Extra Tip:": "🧀 额外提示：",
    "🚀 Quick Adjustments": "🚀 快速调整",
    "🚀 Speed Boosts": "🚀 速度提升",
    "🚀 Upgrade Timeline": "🚀 升级时间线",
    "$ - US Dollar (USD)": "$ - 美元 (USD)",
    "£ - British Pound (GBP)": "£ - 英镑 (GBP)",
    "¥ - Japanese Yen/Chinese Yuan": "¥ - 日元/人民币",
    "฿ - Thai Baht (THB)": "฿ - 泰铢 (THB)",
    "₩ - South Korean Won (KRW)": "₩ - 韩元 (KRW)",
    "₪ - Israeli Shekel (ILS)": "₪ - 以色列谢克尔 (ILS)",
    "₫ - Vietnamese Dong (VND)": "₫ - 越南盾 (VND)",
    "€ - Euro (EUR)": "€ - 欧元 (EUR)",
    "₹ - Indian Rupee (INR)": "₹ - 印度卢比 (INR)",
    "₽ - Russian Ruble (RUB)": "₽ - 俄罗斯卢布 (RUB)",
    "₿ - Bitcoin (BTC)": "₿ - 比特币 (BTC)",
    "3. USER ACCOUNTS": "3. 用户账户",
    "🛒 Burger Shop": "🛒汉堡店",
    "🛒 Research Shop": "🛒研究商店",
    "0-30 minutes:": "0-30分钟：",
    "0-720 minutes (12 hours):": "0-720分钟（12小时）：",
    "A notice on the game's main menu": "游戏主菜单上的通知",
    "Adaptive Bonus": "自适应加成",
    "Adaptive Bonus, Quick Unlocks": "自适应加成，一键解锁",
    "Adjust game balance, progression rates, or virtual economy": "调整游戏平衡，进度率或虚拟经济",
    "Advanced": "高级",
    "Affordability Badges:": "负担能力徽章：",
    "After grace period, demand drops proportionally each minute based on decay rate": "在宽限期之后，基于衰减率，需求每分钟按比例下降",
    "After Grace Period: Demand Decay": "宽限期后：需求衰减",
    "All Advertising Demand:": "所有广告需求：",
    "All Employee Production:": "全体员工生产情况：",
    "All Employee Wages:": "全体员工工资：",
    "All employees produce 10% more burgers": "所有员工的汉堡产量增加了10%",
    "All Game content, including graphics, sounds, text, and code, is owned by us or our\n                            licensors": "所有游戏内容，包括图形、声音、文本和代码，均归我们或我们的授权方所有",
    "All Ingredient Costs:": "所有原料成本：",
    "All Ingredient Prices:": "所有原料价格：",
    "All ingredients are 1% more powerful": "所有食材威力提升1%",
    "All Price Boosts:": "所有价格提升：",
    "All progress transfers automatically!": "所有进度自动转移！",
    "All purchases are final and non-refundable except as required by law": "除法律规定外，所有购买均为最终决定，恕不退款",
    "All sales are calculated and added to your balance": "所有的销售都被计算并添加到您的余额中",
    "AND saves you clicks. ": "和节省你的点击。",
    "Any content you create within the Game remains yours": "你在游戏中创造的任何内容都是你的",
    "Any damages exceeding the amount you paid us in the past 12 months": "任何损失超过你方在过去12个月支付给我方的金额",
    "Any indirect, incidental, special, consequential, or punitive damages": "任何间接的、附带的、特殊的、后果性的或惩罚性的损害赔偿",
    "Any particular results from playing the Game": "任何特定的结果从玩游戏",
    "Apply": "应用",
    "Apply Changes": "应用更改",
    "Apply scaling to all:": "应用缩放到所有：",
    "Architect": "建筑师",
    "Ascend to a higher tier of burger mastery!": "提升到更高层次的汉堡精通！",
    "At our sole discretion with or without notice": "无论是否通知，由我方自行决定",
    "Attempt to gain unauthorized access to the Game's systems or other users' accounts": "试图获得未经授权访问游戏系统或其他用户的帐户",
    "Auto Backups": "自动备份",
    "Auto Buyers": "自动购买者",
    "Auto Cloud Save": "自动云保存",
    "Auto Flipper": "自动翻转者",
    "Auto flipper clicks 20% faster": "自动翻转者点击速度快20%",
    "Auto Flips": "自动翻转",
    "Auto Meat Buyer": "自动买肉者",
    "Auto Meat Buyer is essential:": "自动买肉者必不可少：",
    "Auto Meat Buyer will purchase meat automatically if you have it enabled": "如果你启用了自动买肉者，它会自动购买肉",
    "Auto Meat Buyer, Offline Mastery": "自动买肉，离线精通",
    "Auto-Flip Speed ": "自动翻转速度",
    "Automatic daily backups are created when you save. Last 7 days are kept.": "保存时将自动创建每日备份。保留最近7天。",
    "Automatically hire employees when affordable": "在经济允许的情况下自动雇佣员工",
    "Automatically purchase advertising campaigns": "自动购买广告宣传",
    "Automatically purchase meat when running low": "当肉量不足时自动购买",
    "Automatically purchase packaging upgrades": "自动购买包装升级",
    "Automatically purchase upgrades when you have enough resources.\n                                        Each system unlocks at specific prestige levels.": "当你有足够的资源时自动购买升级。\n每个系统解锁在特定的威望水平。",
    "Automatically save to cloud every\n                                                minute": "自动保存到云每\n分钟",
    "Automatically upgrade burger quality": "自动升级汉堡品质",
    "Automatically upgrade ingredient quality levels": "自动升级原料质量等级",
    "Automation Suite": "自动化套件",
    "Available Golden Spatulas": "可用的金色抹刀",
    "Average Demand": "平均需求",
    "Average Sell Price": "平均售价",
    "Backup Recovery": "备份恢复",
    "Balance between active and idle play": "在积极和无所事事的游戏之间保持平衡",
    "Balanced Start": "平衡开始",
    "Banquet Package \n                        \n                        ": "宴会包\n \n",
    "Base stats (no upgrades):": "基础属性（无升级）：",
    "Base: $": "基数：$",
    "Based on current demand, cashiers, and other multipliers": "基于当前需求，出纳员和其他乘数",
    "based on market conditions": "根据市场情况",
    "Basic Bag ": "基础包",
    "BBQ Deluxe": "烧烤豪华",
    "Beach Burger": "海滩汉堡",
    "Bedazzled Burger": "眼花缭乱的汉堡",
    "Begin operations with a strategic meat stockpile of 5,000 units, ensuring you never run out during the critical early rush.": "以5000单位的战略肉类储备开始行动，确保你在关键的早期高峰期不会耗尽。",
    "Best Streak": "最佳连胜",
    "Bonuses adjust to your play style": "奖励根据你的游戏风格进行调整",
    "Box Deal": "礼盒特惠",
    "Brand Loyalty:": "品牌忠诚度:",
    "Breakfast Special": "早餐特惠",
    "Bulk Bag": "散装袋",
    "Bulk Order": "大宗订单",
    "Bulk purchasing agreements reduce all ingredient costs by 10%, improving your profit margins on every burger sold.": "批量采购协议减少了10%的原料成本，提高了每卖出一个汉堡的利润率。",
    "Burger Consumption:": "汉堡消费:",
    "Burger Customization": "汉堡定制",
    "Burger Flipper Idle is a free-to-play browser-based incremental/idle game. The Game may include:": "《Burger Flipper Idle》是一款基于浏览器的免费增值/空闲游戏。游戏可能包括：",
    "Burger Flipper Idle may delete your account if we find you are in violation of these\n                            Terms of Service": "如果我们发现您违反本服务条款，Burger Flipper Idle可能会删除您的帐户",
    "Burger Plating": "汉堡盘",
    "Burger Plating I (+$12800.00 price)": "汉堡拼盘I（+$12800.00价格）",
    "Burger Price": "汉堡价格",
    "Burger Pricing Controls": "汉堡定价控制",
    "Burger Production:": "汉堡生产:",
    "Burger Skin Credits:": "汉堡皮肤积分：",
    "Burger Stockpile": "汉堡储备",
    "Burgers are sold from your existing stock, then new burgers are flipped from meat": "汉堡从你现有的库存中出售，然后新的汉堡从肉中翻转",
    "By creating content in the Game, you grant us a worldwide, non-exclusive license to use it": "通过在游戏中创建内容，您授予我们在全球范围内使用该内容的非独占许可",
    "By default, demand will decay over 2 hours (120 minutes) down to a minimum floor.": "默认情况下，需求将在2小时（120分钟）内下降到最低限度。",
    "Can be extended up to 12 hours (720 minutes) with the \"Extended Grace Period\" upgrade": "升级“延长宽限期”后，可延长至12小时（720分钟）",
    "Cannot Prestige Yet": "暂不可声望",
    "Cannot purchase premium items": "不能购买高级道具",
    "Capped at 24 hours of progress": "进度上限为24小时",
    "Catering Cashier Training \n        ": "餐饮收银员培训\ n",
    "Catering Ingredient Research \n        ": "餐饮原料研究\n",
    "Catering System": "餐饮系统",
    "Change or remove game features without prior notice": "在没有事先通知的情况下更改或删除游戏功能",
    "Chicken Deluxe": "豪华鸡肉",
    "Choose a font that makes the game comfortable to read. Monospace fonts are great\n                                        for numbers!": "选择一种让游戏读起来舒服的字体。等宽字体非常适合\n显示数字！",
    "Citywide burger distribution system": "全市汉堡配送系统",
    "Citywide Distribution \n                        \n                        ": "全市配送\n \n",
    "Commas (1,000,000)": "逗号 (1,000,000)",
    "Compete globally (coming soon)": "全球竞争（敬请期待）",
    "Container Ship": "集装箱船",
    "Continental Network": "大陆网络",
    "Continental Network \n                        \n                        ": "大陆网络",
    "Continental-scale distribution": "大陆范围内的分布",
    "Convention Pack \n                        \n                        ": "约定包\n \n",
    "Convention-scale packaging system": "传统规模的包装系统",
    "Convert to full account without losing progress": "转换为完整帐户而不会丢失进度",
    "Copy to Clipboard": "复制到剪贴板",
    "Core gameplay features": "核心游戏功能",
    "Corporate Catering \n                        \n                        ": "企业餐饮\n \n",
    "Corporate event catering solutions": "企业活动餐饮解决方案",
    "Cosmetics": "化妆品",
    "Cost: 1 talent point": "消耗：1点天赋点",
    "Create Account": "创建账户",
    "Create an account early to start earning sesame seeds from achievements!": "尽早创建账号，即可通过成就获得芝麻！",
    "Crimson Dark": "暗红",
    "CSP\n                            CHANCE": "CSP\n机会",
    "CSP\n                            SHOP": "CSP\n商店",
    "CSP Bonus: +$": "CSP奖励：+$",
    "CSP Earned": "获得的CSP",
    "CSP Earnings": "CSP收益",
    "CSP Spent": "CSP花费",
    "CSP:": "CSP:",
    "Currency Symbol - Coming Soon": "货币符号-敬请期待",
    "Current Multiplier": "当前乘数",
    "Current Return Rate:": "当前收益率：",
    "Current Streak": "当前连胜",
    "Current Tier": "当前层级",
    "Current Tier Bonuses": "当前层级奖励",
    "Current: Flipping": "当前：翻转",
    "Current: Selling 1 burger per sale": "当前：每次销售1个汉堡",
    "Customer service is key": "客户服务是关键",
    "Customize the appearance of your burger icon!": "自定义您的汉堡图标的外观！",
    "Daily Bonus:": "每日奖励：",
    "Daily Login Rewards": "每日登录奖励",
    "Danger Zone": "危险区域",
    "Dark": "黑暗",
    "Dark Blue (Default)": "深蓝（默认）",
    "Dark Purple": "深紫色",
    "Data & Privacy": "数据与隐私",
    "Data is stored securely with Firebase using industry-standard encryption.": "使用行业标准加密技术，在Firebase中安全地存储数据。",
    "Decay Phase:": "衰变阶段：",
    "Decay Time (Base: 2 hours):": "衰变时间（基础：2小时）：",
    "Defects will be corrected": "缺陷将予以纠正",
    "Delete My Account": "删除我的账号",
    "Demand at Optimal": "需求最优",
    "Demand Boost": "需求提升",
    "Demand decays from 100% down to 10% over 2 hours": "需求在2小时内从100%下降到10%",
    "Demand decays from 100% down to 90% over 5 hours": "需求在5小时内从100%下降到90%",
    "Demand does NOT decrease during this period": "在此期间，需求不会减少",
    "Demand Floor (Base: 10%):": "需求下限（基数：10%）：",
    "Demand matters:": "需求事项：",
    "Demand Retention:": "需求保留:",
    "Demand stays at 100% (or whatever it was when you left), and you earn money just like you're actively playing - no penalties whatsoever.": "需求保持在100%（或者不管你离开时是多少），你赚的钱就像你在积极地玩一样——没有任何惩罚。",
    "Dessert Burger": "甜点汉堡",
    "Dimensional Storage": "多维存储",
    "Distribution Network": "分销网络",
    "Double Pack \n                        \n                        ": "双倍礼包\n \n",
    "Download a copy of all your game data and account information.": "下载所有游戏数据和帐户信息的副本。",
    "Each completed catering order permanently increases cashier effectiveness by 0.1% (soft cap at 10%)": "每完成一份餐饮订单，收银员效率永久提高0.1%（软帽为10%）",
    "Each completed catering order permanently increases ingredient power by 0.1% (soft cap at 10%)": "每完成一份餐饮订单，食材威力永久提高0.1%（软上限为10%）",
    "Each tier grants": "每一层授予",
    "Earn at full capacity longer before decay starts (30 min → 12 hours)": "在衰退开始前更长的时间获得满容量（30分钟→12小时）",
    "Earn bonus Golden Spatulas": "获得奖励金锅铲",
    "Earn Golden Spatulas by selling burgers! Each prestige unlocks a new restaurant tier with powerful bonuses.": "通过卖汉堡获得金锅铲！每个声望解锁一个新的餐厅层与强大的奖金。",
    "Effect: 1% per level": "效果：每升1级增加1%",
    "Effect: 10% per level": "效果：每升1级增加10%",
    "Effect: 20% per level": "效果：每升1级20%",
    "Email (if you have an account)": "电子邮件（如果你有账户）",
    "Email address & username": "电子邮件地址及用户名",
    "Email Verification:": "电子邮件验证:",
    "Email: support@burgerflipperidle.com": "电子邮件:support@burgerflipperidle.com",
    "Email/password protected": "电子邮件/密码保护",
    "Embrace the future of burger production! Start with an auto-flipper system and 1 robot chef to automate your kitchen.": "拥抱汉堡生产的未来！从一个自动翻转系统和一个机器人厨师开始，让你的厨房自动化。",
    "Employee Discount": "员工折扣",
    "Employee Efficiency ": "员工效率",
    "Employee Production": "员工生产",
    "Employee Wages": "员工工资",
    "Enable Auto Meat Buyer (especially for overnight)": "启用自动买肉机（特别是隔夜）",
    "Enable auto-buyers to see activity": "允许自动购买者查看活动",
    "Enable auto-buyers to see statistics": "允许自动购买者查看统计数据",
    "Enable master toggle to see statistics": "启用主开关以查看统计数据",
    "Enable or disable all auto-buyers at once": "同时启用或禁用所有自动购买者",
    "Engage in any activity that disrupts the Game or servers": "参与任何破坏游戏或服务器的活动",
    "Engineering (1.23e6)": "工程 (1.23 e6)",
    "Enter your special code to claim rewards!": "输入您的特殊代码领取奖励！",
    "Example Timeline": "示例时间线",
    "Expected Return:": "预期收益:",
    "Extended Grace Period:": "延长宽限期：",
    "Extended inactivity": "延长不活动",
    "Family Bundle": "家庭包",
    "Family Bundle \n                        \n                        ": "家庭礼包\n \n",
    "Festival Crate \n                        \n                        ": "节日宝箱\n \n",
    "Festival-grade containers for large crowds": "供大量人群使用的节日级集装箱",
    "Fira Code (Monospace)": "Fira代码(等宽字体)",
    "First 30 minutes (or longer with upgrades) earn at FULL demand with no decay": "前30分钟（或更长时间的升级）获得满需求，没有衰减",
    "First Cashier": "第一个收银员",
    "Fish Burger": "鱼肉汉堡",
    "Flippers": "反转者",
    "Flipping robot produces 20% more burgers": "翻转机器人的汉堡产量增加20%",
    "Focus on automation and passive income": "关注自动化和被动收入",
    "Focus on clicking and manual interaction": "专注于点击和手动交互",
    "Food Cart": "餐车",
    "FOOD CART": "餐车",
    "Food Truck": "餐车",
    "Food Truck → Burger Shack": "餐车→汉堡小屋",
    "For long offline sessions, this keeps you stocked automatically": "对于长时间的离线会话，这使您自动储存",
    "For questions about these Terms, please contact us at:": "如对这些条款有任何疑问，请通过以下方式与我们联系：",
    "For the first 30 minutes of being idle, your restaurant operates at FULL CAPACITY.": "在闲置的前30分钟，您的餐厅将满负荷运转。",
    "Free Rookies:": "免费新秀：",
    "Full production at 100% demand, earning normally (extended grace period)": "按100%需求满负荷生产，正常盈利（延长宽限期）",
    "Full production at 100% demand, earning normally (grace period)": "以100%需求满负荷生产，正常盈利（宽限期）",
    "Full Settings": "完整设置",
    "Full stadium supply distribution": "全场供应分配",
    "Future Burger": "未来汉堡",
    "Gain additional offline efficiency": "获得额外的离线效率",
    "Gain benefits from both Active and Idle masteries": "从活动和空闲掌握中获益",
    "Galactic Network \n                        \n                        ": "银河网络",
    "Galactic-scale burger distribution": "银河级的汉堡配送",
    "Game progress & stats": "游戏进度和数据",
    "Garden Fresh": "花园新鲜",
    "Gathering Pack \n                        \n                        ": "收集礼包\n \n",
    "Global burger delivery infrastructure": "全球汉堡配送基础设施",
    "Global Consortium": "全球联盟",
    "Global Distribution \n                        \n                        ": "全球配送\n \n",
    "Grace Period Phase:": "宽限期",
    "Grill BPS:": "烧烤BPS：",
    "Grill Wage/s:": "烧烤工资/秒：",
    "Harass, abuse, or harm other players": "骚扰、辱骂、伤害其他玩家",
    "Heating up the grill...": "烤架加热中…",
    "High (All effects)": "高（所有效果）",
    "Higher cashier count = more burgers sold per minute": "收银台数越多=每分钟卖出的汉堡越多",
    "Higher demand = faster decay, lower demand = slower decay (it's percentage-based)": "更高的需求=更快的衰减，更低的需求=更慢的衰减（这是基于百分比的）",
    "Higher demand when you leave = more earnings during offline time": "当你离开时，更高的需求=离线时更多的收入",
    "Higher minimum demand floor (10% → 90%)": "更高的最低需求下限（10%→90%）",
    "Higher price per burger = higher meat prices": "每个汉堡的价格越高=肉类价格越高",
    "Highest Demand": "最高需求",
    "Highest Money": "最高的钱",
    "Highest Price": "最高价格",
    "Hit the ground running with a pre-trained team of 8 rookie employees ready to flip burgers from day one.": "从第一天起，一个由8名新手员工组成的训练有素的团队就准备好了翻转汉堡。",
    "Hold the flip button to charge up automatic flipping! The longer you hold, the faster it\n                                flips.": "按住翻转按钮充电自动翻转！你持有的时间越长，它翻转的速度就越快。",
    "How does offline time work?": "离线时间是如何工作的？",
    "How Earnings Are Calculated": "如何计算收益",
    "How Prestiging Works": "魔术是如何运作的？",
    "How we protect your data": "我们如何保护您的数据",
    "How we use this information (improving the game, cloud saves)": "我们如何使用这些信息（改进游戏，云存储）",
    "Ideal for community gatherings and events": "理想的社区聚会和活动",
    "Idle Efficiency": "闲置的效率",
    "If any provision is found unenforceable, the remaining provisions will continue in effect.": "如果发现任何条款无法执行，其余条款将继续有效。",
    "If informal resolution fails, disputes will be resolved through binding arbitration rather than\n                        court proceedings.": "如果非正式解决失败，争议将通过有约束力的仲裁解决，而不是通过法庭程序。",
    "If you are between 13 and 18 years old:": "如果你的年龄在13到18岁之间：",
    "If you run out of meat, production stops for the rest of offline time": "如果你的肉用完了，生产就会在剩下的下线时间停止",
    "Implement an advanced training program that makes all rookie employees 50% more productive at flipping burgers.": "实施一项高级培训计划，让所有新员工在烙汉堡时的工作效率提高50%。",
    "Import Save": "导入保存",
    "In-game notifications": "游戏内通知",
    "In-game purchases may require parental consent": "游戏内购买可能需要父母的同意",
    "Income Requirement:": "收入要求:",
    "Individual Systems": "个体系统",
    "Infinite Pipeline": "无限管道",
    "Ingredient Boost": "食材提升",
    "Ingredient Boost:": "食材提升：",
    "Ingredient Enhancement ": "食材增强",
    "Ingredient Price Boosts (L1 values)": "原料价格提升（L1值）",
    "Ingredient Savings": "节省原料",
    "Ingredient Scaling": "食材缩放",
    "Ingredients unlocked! Improve your burger quality!": "原料解锁！提高你的汉堡质量！",
    "Instant Play:": "即时游戏:",
    "Inter": "国际米兰",
    "Interface Themes": "界面主题",
    "Intern BPS:": "实习生BPS：",
    "Intern Wage/s:": "实习生工资/s：",
    "JetBrains Mono\n                                            (Monospace)": "JetBrains Mono\n （Monospace）",
    "Key Things to Know": "需要知道的关键事情",
    "Ł - Litecoin (LTC)": "Ł -莱特币（LTC）",
    "Large box that fits multiple burgers for parties": "大盒子，可以装下派对上的多个汉堡",
    "Large Packs": "大包装",
    "Lato": "Lato",
    "Launch with pre-existing buzz! Your restaurant starts with 150% customer demand thanks to an aggressive marketing campaign.": "以预先存在的热度启动！由于积极的营销活动，你的餐厅一开始就有150%的顾客需求。",
    "Law enforcement if legally required": "法律要求时的执法",
    "Learn how we protect and handle your data.": "了解我们如何保护和处理您的数据。",
    "Legal": "法律",
    "Legend BPS:": "传说BPS：",
    "Legend Wage/s:": "工资标准：",
    "Lettuce": "生菜",
    "Lettuce:": "生菜:",
    "Light": "光",
    "Limited Shop:": "限量店：",
    "Load from Cloud": "从云端加载",
    "Load Save File": "加载保存文件",
    "Load Saved": "加载保存",
    "Loading purchase history...": "加载购买历史…",
    "Loading stats...": "加载数据…",
    "Loading your items...": "装载你的物品…",
    "Local Saves Only:": "仅本地保存：",
    "Manual flips produce more burgers": "手动翻盖能生产更多的汉堡",
    "Manual Mastery": "手动控制",
    "Market Trend:": "市场趋势:",
    "Market variance:": "市场差异:",
    "Master Auto-Buyer": "掌握汽车消费国",
    "Master BPS:": "大师BPS：",
    "Master of all trades": "样样精通",
    "Master the art of burger flipping! Start with your first 3 spatula upgrades already purchased and active.": "掌握煎汉堡的艺术！从你已经购买并激活的前3个刮刀升级开始。",
    "Master Wage/s:": "掌握工资/ s:",
    "Max BPS": "最大BPS",
    "Max Demand Cap": "最大需求上限",
    "Max Demand:": "最大需求：",
    "Max out your demand before leaving": "在离开之前把你的需求最大化",
    "Maximum offline time:": "最大离线时间：",
    "Meat Management:": "肉类管理：",
    "Meat Package Sizes": "肉类包装尺寸",
    "Meat prices update every": "肉类价格每日更新",
    "Meat Purchased": "购买肉类",
    "Meat Reserve": "肉类储备",
    "Meat Singularity": "肉类奇点",
    "Medieval Burger": "中世纪汉堡",
    "Medium (Some effects)": "中等（部分效果）",
    "Medium Packs": "中级礼包",
    "Mega Event Container \n                        \n                        ": "超级事件容器\n \n",
    "Mega event distribution network": "大型活动分销网络",
    "Melting the cheese...": "融化奶酪……",
    "Modify, update, or discontinue any aspect of the Game at any time": "随时修改、更新或停止游戏的任何方面",
    "Montserrat": "蒙特塞拉特",
    "MORE meat per click": "每次点击更多的肉",
    "National Pipeline": "国家管道",
    "National Supply Chain \n                        \n                        ": "国家供应链\n \n",
    "National supply chain network": "全国供应链网络",
    "Negotiate better hiring contracts! All employee types cost 10% less to hire, helping you build your workforce faster.": "谈判更好的雇佣合同！所有类型的员工的雇佣成本都降低了10%，这有助于你更快地建立自己的员工队伍。",
    "Net income must be this many times higher than the employee's wage": "净收入肯定比员工工资高这么多倍",
    "Never lose a burger again! Start with the Burger Recovery System already installed at Tier 1, saving dropped burgers.": "再也不要丢汉堡了！从已经安装在第1层的汉堡回收系统开始，保存掉的汉堡。",
    "Next Tier Bonuses 🎯": "下一层奖励🎯",
    "Organic Lettuce (+$1.00 price)": "有机生菜（+$1.00价格）",
    "Organic Onions (+$1.50 price)": "有机洋葱（+ 1.50美元）",
    "Organic Tomatoes (+$1.25 price)": "有机西红柿（+ 1.25美元的价格）",
    "No active investments": "暂无活跃投资",
    "No Daily Reward:": "没有每日奖励：",
    "No decay:": "没有衰减:",
    "No signup required": "无需注册",
    "Not Built": "未建造",
    "Not intended for users under 13. We do not knowingly collect data from children.": "不适合13岁以下用户使用。我们不会故意收集儿童的数据。",
    "Notification Position:": "通知位置：",
    "Notification Settings": "通知设置",
    "Notifications": "通知",
    "Notifications:": "通知:",
    "Notify us immediately of any unauthorized account use": "如有任何未经授权的帐户使用，请立即通知我们",
    "Novice BPS:": "新手BPS：",
    "Novice Wage/s:": "新手工资/秒：",
    "Number Format": "数字格式",
    "Number Format:": "数字格式:",
    "Nunito": "Nunito",
    "Offline Mastery": "离线精通",
    "Once the grace period ends, demand starts decreasing.": "一旦宽限期结束，需求就开始下降。",
    "Onions": "洋葱",
    "Onions:": "洋葱:",
    "Open Sans": "开放Sans",
    "Opening for business...": "开业…",
    "Optimal Price": "最优价格",
    "Optimize your kitchen workflow! All employees produce 25% more burgers through improved processes and equipment.": "优化您的厨房工作流程！通过改进工艺和设备，所有员工的汉堡产量增加了25%。",
    "Optional in-game purchases": "可选的游戏内购买",
    "OR enter email address and create a password": "或者输入电子邮件地址并创建密码",
    "Orders Completed": "订单完成了",
    "Our failure to enforce any provision is not a waiver of our right to do so later.": "我方未能执行任何规定并不表示我方放弃以后执行该规定的权利。",
    "Package 4 burgers at once for hungry families": "一次为饥饿的家庭打包4个汉堡",
    "Pallet Deal": "托盘的交易",
    "Party Box \n                        \n                        ": "派对盒\n \n",
    "Patty BPS:": "佩蒂BPS：",
    "Patty Wage/s:": "帕蒂工资/秒：",
    "Payments are processed through third-party providers": "付款是通过第三方提供商处理的",
    "Perfect for outdoor gatherings and picnics": "适合户外聚会和野餐",
    "Perform maintenance that may temporarily limit access": "执行可能暂时限制访问的维护",
    "Performance Mode": "性能模式",
    "Picnic Basket \n                        \n                        ": "野餐篮\n \n",
    "Pixel Burger": "像素汉堡",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "https://discord.gg/VCcj2cRGCr": "https://discord.gg/VCcj2cRGCr",
    "Roboto": "Roboto",
    "RP/sec": "研究点数/秒",
    "RP:": "研究点数:",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "🎲": "🎲",
    "🏆": "🏆",
    "🏪": "🏪",
    "👆": "👆",
    "👆": "👆",
    "👑": "👑",
    "👤": "👤",
    "👥": "👥",
    "🛡️": "🛡️",
    "🟤": "🟤",
    "$": "$",
    "🧄": "🧄",
    "🥘": "🥘",
    "🥩": "🥩",
    "🗑️": "🗑️",
    "🤖": "🤖",
    "🔐": "🔐",
    "🔒": "🔒",
    "🔓": "🔓",
    "🥄": "🥄",
    "⭐": "⭐",
    "🍔": "🍔",
    "🍽️": "🍽️",
    "🎨": "🎨",
    "🎮": "🎮",
    "🌙": "🌙",
    "👷": "👷",
    "💡": "💡",
    "💰": "💰",
    "💾": "💾",
    "📂": "📂",
    "📅": "📅",
    "📄": "📄",
    "📈": "📈",
    "📊": "📊",
    "📤": "📤",
    "📥": "📥",
    "📦": "📦",
    "🔄": "🔄",
    "⚠️": "⚠️",
    "✏️": "✏️",
    "✕": "✕",
    "✨": "✨",
    "⚡": "⚡",
    "⚙️": "⚙️",
    "⚖️": "⚖️",
    "×": "×",
    "−": "−",
    "☁️": "☁️",
    "⏱": "⏱",
    "👁️": "👁️",
    "ℹ": "ℹ",
    "ðŸ‘¥": "ðŸ‘¥",
    "ðŸ§€": "ðŸ§€",
    "✓": "✓",
    "🌱": "🌱",
    "🧀": "🧀",
    "🚀": "🚀",
    "🧑‍💼": "🧑‍💼",
    "© 2025 Burger Flipper Idle. All rights reserved.": "© 2025 Burger Flipper Idle. All rights reserved.",
    "🌍": "🌍",
    "🌟": "🌟",
    "🌶️": "🌶️",
    "🍄": "🍄",
    "🍅": "🍅",
    "🍞": "🍞",
    "🍯": "🍯",
    "🎯": "🎯",
    "💼": "💼",
    "🥒": "🥒",
    "🥓": "🥓",
    "🥫": "🥫",
    "🥬": "🥬",
    "🧅": "🧅",
    "🔥": "🔥",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "🔒 Prestige ": "🔒 声望 ",
    "🔒\n                            ": "🔒\n                            ",
    "🔧\n                                    ": "🔧\n                                    ",
    "🤫\n                                    ": "🤫\n                                    ",
    "🥄\n                                    ": "🥄\n                                    ",
    "🚀\n                                    ": "🚀\n                                    ",
    "🧂\n                                    ": "🧂\n                                    ",
    "📊\n                                    ": "📊\n                                    ",
    "👤\n                                    ": "👤\n                                    ",
    "👥\n                                    ": "👥\n                                    ",
    "⭐\n                                    ": "⭐\n                                    ",
    "✗\n              ": "✗\n              ",
    "Unlock: ": "解锁: ",
    "⏳\n                                    ": "⏳\n                                    ",
    "Requires: ": "要求: ",
    "Saved: ": "保存于: ",
    "💰 $": "💰 $",
    "+$": "+$",
    "Alien (": "外星人 (",
    "Rare Cook Option": "稀有烹饪选项",
    "Current demand: ": "当前需求: ",
    "Decay rate: ": "需求率: ",
    "Time to minimum: ": "降到最低所需时间: ",
    "Last updated: ": "最近更新: ",
    "American Cheese": "美国芝士",
    "Bacon": "培根",
    "Chef's Prestige Badge": "厨师荣誉徽章",
    "Dijon": "第戎",
    "Goth Burger": "哥特汉堡",
    "Pickles": "泡菜",
    "Gourmet Status": "美食地位",
    "Mushrooms": "蘑菇",
    "Jalapeños": "辣椒",
    "Ketchup": "番茄酱",
    "Master Grill Marks": "烧烤大师标志",
    "Next: ": "下一个: ",
    "Michelin Recognition": "米其林认证",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    "  🟤": "  🟤",
    "  🥩": "  🥩",
    "% per minute": "% 每分钟",
    " price)": " 价格)",
    " burgers/sec": " 汉堡/秒",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+)Sx$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\-\$([\d\.]+)\/s$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\÷([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^🥄 ([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Need (.+)\/sec net income \(currently (.+)$/, '需要净收入达到 $1/秒 (当前 $2'],
    [/^You've been idle for 30 minutes.\n(.+)Demand is starting to decrease!$/, '你已经放置了 $1 分钟。\n$2需求量开始下降了！'],
    [/^Buy (.+) meat per click$/, '每次点击购买 $1 肉'],
    [/^Sell (.+) burgers per sale$/, '每次出售 $1 汉堡'],
    [/^Sell (.+) burger per sale$/, '每次出售 $1 汉堡'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)\/s$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) price$/, '$1 价格'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) BPS$/, '$1 BPS'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) notifications$/, '$1 通知'],
    [/^([\d\.,]+) days$/, '$1 天'],
    [/^\+([\d\.,]+) 🌱 Sesame Seed$/, '+$1 🌱 芝麻种子'],
    [/^([\d\.,]+) CC$/, '$1 CC'],
    [/^🌰 ([\d\.,]+) Seeds$/, '🌰 $1 种子'],
    [/^([\d\.,]+) hours ago$/, '$1 小时前'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^([\d\.,]+) seconds ago$/, '$1 秒前'],
    [/^([\d\.,]+) Hours \(([\d\.,]+)x\)$/, '$1 小时 ($2x)'],
    [/^([\d\.,]+) minutes$/, '$1 分钟'],
    [/^([\d\.,]+)\+ minutes:$/, '$1+ 分钟:'],
    [/^([\d\.,]+)pt$/, '$1 点数'],
    [/^([\d\.,]+)x Speed$/, '$1x 速度'],
    [/^([\d\.,]+)x Larger$/, '$1x 更大'],
    [/^([\d\.,]+)x Effect$/, '$1x 效果'],
    [/^Next update: ([\d\.]+)s$/, '下一次更新: $1秒'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Purchase \$(.+)$/, '购买 \$ $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Current: (.+) price$/, '当前：$1 价格'],
    [/^Burgers: (.+) \/ (.+)$/, '汉堡：$1 \/ $2'],
    [/^Level (.+)\/(.+)$/, '等级 $1\/$2'],
    [/^Level (.+) \/ (.+)$/, '等级 $1 \/ $2'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 2000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();