// ==UserScript==
// @name         Degen Dungeon 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.12
// @description  Degen Dungeon (https://www.degen-dungeon.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Degen Dungeon.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://www.degendungeon.com/favicon.ico
// @include      *degendungeon.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/degen-dungeon-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/degen-dungeon-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/02/17 20:04
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "You": "你",
    "XP": "经验值",
    "Woodcutting": "伐木",
    "Shop": "商店",
    "Skills": "技能",
    "More": "更多",
    "monster": "怪物",
    "Mining": "采矿",
    "Membership": "会员",
    "Level": "等级",
    "Health": "生命值",
    "Inventory": "库存",
    "Character": "角色",
    "Combat History": "战斗记录",
    "Combat": "战斗",
    "Combat Chest": "战斗宝箱",
    "Cooking": "烹饪",
    "Energy": "能量",
    "Crafting": "制作",
    "Fishing": "钓鱼",
    "Forging": "锻造",
    "Alchemy": "炼金",
    "Armored Cave Crawler": "装甲洞穴爬行者",
    "Available Encounters": "可用的遭遇",
    "Cliff Prowler": "悬崖徘徊者",
    "Frosthide Boar": "冰霜猪",
    "Frosthide Wolf": "冰霜狼",
    "Gathering": "采集",
    "Glacial Warden": "冰川监狱长",
    "Glacier Beetle": "冰川甲虫",
    "Herbalism": "草药学",
    "Leaderboards": "排行榜",
    "Leatherworking": "皮革加工",
    "Marketplace": "市场",
    "Muck Bat": "粪蝠",
    "Mud Golem": "泥魔像",
    "Night Spider": "夜蛛",
    "required": "要求",
    "Rotfang": "腐牙",
    "Shadow Rat": "暗影鼠",
    "Snowdrift Owl": "雪原夜枭",
    "Stormhorn": "暴风号角",
    "Swamp Frog": "沼泽蛙",
    "Tailoring": "裁缝",
    "The Dreadmire Colossus": "可怕的巨像",
    "Thunderhorn Ram": "雷角公羊",
    "Tracking": "追踪",
    "Windstrider Hawk": "疾风鹰",
    "No encounters available": "没有可用的遭遇",
    "Damage Dealt:": "造成的伤害:",
    "Damage Taken:": "受到的伤害:",
    "In Progress": "进行中",
    "No items in combat chest": "战斗宝箱空空如也",
    "Character Slot": "角色槽位",
    "Characters": "角色",
    "Coming Soon": "敬请期待",
    "Continue": "继续",
    "Logout": "登出",
    "warrior": "战士",
    "Agility": "敏捷",
    "Attack Speed": "攻击速度",
    "Attack Power": "攻击力量",
    "Combat Stats": "战斗属性",
    "Defense": "防御",
    "for updates and more.": "查看更新和更多内容。",
    "Intelligence": "智力",
    "Join us on": "加入我们的",
    "Primary Stats": "主属性",
    "Strength": "力量",
    "Warrior": "战士",
    "Regenerate your health with food from cooking or health potions from alchemy.": "通过烹饪获得的食物，或炼金获得的生命药水来恢复生命值。",
    "Regenerate your energy with energy potions from alchemy.": "使用炼金术中获得的能量药水来恢复能量。",
    "No character found": "未找到角色",
    "Bank": "银行",
    "bank slots used": "使用的银行插槽",
    "Coal Ore": "煤矿石",
    "Coal Ore.": "煤矿石。",
    "Common": "普通",
    "Copper Bar": "铜锭",
    "Empty": "空",
    "Empty Slot": "空槽位",
    "Equipment Effects": "装备效果",
    "Equips": "装备",
    "Leather Hide": "皮革皮",
    "Manage your items and equipment": "管理你的物品和装备",
    "Oak Logs": "橡树原木",
    "Raw Wool": "原生羊毛",
    "slots used": "已使用槽位",
    "Whisperleaf": "低语之叶",
    "Time": "时间",
    "Speed": "速度",
    "/ Need:": "/ 需要:",
    "Start 1 Action": "开始 1 行动",
    "Stop Task": "停止任务",
    "Weapons": "武器",
    "Max": "最大",
    "Attack": "攻击",
    "Have:": "拥有:",
    "gathered": "已采集",
    "Fishingrod": "鱼竿",
    "Current Task": "当前任务",
    "Resource": "资源",
    "Resources": "资源",
    "Requirements": "需要",
    "Required Bait": "需要鱼饵",
    "Aetherbloom": "以太绽放",
    "Angler": "垂钓者",
    "Angler Soup": "垂钓者汤",
    "Arcanleaf": "神秘叶",
    "Astralis": "黄芪",
    "Available Resources": "可用的资源",
    "Barracuda": "梭鱼",
    "Basic Bait": "初级诱饵",
    "Bodyarmor": "防弹衣",
    "Briarthorn": "刺梨",
    "Briarthorn Resin": "刺梨树脂",
    "Dreamvine": "梦之藤",
    "Dreamvine Sap": "梦藤汁液",
    "Emberpetal": "余烬",
    "Emberpetal Oil": "余烬油",
    "Emberroot": "香蒿",
    "Emberroot Essence": "香蒿精华",
    "Etherbloom": "永恒绽放",
    "Flaxthorn": "亚麻籽",
    "Frosted Sawfish Filet": "凉拌锯鳐鱼片",
    "Frostleaf": "霜叶",
    "Frostleaf Distillate": "霜叶蒸馏液",
    "Grilled Minnow": "烤鲦鱼",
    "Leviathan": "利维坦",
    "Leviathan Roast": "利维坦烤肉",
    "Minnow": "鲦鱼",
    "Moonblossom": "月花",
    "Moonblossom Tincture": "月花酊",
    "Moonglow": "月光草",
    "Mystroot": "神秘根",
    "Mystweave Cloth": "神秘织物",
    "Piranha": "食人鱼",
    "Piranha Stew": "炖食人鱼",
    "Raw Cotten": "原棉",
    "Roasted Snapper": "烤鲷鱼",
    "Sawfish": "锯鳐",
    "Sea Wyrm": "海妖龙",
    "Shadowbloom": "暗影花",
    "Shadowbloom Essence": "暗影花精华",
    "Shadowvine": "影藤",
    "Silkwisp": "蚕丝",
    "Snapper": "鲷鱼",
    "Spiced Sea Wyrm": "五香海龙",
    "Spicy Barracuda": "麻辣梭鱼",
    "Spiritthorn": "荆刺",
    "Spiritthorn Powder": "荆刺粉",
    "Starlotus": "星莲花",
    "Starlotus Extract": "星莲花提取物",
    "Stormray": "暴风",
    "Stormray Filet": "暴风鱼片",
    "Sunpetal": "太阳花瓣",
    "Sunpetal Infusion": "太阳花瓣灌注液",
    "Tigerfish": "虎鱼",
    "Tigerfish Stew": "炖虎鱼",
    "Whisperleaf Extract": "柳叶提取物",
    "You need level 20 Herbalism to gather this resource.": "需要草药学等级达到20级才能采集该资源",
    "Extended Idle Time": "扩展放置时间",
    "Purchase Gems": "购买宝石",
    "Name Highlight": "名字高亮",
    "The membership aims to provide slight gameplay enhancements while ensuring the core game remains fully accessible to all players. No critical content is locked behind the membership paywall.": "会员旨在提供轻微的游戏性增强，同时确保所有玩家都可以完全访问核心游戏。没有关键内容被锁定在会员付费墙后面。",
    "Membership is an optional subscription, activated through a Membership Scroll—an in-game item that can be purchased and traded through the marketplace. This membership provides special benefits to enhance your gaming experience, designed to offer modest improvements without fundamentally altering game balance.": "会员资格是一种可选的订阅，可以通过会员卷轴激活，这是一种可以通过市场购买和交易的游戏内物品。这个会员资格提供特殊的好处，以提高您的游戏体验，旨在提供适度的改进，而不会从根本上改变游戏的平衡。",
    "15% faster action times on all tasks": "所有任务的行动时间加快15%",
    "30 Day Membership Scroll": "30天会员资格卷轴",
    "Activate premium benefits with a Membership Scroll": "使用会员卷轴激活高级福利",
    "Activate this scroll to receive 30 days of premium membership benefits. The scroll can be traded with other players through the marketplace.": "激活此卷轴可获得30天的高级会员福利。卷轴可以通过市场与其他玩家进行交易。",
    "Character receives a distinctive color identifier": "字符接收一个独特的颜色标识符",
    "Enhance your gaming experience with premium benefits": "享受尊享福利，提升您的游戏体验",
    "Expanded from 8 to 12 maximum listings": "从8个扩展到12个最大清单",
    "Increased from 2 hours to 4 hours of idle progression": "从2小时增加到4小时",
    "Increased Listing Limits": "上架上限增加",
    "Membership Benefits": "会员福利",
    "Membership in Degen Dungeon": "剑与地下城的会员资格",
    "Purchase Membership": "购买会员",
    "Skill Efficiency": "技能效率",
    "gems": "宝石",
    "Get gems": "获取宝石",
    "Most popular": "热门",
    "Your balance:": "你的账户:",
    "This is currently an Alpha test and you will be refunded spent gems back to your character with a 20% bonus after alpha. Join our discord if you have any quesitons or need support.": "这是一个目前的Alpha测试，你将会在Alpha测试后获得已消耗宝石的20%的加成返回你的角色。如果您有任何问题或需要支持，请加入我们的discord。",
    "Ore": "矿石",
    "Planks": "板材",
    "Hide": "皮",
    "HP:": "生命值:",
    "Heavy Hide": "重皮",
    "Handles": "手柄",
    "Handle": "手柄",
    "Gemstones": "宝石",
    "Gemstone": "宝石",
    "Estimated health:": "预估生命值：",
    "Dragon Hide": "龙皮",
    "Dragonhide Pouch": "龙皮口袋",
    "Calculating...": "计算中...",
    "Calculating optimal quantity...": "Calculating optimal quantity...",
    "| SPD:": "| 速度:",
    "| ATK:": "| 攻击:",
    "Basic Sap": "Basic Sap",
    "Bone Charcoal": "骨炭",
    "Bowstrings": "弓弦",
    "Bowstring": "弓弦",
    "Monster DPS:": "怪物 DPS:",
    "MONSTERS": "怪物",
    "POSSIBLE LOOT": "可能的战利品",
    "QUANTITY": "数量",
    "Rat": "老鼠",
    "RECOMMENDED QUANTITY": "推荐数量",
    "Reinforced Hide": "加强皮",
    "Sturdy Hide": "韧皮",
    "Thick Hide": "厚皮",
    "Total damage:": "总计伤害:",
    "Time to kill:": "击杀时间:",
    "Tough Hide": "硬皮",
    "Woodcrafting": "木工",
    "You can successfully defeat up to": "你最多可以成功击败",
    "in a single combat session.": "在单个战斗回合中。",
    "All Items": "全部物品",
    "All Listings": "全部挂单",
    "Browse, trade, and claim items": "浏览、交易、领取物品",
    "Claims": "领取",
    "Current Health": "当前生命值",
    "Current Energy": "当前能量",
    "List": "挂单",
    "My Listings": "我的挂单",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Mythic": "神秘",
    "Epic": "史诗",
    "Equipment": "装备",
    "Equip Item": "装备物品",
    "Herbalism Efficiency": "草药学效率",
    "Woodcutting Efficiency": "伐木效率",
    "Tracking Efficiency": "追踪效率",
    "Mining Efficiency": "采矿效率",
    "Gathering Efficiency": "采集效率",
    "Fishing Efficiency": "钓鱼效率",
    "Legendary": "传说",
    "Required Level:": "要求等级:",
    "Quantity:": "数量:",
    "Item Effects:": "物品效率:",
    "Manage": "管理",
    "Manage Item": "管理物品",
    "Consumables": "消耗品",
    "Deposit to Bank": "存入银行",
    "Vendor": "商人",
    "After 20% fee": "扣除 20% 费用之后到手",
    "List Item": "上架物品",
    "Gold": "金币",
    "gold": "金币",
    "Owned:": "拥有:",
    "Price per Item": "单价",
    "Sell to Vendor": "卖给商人",
    "Suggested Price Range": "建议价格范围",
    "You will receive": "你将得到",
    "Listing value": "挂单价格",
    "Bait": "诱饵",
    "Flask": "瓶",
    "Flux": "通量",
    "Sap": "树液",
    "Solution": "溶液",
    "Thread": "线",
    "Buy": "购买",
    "Buy Item": "购买物品",
    "Check back later for available items!": "稍后再来查看可用的项目！",
    "Cost:": "成本:",
    "Insufficient": "不足",
    "Inventory Expansion Slot": "库存扩展槽",
    "Membership Scroll": "会员卷轴",
    "No items available": "暂无可购物品",
    "Purchase items and resources": "购买物品和资源",
    "Total cost": "总成本",
    "Buying...": "购买中...",
    "(Cannot be changed)": "（不可更改）",
    "DD": "DD",
    "Delete Account": "删除账户",
    "Email Address": "电子邮件地址",
    "Manage your membership subscription here.": "在这里管理您的会员订阅。",
    "Membership Source": "会员来源",
    "No active membership": "无有效会员资格",
    "Once your account is deleted, all of its resources and data will be permanently deleted.": "一旦您的帐户被删除，其所有资源和数据将被永久删除。",
    "Process an account deletion and have all of your data destroyed.": "处理一个帐户删除，并销毁你的所有数据。",
    "Profile Information": "个人资料信息",
    "Subscription Ends On": "订阅截止日期：",
    "Update your account's profile information and email address.": "更新您的帐户的个人资料信息和电子邮件地址。",
    "Arena": "竞技场",
    "Compete with other players and climb the ranks!": "与其他玩家竞争，攀登排名！",
    "Overall": "整体",
    "Consume Item": "消耗物品",
    "Starting Combat...": "开始战斗...",
    "Tip: Try improving your combat stats or equipment to fight more monsters at once!": "提示：尝试提高你的战斗属性或装备，以一次对抗更多的怪物！",
    "damage": "伤害",
    "VICTORY!": "胜利!",
    "Duration:": "持续时长:",
    "s remaining": "剩余",
    "Health Left:": "剩余生命值:",
    "Victory": "胜利",
    "taken": "受到的",
    "Failed to process combat": "战斗处理失败",
    "Checking Requirements...": "检查要求...",
    "Dragonhide Leather": "龙皮皮革",
    "Leather Bow": "皮革弓",
    "Leather Handle": "皮革手柄",
    "Mystweave Staff": "神秘编织法杖",
    "No items to claim": "没有可领取的物品",
    "You have no active listings": "你没有上架中的挂单",
    "No Health Remaining": "无剩余生命值",
    "Available Listings": "可用挂单",
    "gold each": "金币每个",
    "gold to make this purchase.": "金币以完成购买。",
    "Insufficient Gold": "金币不足",
    "Insufficient gold. You need": "金币不足。你需要",
    "Marketplace Purchase": "市场购买",
    "of": "",
    "Purchase Quantity": "购买数量",
    "Total Available:": "可用购买:",
    "Total Price": "总价",
    "Crystal": "水晶",
    "Withdraw from Bank": "从银行取出",
    "Create": "创建",
    "Create a character to begin your adventure!": "创建一个角色开始你的冒险！",
    "Create Character": "创建角色",
    "Degen Dungeon is currently in Beta": "Degen Dungeon目前处于测试阶段",
    "Embark on idle expeditions, level up your skills, gather rare loot, and more.": "开始放置探险，升级你的技能，收集稀有的战利品，以及更多。",
    "Enter The Dungeon": "进入地下城",
    "for updates, roadmap and more.": "更新，路线图和更多。",
    "Mobile Idle MMO": "手机放置MMO",
    "No Character Found": "未找到角色",
    "Unlock for free at Character Level 10 or with Character Slot Expansion": "在角色10级或角色插槽扩展中免费解锁",
    "Unlock with Character Slot Expansion": "解锁角色插槽扩展",
    "= Agility,": "=敏捷,",
    "= Intelligence": "=智力",
    "= Strength,": "=力量,",
    "AGI": "敏捷",
    "Agile fighter with the fastest attack speed. Excels at consistent damage output.": "拥有最快攻击速度的敏捷战士。擅长持续的伤害输出。",
    "and certify this is my only account.": "并证明这是我唯一的账户。",
    "Cancel": "取消",
    "Character Name": "角色名称",
    "Choose Your Class": "选择职业",
    "Class Comparison": "职业对比",
    "Durable tank with high health scaling. Strength-based fighter with excellent survivability.": "具有高血量缩放的耐用坦克。以力量为基础的战斗机，具有出色的生存能力。",
    "Each attack can consume 15 Energy to deal bonus damage based on your class's Empowered Bonus": "每次攻击可以消耗15点能量，造成基于你职业授权加成的额外伤害",
    "Empowered Bonus": "授权加成",
    "Energy-rich caster with devastating empowered attacks. Intelligence-based damage dealer.": "能量丰富的施法者，具有毁灭性的强化攻击。基于智力的伤害经销商。",
    "I agree to the": "我同意",
    "INT": "智力",
    "Loading character data...": "加载字符数据…",
    "Mage": "法师",
    "Ranger": "游侠",
    "Rules": "规则",
    "Stat": "属性",
    "STR": "力量",
    ". Creating a new character will allow you to experience different classes and playstyles.": "。创建一个新角色可以让你体验不同的职业和游戏风格。",
    "available": "可用",
    "character": "角色",
    "Create New Character": "创建新角色",
    "Creating Character...": "正在创建角色…",
    "Name must be at least 3 characters long": "名称长度至少为3个字符",
    "Name must start with 3 letters and contain only letters and numbers": "名称必须以3个字母开头，且只能包含字母和数字",
    "ranger": "游侠",
    "Select": "选择",
    "slot": "槽位",
    "You already have": "你已经有",
    "Map": "地图",
    "Altars": "祭坛",
    "Birthday": "生日",
    "Boosted by Gathering, Tailoring, Herbalism, and Alchemy. Increases max energy.": "通过采集，剪裁，草药学和炼金术提升。提升能量上限",
    "Boosted by Mining, Forging, Fishing, and Cooking. Increases max health.": "由采矿，锻造，捕鱼和烹饪推动。增加最大生命值。",
    "Boosted by Tracking, Leatherworking, Woodcutting, and Woodcrafting. Increases attack speed.": "通过跟踪、皮革加工、木刻和木工工艺提升。增加攻击速度。",
    "Boosted by your class's primary attribute: Warrior (Strength), Ranger (Agility), Mage (Intelligence), and by equipping weapons.": "通过你职业的主要属性：战士（力量），游侠（敏捷），法师（智力）和装备武器来提升。",
    "Character Level": "人物等级",
    "Current Map": "当前地图",
    "Dungeoneering": "地下堡垒",
    "Grimmwood": "Grimmwood",
    "Increases with equipped Armor to reduce damage taken.": "随装备护甲增加，减少所受伤害。",
    "Increases with your Agility stat.": "随敏捷属性增加。",
    "Players Idling": "玩家放置中",
    "Replenish energy using Altars or food from Cooking.": "使用祭坛或烹饪食物来补充能量。",
    "Replenish health using Altars or food from Cooking.": "使用祭坛或烹饪的食物来补充生命值。",
    "Total experience from Strength, Agility, and Intelligence, divided by 3. Determines equipment eligibility.": "力量、敏捷和智力的总经验除以3。决定装备资格",
    "Total Level": "总等级",
    "Thank you so much for your dedication during our Alpha phase! You've helped us shape the future of the game, and we want to celebrate your contribution. We’re giving you a special Profile Picture!": "非常感谢您在我们Alpha阶段的奉献！你们帮助我们塑造了游戏的未来，我们想要庆祝你们的贡献。我们要给你一个特别的头像！",
    "Account Settings": "帐户设置",
    "Danger Zone": "危险区域",
    "Delete Character": "删除角色",
    "Delete your current character. This action can be undone by contacting support.": "删除你当前的角色。此操作可以通过联系技术支持来撤销。",
    "Irreversible actions that affect your account and characters.": "不可逆转的行为，影响您的帐户和角色。",
    "Loading mail...": "正在加载邮件…",
    "Mail": "邮件",
    "Manage your account settings and preferences": "管理您的帐户设置和首选项",
    "Mark as read": "标记为已读",
    "Once your account is deleted, all of its resources and data will be permanently deleted. This action cannot be undone.": "一旦您的帐户被删除，其所有资源和数据将被永久删除。此操作不能撤消。",
    "Thanks for Playing Alpha!": "感谢您参与Alpha！",
    "Warning: This will delete your current character and all associated data. You will be redirected to the character selection screen.": "警告：这将删除您当前的角色和所有相关数据。您将被重定向到角色选择屏幕。",
    "Explore More": "探索更多",
    "Lv.": "等级",
    "Travel to other areas on the map to discover more resources and crafting items.": "旅行到地图上的其他地区，以发现更多的资源和制作物品。",
    "before traveling": "旅行之前",
    "Cannot travel while busy": "繁忙时不能旅行",
    "Eldroth": "艾尔德罗斯",
    "Eternal Sands": "永恒之沙",
    "Glacium": "冰天雪地",
    "Marrow Wastes": "骨髓废料",
    "Mordaan": "摩丹",
    "Stormveil": "风暴面纱",
    "Sunken Reefs": "沉没的暗礁",
    "task": "任务",
    "Vyrmire": "维米尔",
    "World Map": "世界地图",
    "You must complete your current": "你必须完成当前",
    "Membership is an optional subscription that provides special benefits to enhance your gaming experience, designed to offer modest improvements without fundamentally altering game balance.": "会员是一个可选的订阅，提供特殊的好处，以提高您的游戏体验，旨在提供适度的改进，而不会从根本上改变游戏的平衡。",
    "Aegis Altar": "圣盾祭坛",
    "Altar cooldown reduced from 3 hours to 2 hours": "圣坛的冷却时间从3小时减少到2小时",
    "Armor": "护甲",
    "Available Altars": "可用祭坛",
    "Bank Slots": "银行槽位",
    "Checking Combat Status...": "检查战斗状态…",
    "Cover": "封面",
    "Eldritch Altar": "邪魔祭坛",
    "Increased from 5 hours to 6 hours of idle progression": "放置进程从5小时增加到6小时",
    "Inventory Slots": "库存槽位",
    "Monthly": "月卡",
    "Monthly Subscription": "月卡订阅",
    "No equipment effects": "没有装备效果",
    "Not Enough Gold": "黄金不够用",
    "PFP": "PFP",
    "Pick": "选择",
    "Prayer Duration": "祈祷时间",
    "Reduced Altar Cooldown": "减少祭坛冷却时间",
    "Restore your health and energy through divine intervention": "通过神的干预恢复你的健康和能量",
    "Rod": "杖",
    "Sacred Altar": "神圣祭坛",
    "Save 30%": "节省30%",
    "Subscribe monthly for continuous access to all membership benefits. Cancel anytime.": "每月订阅以持续获得所有会员福利。随时取消。",
    "Subscribe Now": "现在就订阅",
    "Subscribe yearly for continuous access to all membership benefits. Save 30% compared to monthly billing.": "每年订阅以持续获得所有会员福利。与每月计费相比节省30%。",
    "Wellspring Altar": "泉源祭坛",
    "Yearly": "年卡",
    "Yearly Subscription": "年卡订阅",
    "Drop Chance": "掉率",
    "Duration": "持续时长",
    "inventory slots purchased": "购买的库存槽位",
    "Name": "名称",
    "Loading total skill leaderboard...": "加载总技能排行榜…",
    "Insufficient gold (": "金币不足 (",
    "max": "最大",
    "needed)": "需要)",
    "Show 4 More": "再显示4个",
    "Cheapest": "最便宜",
    "Degen Tip:": "地下城提示:",
    "No combat history yet": "暂无战斗历史",
    "You can idle other tasks while in combat": "你可以在战斗中放置其他任务",
    "BONUSES": "加成",
    "exp": "经验值",
    "Food": "食物",
    "Leonhardt Profile Picture": "莱昂哈特头像",
    "REWARDS": "奖励",
    "rewards)": "奖励)",
    "Whispering Grove Dungeon Ticket": "呓语丛林地下城门票",
    "Required Items:": "需要的物品:",
    "Show Details": "显示详情",
    "minutes": "分钟",
    "Missing Items": "缺少物品",
    "Possible Loot": "可能包含的战利品",
    "Dungeon Chest": "地下城宝箱",
    "Dungeon History": "地下城历史",
    "Dungeon Rooms": "地下城房间",
    "Available Dungeons": "可用地下城",
    "Whispering Grove": "呓语丛林",
    "No items in dungeon chest": "地下城宝箱暂无物品",
    "No dungeon history yet": "暂无地下城历史",
    "Basket Recipe": "篮子 配方",
    "Fishing Rod Recipe": "鱼竿 配方",
    "Trap Recipe": "陷阱 配方",
    "Pouch Recipe": "袋子 配方",
    "Pickaxe Recipe": "镐子 配方",
    "Axe Recipe": "斧头 配方",
    "Not enough materials": "材料不足",
    "Item Effects": "物品效果",
    "Charm": "魅力",
    "Obtained via": "获得来源是",
    "Obtained via Shop": "获得来源是商店",
    "Your Mining task is complete!": "你的采矿任务已完成!",
    "You can now create a second character on the characters select screen!": "现在可以在角色选择界面创建第二个角色了！",
    "Echoes of War Cover": "战争回声封面",
    "Gem Shop": "宝石商店",
    "Gems": "宝石",
    "Selene Profile Picture": "选择个人资料图片",
    "Copper Bar.": "铜锭。",
    "Your Forging task is complete!": "你的锻造任务完成了！",
    "Arcane Crystal.": "奥术水晶。",
    "Your Gathering task is complete!": "你的采集任务完成了！",
    "Attachments available": "可用附件",
    "Claim items": "领取物品",
    "Important": "重要",
    "Tasks": "任务",
    "Claiming...": "领取中...",
    "Confirm Claim": "确认领取",
    "No completed tasks": "暂无已完成的任务",
    "You are currently claiming the item on": "您目前正在领取物品",
    "Date Added:": "添加日期:",
    "Claim": "领取",
    "Sales History": "出售记录",
    "Load More": "加载更多",
    "Loading sales history...": "加载出售历史...",
    "No sales history available": "暂无出售记录",
    "Character Slot Expansion": "角色槽位扩展",
    "claims tab": "领取标签页",
    "Copper Axe.": "铜斧。",
    "Delete All": "全部删除",
    "Find your purchased items in the": "找到你购买的物品",
    "Minnow.": "鲦鱼。",
    "Processing...": "处理中…",
    "Read All": "全部已读",
    "Ruins of the Ancients Cover": "上古遗迹封面",
    "Sands of Eternity Dungeon Ticket": "永恒之沙地下城门票",
    "Show Less": "显示更少",
    "Start Prayer": "开始祈祷",
    "Violet Profile Picture": "紫罗兰头像",
    "Your Crafting task is complete!": "你的制作任务完成了！",
    "Your Fishing task is complete!": "你的钓鱼任务完成了！",
    "adventure": "冒险",
    "Bloomtide Festival": "春日盛典",
    "Choose your path and master unique abilities with three distinct character classes:": "选择你的道路和掌握独特的能力与三个不同的角色类别：",
    "Combat & Dungeons": "战斗&地下城",
    "Compete with players worldwide across all skills and activities. Climb the ranks and prove your worth.": "在所有技能和活动中与世界各地的玩家竞争。爬上去，证明你的价值。",
    "Connect with players and get the latest updates on Discord": "与玩家连接并获得Discord上的最新更新",
    "Desktop": "桌面",
    "Dive into a world of endless possibilities and adventures": "潜入一个充满无限可能性和冒险的世界",
    "Embark on idle expeditions, level up your skills, gather rare loot, and dominate the leaderboards in this immersive MMO experience.": "在这个身临其境的MMO体验中，开始空闲的探险，升级你的技能，收集稀有的战利品，并主宰排行榜。",
    "Expert in ranged combat and swift strikes": "擅长远程战斗和快速打击",
    "Explore a Rich World of Features": "探索一个功能丰富的世界",
    "Explore vast territories, discover hidden dungeons, and uncover rare resources across our expansive world map.": "探索广阔的领土，发现隐藏的地下城，并在我们广阔的世界地图上发现稀有资源。",
    "Form parties with other players to battle fierce monsters, explore dangerous dungeons, and collect epic loot through challenging encounters.": "与其他玩家组队对抗凶猛的怪物，探索危险的地下城，并通过具有挑战性的遭遇收集史诗般的战利品。",
    "Full-featured PC experience": "全功能PC体验",
    "Get ready for your": "准备好你的",
    "Global Hiscores": "全球高分榜",
    "idle": "放置",
    "Interactive World Map": "互动世界地图",
    "Join Discord": "加入Discord",
    "Join Our Community": "加入我们的社区",
    "Market": "市场",
    "Market Exchange": "市场交换",
    "Master diverse skills from combat to crafting. Each skill offers unique progression paths and rewards.": "掌握从战斗到制作的各种技能。每个技能都提供独特的进程路径和奖励。",
    "Master of melee combat and defensive tactics": "精通近战和防御战术",
    "Mobile": "移动端",
    "next": "下一个",
    "Optimized for tablet gameplay": "针对平板电脑游戏进行了优化",
    "Patch Notes": "更新日志",
    "Pets": "宠物",
    "Play Anywhere, Anytime": "随时随地玩",
    "Play on the go with our mobile app": "用我们的移动应用程序玩",
    "Privacy Policy": "隐私政策",
    "Professions": "职业",
    "Progress even while offline. Return to collect resources and experience earned during your absence.": "即使离线也能进步。返回收集在你离开期间获得的资源和经验。",
    "Quick Actions": "快速行动",
    "Rankings": "排名",
    "Seamlessly switch between devices with full cross-platform support:": "设备之间无缝切换，完全跨平台支持：",
    "Search": "搜索",
    "Sign in": "登录",
    "Tablet": "平板电脑",
    "Terms of Service": "服务条款",
    "Trade resources, equipment, and rare items in our player-driven marketplace. Build your wealth through smart trading.": "在玩家驱动的市场中交易资源、装备和稀有道具。通过聪明的交易积累财富。",
    "Up to 6 Hours Idle Time": "高达6小时的放置时间",
    "Wielder of powerful spells and ancient magic": "拥有强大的咒语和古老的魔法",
    "Continue with Apple": "用苹果账号登录",
    "Continue with Google": "用谷歌账号登录",
    "Create one": "创建一个",
    "Get Started": "开始",
    "No account?": "还没有账号？",
    "Already have an account?": "已经有账号了？",
    "Active Days Streak": "连续活跃天数",
    "days": "天",
    "DEF": "防御",
    "Dungeons Completed": "地下城已完成",
    "Monsters Slain": "击杀怪物",
    "Player Stats": "玩家统计",
    "Total Idle Hours": "总计放置时间",
    "Add": "添加",
    "Create a party to adventure with friends": "和朋友们一起创建一个队伍进行冒险",
    "Create Party": "创建队伍",
    "Find Friends": "查找好友",
    "Friends": "朋友",
    "Invites": "邀请",
    "Loading party data...": "正在加载好友数据...",
    "No Active Party": "无可用队伍",
    "Party": "队伍",
    "No characters found": "未找到角色",
    "Pending": "等待中",
    "Search for characters to add them as friends": "搜索角色并添加为好友",
    "slots remaining": "剩余槽位",
    "Sent": "发送",
    "You don't have any friends yet": "你现在还没有朋友",
    "Actions": "行动",
    "Oak Plank.": "橡木板。",
    "REQUIREMENTS": "要求",
    "Calculating task details...": "计算任务详情…",
    "Copper Fishing Rod.": "铜鱼竿。",
    "Copper Ore.": "铜矿石。",
    "Copper Pickaxe.": "铜镐。",
    "Copper Trap.": "铜陷阱。",
    "Leather Hide.": "皮革。",
    "Whisperleaf.": "低语之叶。",
    "Your Herbalism task is complete!": "你的草药学任务完成了！",
    "Your Tracking task is complete!": "你的追踪任务完成了！",
    "Your Woodcrafting task is complete!": "你的木工任务完成了！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "AS": "AS",
    "AP": "AP",
    "DTPS)": "DTPS)",
    "DPS)": "DPS)",
    "Shark Stew": "炖鲨鱼",
    "Shark": "鲨鱼",
    "Leather": "皮",
    "Hat": "帽子",
    "Reinforced Leather": "加强皮革",
    "Heavy Leather": "重皮革",
    "Light Leather": "光皮革",
    "Soft Leather": "软皮革",
    "Sturdy Leather": "韧皮革",
    "Tough Leather": "硬皮革",
    "Thick Leather": "厚皮革",
    "Speed Potion": "速度药水",
    "Health Potion": "生命药水",
    "Energy Potion": "能量药水",
    "Defense Potion": "防御药水",
    "Attack Potion": "攻击药水",
    "Staff": "权杖",
    "Plank": "木板",
    "Logs": "原木",
    "Bow": "弓",
    "Pouch": "袋子",
    "Leather": "皮",
    "Shoes": "鞋子",
    "Robe": "长袍",
    "Basket": "篮子",
    "Cloth": "衣服",
    "Axe": "斧",
    "Bar": "锭",
    "Bodyarmor": "铠甲",
    "Boots": "靴子",
    "Fishing Rod": "鱼竿",
    "Gloves": "手套",
    "Helmet": "头盔",
    "Pickaxe": "镐子",
    "Shield": "盾牌",
    "Sword": "剑",
    "Trap": "陷阱",

    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "GItyx": "GItyx",
    "Degen Dungeon": "剑与地下城",
    "s": "",
    "/": "/",
    "?": "?",
    "•": "•",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    "Gityx": "Gityx",
    "Gz": "Gz",
    "O": "O",
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Silver ": "银",
    "Moonlit ": "月光",
    "Mithril ": "秘银",
    "Mystic ": "神秘",
    "Iron ": "铁",
    "Gold ": "金",
    "Quality ": "优质",
    "Basic ": "基础",
    "Premium ": "会员",
    "Advanced ": "高级",
    "Exotic ": "奇异",
    "Dragonwood ": "龙木",
    "Eternium ": "永恒",
    "Etheric ": "以太",
    "Spirit ": "精神",
    "Standard ": "普通",
    "Superior ": "高级",
    "Umbral ": "阴暗",
    "Lesser ": "小型",
    "Greater ": "大型",
    "Grand ": "巨型",
    "Platinum ": "铂",
    "Radiant ": "辐射",
    "Abyssal ": "深渊",
    "Astral ": "星体",
    "Maple ": "枫木",
    "Mighty ": "强大",
    "Minor ": "迷你",
    "Redwood ": "红木",
    "Lead ": "铅",
    "Adamantite ": "精钢",
    "Aether ": "以太",
    "Arcane ": "奥术",
    "Pine ": "松木",
    "Oak ": "橡木",
    "Wool ": "羊毛",
    "Birch ": "桦木",
    "Eldertree ": "接骨木",
    "Dragonhide Leather ": "龙皮皮革",
    "Leather ": "皮",
    "Reinforced Leather ": "加强皮",
    "Light Leather ": "光皮",
    "Soft Leather ": "软皮",
    "Sturdy Leather ": "韧皮",
    "Heavy Leather ": "重皮",
    "Tough Leather ": "硬皮",
    "Thick Leather ": "厚皮",
    "Ironwood ": "铁木",
    "Cedar ": "雪松",
    "Shadow ": "阴影",
    "Shadowhide ": "暗影",
    "Silk ": "丝绸",
    "Tin ": "锡",
    "Ebony ": "乌木",
    "Linen ": "亚麻",
    "Celestial ": "天体",
    "Copper ": "铜",
    "Cotton ": "棉花",
    "Start Combat ": "开始战斗 ",
    "Whispering Grove Dungeon Ticket: ": "呓语丛林地下城门票: ",
    "Basket Recipe x": "篮子 配方 x",
    "Fishing Rod Recipe x": "鱼竿 配方 x",
    "Trap Recipe x": "陷阱 配方 x",
    "Pouch Recipe x": "袋子 配方 x",
    "Pickaxe Recipe x": "镐子 配方 x",
    "Axe Recipe x": "斧头 配方 x",
    "You finished gathering ": "你完成了采集 ",
    "You finished crafting ": "你完成了制作 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " USD/month": " USD/月",
    " USD/year": " USD/年",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.,]+) \- ([\d\.,]+)$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Start (.+) Actions$/, '开始 $1 行动'],
    [/^Inventory is full! \((.+) slots used\)$/, '库存已满！（已使用 $1 插槽）'],
    [/^Jan ([\d\.,]+), ([\d\.,]+)$/, '$2 年 1 月 $1'],
    [/^Feb ([\d\.,]+), ([\d\.,]+)$/, '$2 年 2 月 $1'],
    [/^Mar ([\d\.,]+), ([\d\.,]+)$/, '$2 年 3 月 $1'],
    [/^Apr ([\d\.,]+), ([\d\.,]+)$/, '$2 年 4 月 $1'],
    [/^May ([\d\.,]+), ([\d\.,]+)$/, '$2 年 5 月 $1'],
    [/^Jun ([\d\.,]+), ([\d\.,]+)$/, '$2 年 6 月 $1'],
    [/^Jul ([\d\.,]+), ([\d\.,]+)$/, '$2 年 7 月 $1'],
    [/^Aug ([\d\.,]+), ([\d\.,]+)$/, '$2 年 8 月 $1'],
    [/^Sep ([\d\.,]+), ([\d\.,]+)$/, '$2 年 9 月 $1'],
    [/^Oct ([\d\.,]+), ([\d\.,]+)$/, '$2 年 10 月 $1'],
    [/^Nov ([\d\.,]+), ([\d\.,]+)$/, '$2 年 11 月 $1'],
    [/^Dec ([\d\.,]+), ([\d\.,]+)$/, '$2 年 12 月 $1'],
    [/^Jan ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 1 月 $1, $3:$4 下午'],
    [/^Feb ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 2 月 $1, $3:$4 下午'],
    [/^Mar ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 3 月 $1, $3:$4 下午'],
    [/^Apr ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 4 月 $1, $3:$4 下午'],
    [/^May ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 5 月 $1, $3:$4 下午'],
    [/^Jun ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 6 月 $1, $3:$4 下午'],
    [/^Jul ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 7 月 $1, $3:$4 下午'],
    [/^Aug ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 8 月 $1, $3:$4 下午'],
    [/^Sep ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 9 月 $1, $3:$4 下午'],
    [/^Oct ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 10 月 $1, $3:$4 下午'],
    [/^Nov ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 11 月 $1, $3:$4 下午'],
    [/^Dec ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) PM$/, '$2 年 12 月 $1, $3:$4 下午'],
    [/^Jan ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 1 月 $1, $3:$4 上午'],
    [/^Feb ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 2 月 $1, $3:$4 上午'],
    [/^Mar ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 3 月 $1, $3:$4 上午'],
    [/^Apr ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 4 月 $1, $3:$4 上午'],
    [/^May ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 5 月 $1, $3:$4 上午'],
    [/^Jun ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 6 月 $1, $3:$4 上午'],
    [/^Jul ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 7 月 $1, $3:$4 上午'],
    [/^Aug ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 8 月 $1, $3:$4 上午'],
    [/^Sep ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 9 月 $1, $3:$4 上午'],
    [/^Oct ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 10 月 $1, $3:$4 上午'],
    [/^Nov ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 11 月 $1, $3:$4 上午'],
    [/^Dec ([\d\.,]+), ([\d\.,]+), ([\d\.,]+):([\d\.,]+) AM$/, '$2 年 12 月 $1, $3:$4 上午'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Level ([\d\.,]+) required$/, '要求等级 $1'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Purchase ([\d\.,]+) item$/, '购买 $1 物品'],
    [/^Purchase ([\d\.,]+) items$/, '购买 $1 物品'],
    [/^Show ([\d\.,]+) More$/, '再显示 $1 个'],
    [/^Congrats on hitting level ([\d\.,]+)!$/, '恭喜你达到 $1 级！'],
    [/^([\d\.,]+) Unique Skills$/, '$1 独特技能'],
    [/^([\d\.,]+) Unique Character Classes$/, '$1 独特角色职业'],
    [/^([\d\.,]+) Players Idling$/, '$1 玩家放置中'],
    [/^([\d\.,]+) minutes$/, '$1 分钟'],
    [/^([\d\.,]+)h ([\d\.,]+)s$/, '$1 小时 $2 秒'],
    [/^([\d\.,]+)H$/, '$1 小时'],
    [/^([\d\.,]+) day ago$/, '$1 天前'],
    [/^([\d\.,]+) days ago$/, '$1 天前'],
    [/^([\d\.,]+) minutes ago$/, '$1 分钟前'],
    [/^([\d\.,]+) hours and ([\d\.,]+) minutes ago$/, '$1 小时 $2 分钟前'],
    [/^([\d\.,]+) hours and ([\d\.,]+) minute ago$/, '$1 小时 $2 分钟前'],
    [/^([\d\.,]+):([\d\.,]+) PM$/, '下午 $1:$2'],
    [/^([\d\.,]+):([\d\.,]+) AM$/, '上午 $1:$2'],
    [/^\+([\d\.]+) per STR$/, '\+$1 每点 力量'],
    [/^\+([\d\.]+) per INT$/, '\+$1 每点 智力'],
    [/^\+([\d\.]+) per AGI$/, '\+$1 每点 敏捷'],
    [/^Level ([\d\.,]+) Combat$/, '等级 $1 战斗'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Room ([\d\.,]+): Forest Sprite x([\d\.,]+)$/, '房间 $1: 森林精灵 x$1'],
    [/^Room ([\d\.,]+): Wood Wasp x([\d\.,]+)$/, '房间 $1: 树蜂 x$1'],
    [/^Room ([\d\.,]+): Oak Gnarl x([\d\.,]+)$/, '房间 $1: 橡树节 x$1'],
    [/^Room ([\d\.,]+): Forest Guardian x([\d\.,]+)$/, '房间 $1: 森林守护者 x$1'],
    [/^Room ([\d\.,]+): Mossling x([\d\.,]+)$/, '房间 $1: 苔藓 x$1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");
    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();