// ==UserScript==
// @name         Farming Simulation Tycoon 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.1
// @description  网页游戏 Farming Simulation Tycoon (https://farmingsimulationtycoon.com/register.php?ref=77c80b2f267a2ff1) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Farming Simulation Tycoon.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://farmingsimulationtycoon.com/images/logo.png
// @license      MIT
// @include      *https://farmingsimulationtycoon.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/farming-simulation-tycoon-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/farming-simulation-tycoon-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/11/22 11:58
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "New?": "新玩家?",
    "Login": "登录",
    "Guest:": "游客:",
    "Forgot Password?": "忘记密码？",
    "Don't Show Again": "不再显示",
    "Send": "发送",
    "Try as Guest": "以游客身份试玩",
    "Remember Me": "记住我",
    "Register here": "在这里注册",
    "Play with Sound": "开启游戏声音",
    "Community Spotlight": "社区焦点",
    "Back to Login": "返回登录",
    "Continue": "继续",
    "Join the Farm! 🌱": "加入农场! 🌱",
    "Click below": "点击下面",
    "Build your": "建造你的",
    "Already a farmer?": "已经是一名农夫了？",
    "Log In": "登录",
    "Play as Guest": "以游客身份进行游戏",
    "Sign up now and claim your": "立即注册并领取你的",
    "Legendary Farmers": "传奇农夫",
    "Farm Simulation Tycoon": "农场模拟大亨",
    "! Join thousands of farmers now!": "! 立即加入到数千农夫的行列中!",
    "Start Your Farm Adventure!": "开始你的农场冒险!",
    "Starter Seed Pack": "入门种子包",
    ", grow epic crops, raise adorable animals, and become a legend in": "，种植史诗般的作物，饲养可爱的动物，并成为一个传奇",
    "to explore as a guest — no signup needed!": "探索以游客身份 - 不需要注册!",
    "to kickstart your farm! 🚜": "来启动你的农场！🚜",
    "Try Before You Join!": "先试试再加入！",
    "Want to see the game in action?": "想看看游戏的实际操作吗？",
    "dream farm": "梦幻农场",
    "Carrots": "胡萝卜",
    "Corn": "玉米",
    "Farm": "农场",
    "Farm Development Level:": "农场开发等级:",
    "Energy Drink": "能量饮料",
    "Fullscreen": "全屏",
    "Accept": "接受",
    "Active just now": "活动于刚刚",
    "Chat": "聊天",
    "Barn": "谷仓",
    "Claim these to get a head start!": "领取这些，就能抢占先机！",
    "Decline": "拒绝",
    "Downtown": "市中心",
    "Got It!": "知道了!",
    "Current Season:": "当前季节:",
    "Potatoes": "土豆",
    "Profile": "个人资料",
    "Quantum": "Quantum",
    "Quests": "任务",
    "Shops": "商店",
    "Plant Crops": "种植作物",
    "Online Players:": "在线玩家:",
    "Notifications": "通知",
    "No crops growing.": "暂无种植作物。",
    "OK": "确定",
    "Navigation": "导航",
    "Home": "首页",
    "Hay": "干草",
    "Logout": "登出",
    "Messages": "消息",
    "Spring": "春季",
    "Support": "支持",
    "Tomatoes": "西红柿",
    "Welcome,": "欢迎,",
    "Wheat": "小麦",
    "Light Mode": "浅色模式",
    "Workers don't use energy harvesting": "工人们不使用能量收割",
    "Your Starter Pack!": "你的入门包!",
    "Growing Crops": "生长中的作物",
    "Dark Mode": "深色模式",
    "Animal Pasture": "动物牧场",
    "Armory": "军械库",
    "Back to Farm": "返回农场",
    "No Barn": "没有谷仓",
    "Health Pack": "医疗包",
    "Search Barn": "搜索谷仓",
    "Sell": "出售",
    "Sell All": "出售所有",
    "Sell All Crops": "出售所有作物",
    "Send Items": "发送物品",
    "Usable item": "可用物品",
    "Use": "使用",
    "Your Barn": "你的谷仓",
    "Back to Barn": "返回谷仓",
    "Livestock Market": "牲畜市场",
    "No sheds owned. Visit the Livestock Market to buy some!": "没有棚屋。去家畜市场买一些吧！",
    "INFO!": "信息!",
    "item": "物品",
    "for": "为",
    "Close": "关闭",
    "Clothing": "服装",
    "Equipped Gear": "已装备物品",
    "None": "无",
    "Nothing equipped": "暂无已装备",
    "To Gun Store": "前往枪店",
    "Weapons": "武器",
    "Your Armory": "你的军械库",
    "TAP": "点击",
    "Armor": "盔甲",
    "Attachments": "附件",
    "Sidearms": "配枪",
    "Modify": "改装",
    "Inventory (Excluding Attachments)": "库存（不含附件）",
    "All Categories": "所有类型",
    "👁️ Profile Views:": "👁️ 查看个人资料:",
    "Agility": "敏捷",
    "Bank": "银行",
    "Burn House": "谷仓房屋",
    "Cancel": "取消",
    "Cash": "现金",
    "Comments": "评论",
    "Current Barn": "当前谷仓",
    "Current House": "当前房屋",
    "Change Profile Picture": "更换个人资料图片",
    "Last Active": "最近活动",
    "Level": "等级",
    "Health": "生命值",
    "Defense": "防御",
    "Most Recent Visitor:": "最近访客:",
    "No comments yet.": "暂无评论。",
    "Profile Picture": "个人资料图片",
    "Send Money": "发送金钱",
    "Strength": "力量",
    "Username": "用户名",
    "Your Profile": "你的个人资料",
    "You cannot perform actions on your own profile.": "您不能对自己的个人资料执行操作。",
    "Inbox": "收件箱",
    "New Message": "新消息",
    "No notifications yet.": "暂无通知。",
    "No messages yet.": "暂无消息。",
    "Sent": "已发送",
    "Back to Downtown": "回到市中心",
    "Dog Breeder": "狗饲养员",
    "Drug Store": "药店",
    "Farm Land": "农田",
    "Farm Shops": "农场商店",
    "Food Store": "食品商店",
    "Gun Store": "枪支商店",
    "Realtor's Office": "地产经纪人办公室",
    "Tractor Supply": "拖拉机供应",
    "Exit Fullscreen": "退出全屏",
    "Ready!": "已就绪!",
    "Harvest": "收割",
    "Crop ready to sell": "作物等待出售",
    "Sellable item": "可出售物品",
    "Straw": "稻草",
    "An error occurred while harvesting.": "收割时发生错误。",
    "Coming Soon!!!": "即将推出!!!",
    "First Seeds": "第一颗种子",
    "Go to your farm and plant a Wheat crop in an available plot.": "去你的农场，在一块可用的土地上种一棵小麦。",
    "Level Rewards": "升级奖励",
    "Shady Quest": "阴暗的任务",
    "Hide Past Quests": "隐藏过去的任务",
    "Show Past Quests": "显示过去的任务",
    "Welcome to your farm! Plant your first Wheat crop to begin your journey.": "欢迎来到你的农场！种下第一棵小麦，开始你的旅程。",
    "No completed quests yet.": "暂无已完成任务。",
    "Claim": "领取",
    "Back to Quests": "返回任务",
    "Billy needs you to hit the Gun Store Downtown. Get in, grab some gear, and get out. Don't get caught!": "比利要你去市中心的枪店。进去，拿些装备，然后出去。不要被抓住！",
    "Billy's Shady Jobs": "比利的阴暗工作",
    "Go Downtown, visit the Gun Store, and 'acquire' some goods for Billy. Careful not to get spotted!": "去市中心，参观枪支商店，为比利“买”一些东西。小心别被发现！",
    "Quest": "任务",
    "Rob the Gun Store": "抢劫枪支商店",
    "Show Past Jobs": "显示过去的工作",
    "Harvest Time": "收获时间",
    "Harvest your Wheat crop from the farm to add it to your inventory.": "从农场收割小麦，将其添加到你的库存中。",
    "Quest 'First Seeds' completed! Gained 50 XP and $100.": "任务“第一颗种子”完成！获得50点经验和$100。",
    "Your Wheat is ready! Harvest it to store in your barn.": "小麦准备好了！收获后会储存在谷仓里。",
    "Go sell your wheat at the barn!": "去谷仓里卖小麦吧！",
    "Market Day": "集市日",
    "Quest 'Harvest Time' completed! Gained 75 XP and $250.": "任务“收割时间”完成！获得75点经验和$250。",
    "Visit the Barn and sell your Wheat from your inventory.": "访问谷仓并从库存中出售小麦。",
    "Expand the Fields": "扩展农田",
    "Plant three Corn crops in available plots on your farm.": "在你农场的可用地块上种植3棵玉米作物。",
    "Your farm is growing! Plant some Corn to diversify.": "你的农场在成长！种植一些玉米以实现多样化。",
    "Farming is hard work! Hire a Basic Worker to assist with harvesting. go downtown and browse the Hiring Agency to find a worker! Hired Harvest Unlock is required!": "务农是一项艰苦的工作！雇佣一个基本工人协助收割。去市中心的招聘机构找一个工人！雇佣收获解锁是必需的！",
    "Go to the Workers section and hire a Basic Worker.": "前往工人区雇佣一个基础工人。",
    "Hire Help": "雇佣帮手",
    "Quest 'Expand the Fields' completed! Gained 150 XP and $300.": "任务“扩展领域”完成！获得150经验值和$300。",
    "Example: Start by buying a Small Dog House to create space for dogs. Then, adopt a dog like a German Shepherd and purchase dog food to feed it. Visit the Dog House page to train your dogs!": "例子：从买一个小狗屋开始，为狗创造空间。然后，领养一只像德国牧羊犬一样的狗，并购买狗粮喂养它。访问狗屋页面来训练你的狗！",
    "This is your one-stop shop to start your dog training empire! Purchase dog houses to provide shelter, adopt dogs to train and protect your farm, and buy dog food to keep them happy and healthy.": "这是你的一站式商店，开始你的狗训练帝国！购买狗屋提供庇护，收养狗来训练和保护你的农场，买狗粮让他们快乐和健康。",
    "Bulldog": "斗牛犬",
    "Buy": "购买",
    "Dog Food": "狗粮",
    "German Shepherd": "德国牧羊犬",
    "Large Dog House": "大型狗屋",
    "Mixed Breed": "杂交品种",
    "No dog house owned": "暂无狗屋",
    "Not enough money": "没有足够的钱",
    "Small Dog House": "小狗屋",
    "Welcome to the Dog Breeder!": "欢迎来到狗饲养员！",
    "Already own this dog house": "已拥有此狗屋",
    "Dog House": "狗屋",
    "Purchased 1 Small Dog House for $1000!": "花费$1000购买了1个小型狗屋！",
    "Purchased 1 Dog Food for $100!": "花费$100购买了1狗粮！",
    "This is where you manage your dog houses and train your dogs! Add dogs, feed them with Dog Food, and add Straw for comfort to boost training. Train your dogs to improve their stats and protect your farm.": "这是你管理狗窝和训练狗的地方！添加狗，用狗粮喂养它们，并添加稻草以促进训练。训练你的狗来提高他们的状态和保护你的农场。",
    "Add Feed": "添加饲料",
    "Add Straw": "添加稻草",
    "Add Dog Food": "添加狗粮",
    "Back to Home": "返回首页",
    "Dogs:": "狗:",
    "Welcome to the Dog House!": "欢迎来到狗屋!",
    "❌ Need dog food to breed": "❌ 需要投喂狗粮",
    "No dogs in this dog house. Add some below!": "狗屋中暂无狗狗。在下面添加一些！",
    "Example: Add a German Shepherd, feed it, add Straw, then train it! Now with breeding!": "例如：添加一只德国牧羊犬，喂它，添加稻草，然后训练它！现在开始繁殖!",
    "❌ Need straw for comfort": "❌ 需要稻草来安慰",
    "• 3-20 characters": "•3-20个字符",
    "• Costs 1 gold (you have:": "• 花费1黄金 (你有：",
    "• Letters, numbers, underscores, and hyphens only": "• 只能输入字母、数字、“_”和“-”",
    "• Must be unique": "• 必须是独一无二的",
    "← Back to Farm": "← 返回农场",
    "🌾 Farm Simulation Tycoon": "🌾农场模拟大亨",
    "$FarmSimTycoon": "$FarmSimTycoon",
    "1. Choose an amount and submit your request": "1. 选择一个金额并提交您的请求",
    "2. Send payment to": "2. 付款给",
    "3. Include your Transaction ID in the payment note": "3. 在付款通知单中包括您的交易ID",
    "4. Gold is credited after verification": "4. 黄金在验证后记入账户",
    "Change Username": "更改用户名",
    "Change Username (1 Gold)": "更改用户名（1黄金）",
    "Continue with Donation": "继续捐赠",
    "Customize your display name. You can change your username anytime for 1 gold. Your login credentials will also be updated.": "自定义显示名称。你可以随时改变你的用户名1黄金。您的登录凭证也将被更新。",
    "Donation Amount (USD)": "捐款金额（美元）",
    "How It Works": "它是如何工作的",
    "New Username": "新用户名",
    "Premium Benefits": "高级福利",
    "Requirements": "要求",
    "Support & Earn Gold": "支持&获得金币",
    "Upgrade your experience and support the game": "升级你的体验，支持游戏",
    "Your support helps us maintain and improve Farm Simulation Tycoon. Every dollar donated converts directly to gold in your account.": "您的支持有助于我们维护和改进农场模拟大亨。捐赠的每一美元都直接转换成你账户里的黄金。",
    "Activities": "活动",
    "Casino": "游戏厅",
    "Crew": "兵团",
    "Downtown Hub": "市区中心",
    "Flea Market": "跳蚤市场",
    "Gym": "健身房",
    "Hall of Fame": "名人堂",
    "Hiring Agency": "招聘机构",
    "Hospital": "医院",
    "Pool Hall": "台球厅",
    "Services": "服务",
    "Shop": "商店",
    "Tractor Pulls": "牵引车",
    "Travel": "旅行",
    "Visit Jail": "参观监狱",
    "Copy Link": "复制链接",
    "Basic Worker": "基础工人",
    "Claim Rewards": "领取奖励",
    "Hired Harvest Unlock": "雇佣收割解锁",
    "Referral Placeholder": "推荐占位符",
    "Referral Program": "推荐计划",
    "Referral Stats": "推荐统计",
    "Referral ": "推荐",
    "Invite friends with your referral link! Earn 10,000 coins per referral when they reach Farm Level 5.": "使用推荐链接邀请好友！当他们达到农场5级时，每个推荐都能让你获得10,000金币。",
    "No workers currently hired.": "目前没有雇佣工人。",
    "Referral link copied to clipboard!": "推荐链接已复制至剪贴板！",
    "Skilled Worker": "技术工人",
    "Stats Placeholder": "统计占位符",
    "Unlock Placeholder": "解锁占位符",
    "Unlock Required": "需要解锁",
    "Worker Placeholder": "工人占位符",
    "Your Hired Workers": "你雇佣的工人",
    "Your Referral Link": "您的推荐链接",
    "Owned": "雇佣",
    "Hire": "雇佣",
    "Purchased Hired Harvest Unlock for $1000! You can now use the Hired Harvest feature.": "购买了雇佣收割解锁花费了 $1000！你现在可以使用雇佣收割功能了。",
    "Hired Basic Worker for $100! Can harvest 10 times, every 5 seconds.": "雇佣基础工人花费了$100！可以收获10次，每5秒一次。",
    "Ready to harvest": "准备收割",
    "Hired Harvest": "已雇佣收割",
    "Need a Farm Fridge!": "需要一个农场冰箱！",
    "Invest in your farm's future by upgrading your Farm Level.": "通过升级农场等级来投资农场的未来。",
    "Quest 'Hire Help' completed! Gained 200 XP and $500.": "任务“雇佣帮手”完成！获得200 经验值和 $500。",
    "Upgrade Your Farm": "升级你的农场",
    "Upgrade your Farm Level to 3 by earning XP and spending resources.": "通过获得经验值和消耗资源将农场升级到3级。",
    "Refill Energy (50 Coins)": "恢复能量 (50 金钱)",
    "Train (10 Energy)": "训练 (10 能量)",
    "Train your stats and become the ultimate farmer!": "训练你的属性，成为终极农民！",
    "Gym - Farm Simulation Tycoon": "健身房 - 农场模拟大亨",
    "Action": "动作",
    "Blackjack 21": "21点",
    "Item:": "物品:",
    "Games": "游戏",
    "Wool": "羊毛",
    "Player": "玩家",
    "Item": "物品",
    "Select an item": "选择一个物品",
    "Start Blackjack": "开始21点",
    "Annie Oakley Heritage Rough Rider 22LR": "安妮·奥克利传统粗糙骑手22LR",
    "Bet:": "下注：",
    "Click to bet farm cash against another player. 50% chance to win double or lose it all.": "点击与另一个玩家PK农场现金。50%的机会赢得两倍或输掉所有。",
    "Click to bet items from your inventory against another player. 50% chance to win their item or lose yours. Opponent must bet the same item and quantity.": "点击可将背包中的物品与其他玩家对赌。50%概率赢得对方物品，或输掉自己物品。对手必须投注相同的物品和数量。",
    "Click to play against the dealer. Minimum bet: $10.": "点击与庄家对战。最低投注：$10。",
    "DarkFury": "DarkFury",
    "Deposit": "存款",
    "Deposit to Chips:": "存入筹码：",
    "Goat Milk": "羊奶",
    "mistress": "mistress",
    "Pending Bets from Other Players": "其他玩家的未决投注",
    "Pending Item Flip Bets from Other Players": "等待其他玩家的物品翻转赌注",
    "Place Coin Flip Bet": "抛硬币下注",
    "Place Item Flip Bet": "放置物品下注",
    "Place up to 5 more Item Flip bets. Select an item from your inventory.": "放置最多5个物品进行投注。从你的库存中选择一件物品。",
    "Quantity": "数量",
    "Quantity: ": "数量:",
    "Tactical Helmet": "战术头盔",
    "Withdraw": "提现",
    "Withdraw to Cash:": "提取现金：",
    "Hit": "加牌",
    "Stand": "保持",
    "Play Again? Bet:": "再玩一次? 下注:",
    "No, Back to Menu": "不了，返回菜单",
    "Yes, Play Again": "是的，再玩一次",
    "Your Pending Bets": "您的未完成投注",
    "Place up to 4 more Item Flip bets. Select an item from your inventory.": "放置最多4个物品进行下注。从你的库存中选择一件物品。",
    "Your Pending Item Flip Bets": "您的未完成物品投注",
    "You won a Coin Flip against": "你在抛硬币中战胜了",
    "Back to Shops": "返回商店",
    "Community Contribution": "社区贡献",
    "Create a listing in the Flea Market with any item from your inventory.": "在跳蚤市场创建一个清单，列出你库存中的任何物品。",
    "Quest 'Upgrade Your Farm' completed! Gained 300 XP and $1000.": "任务“升级你的农场”完成！获得300经验值和$1000",
    "The town needs your help! Create a listing on the Flea Market and post it for sale!": "小镇需要你的帮助！在跳蚤市场上创建一个清单，并张贴出来出售！",
    "You won an Item Flip against": "你在物品投注中战胜了",
    "Double stat gains for 5 minutes at gym": "在健身房5分钟内获得双倍属性增益",
    "Grants unlimited energy for 5 minutes": "给予无限能量，持续5分钟",
    "Gym Booster": "健身房助推器",
    "Not enough gold": "没有足够的黄金",
    "Unlimited Energy Pill": "无限能量药丸",
    "Beef Cattle": "肉牛",
    "Cattle Pen": "牛栏",
    "Chicken": "鸡",
    "Chicken Shed": "鸡棚",
    "Goat": "山羊",
    "Goat Shelter": "山羊圈",
    "Hog Barn": "猪舍",
    "Milking Barn": "挤奶棚",
    "Milking Cow": "奶牛",
    "No shed owned": "暂未拥有畜棚",
    "Pig": "猪",
    "Sheep": "绵羊",
    "Sheep Barn": "绵羊棚",
    "Add": "添加",
    "Add Goat": "添加山羊",
    "Add Hay": "添加干草",
    "Product:": "产出:",
    "Collect": "收集",
    "🌾 Flea Market 🌾": "🌾 跳蚤市场 🌾",
    "12Gauge BuckShot": "12口径霰弹",
    "All Types": "所有类型",
    "Armory Item": "军械库物品",
    "Armory Items": "军械库物品",
    "Crop": "作物",
    "Crops": "作物",
    "Filter": "过滤器",
    "Flea Market - Farm Simulation Tycoon": "跳蚤市场-农场模拟大亨",
    "Item Type:": "物品类型：",
    "List an Item": "上架一个物品",
    "List Item": "上架物品",
    "Next": "下一页",
    "Previous": "上一页",
    "Price per Unit ($):": "单价（$）：",
    "Quantity:": "数量:",
    "Select Item": "选择物品",
    "Select Type": "选择类型",
    "Remove": "移除",
    "9mm": "9mm子弹",
    "Quest 'Community Contribution' completed! Gained 500 XP and $2000.": "任务“社区贡献”完成！获得500点经验值和$2000",
    "Rest Up!": "好好休息！",
    "Visit your Home and take a nap to rest.": "拜访自己的家园，打个盹休息一下。",
    "You seem tired! Go inside your home and take a nap or sleep to restore your energy.": "你看起来很累！回到家里打个盹或睡一觉来恢复能量。",
    "Farming Simulation Tycoon": "农场模拟大亨",
    "Go Inside": "进入",
    "Trailer": "旅行拖车",
    "": "",
    "Your house is already at full health!": "你的房屋已经修好了!",
    "🌾 Back to Farm": "🌾 返回农场",
    "🚪 Step Outside": "🚪 离开",
    "Calendar": "日历",
    "Computer": "电脑",
    "Long Sleep (Full Energy, 10s)": "长睡（满能量，10秒）",
    "Nap": "午睡",
    "Short Nap (+25 Energy, 5s)": "小睡（+25能量，5秒）",
    "Sleep": "睡觉",
    "Sleeping...": "睡觉中...",
    "Energy is full, but sleep attempt counted for quest!": "能量充足，但睡眠尝试算作任务！",
    "Back to Game": "返回游戏",
    "Days in this Season": "当前季节天数",
    "Next Season": "下一季节",
    "No note set": "无备注组",
    "Previous Season": "上一季节",
    "Save Note": "保存笔记",
    "Season Calendar": "季节日历",
    "Go to Downtown, enter the Games area, and place a bet on a Coin Flip.": "去市中心，进入游戏区，在抛硬币上下注。",
    "Head to Downtown, enter the Games area, and place a 50/50 Coin Flip bet against another player!": "前往市中心，进入游戏区，并放置一个50/50的抛硬币与另一个玩家PK！",
    "Place a Coin Flip Bet": "抛硬币PK",
    "Quest 'Rest Up!' completed! Gained 250 XP and $250.": "任务“休息！”“完成!获得250经验值和$250。",
    "Help the Elder Family Clean Out Their Barn": "帮助长辈清理他们的谷仓",
    "Quest 'Place a Coin Flip Bet' completed! Gained 100 XP and $200.": "任务“抛硬币PK”完成！获得100经验和$200。",
    "Search the Barn in Downtown to help the Elder family clean it out.": "搜索市中心的谷仓，帮助埃尔德家族清理它。",
    "The Elder family needs help cleaning their old barn. Head to the barn and search it to uncover hidden items!": "埃尔德一家需要帮助清理他们的旧谷仓。前往谷仓并搜索它以发现隐藏的物品！",
    "Empty-handed, but you got 5 XP!": "空手而归，但你获得了5经验值！",
    "Nada! Try again, farmer!": "没有！再试一次，农夫！",
    "Just some dust and cobwebs in here...": "这里只有灰尘和蜘蛛网...",
    "The barn's hiding its treasures today!": "谷仓今天把宝藏藏起来了！",
    "Keep searching... nothing found this time!": "保持搜索...这次什么也没找到！",
    "Visit the local gun store to prepare for potential conflicts. A firearm is not required but highly recommended! Some farmers may not take kindly to you being near their land, and others might simply dislike your name. Clothing adds protection, and attachments can enhance your agility!": "去当地的枪支商店，为潜在的冲突做好准备。枪支不是必需的，但强烈建议！有些农民可能不喜欢你靠近他们的土地，而其他人可能只是不喜欢你的名字。衣服可以增加保护，附件可以增强你的敏捷性！",
    "Go to Downtown, visit the Shops, and enter the Gun Store. No purchase required, just take a look around!": "前往市中心，参观商店，进入弹药商店。不需要购买，只是看看周围！",
    "Quest 'Help the Elder Family Clean Out Their Barn' completed! Gained 150 XP and $300. Farm Fridge unlocked!": "任务“帮助长辈清理他们的谷仓”完成！获得150经验值和$300。农场冰箱已解锁！",
    "Visit the Gun Store": "参观枪支商店",
    "Limit reached": "已达上限",
    "Eggs": "鸡蛋",
    "Add Beef Cattle": "添加肉牛",
    "Add Chicken": "添加鸡",
    "Add Wheat": "添加小麦",
    "Beef": "牛肉",
    "Game Chat": "游戏聊天",
    "Search limit reached! Try again later.": "已达到搜索上限！请稍后再试。",
    "lighter": "打火机",
    "Manure": "粪肥",
    "Auto-Harvest Tractor": "自动收割拖拉机",
    "Farm Fridge": "农场冰箱",
    "Fertilizer": "肥料",
    "To Armory": "请问军械库",
    "Desert Eagle": "沙漠之鹰",
    "Desert Eagle Ammo": "沙漠之鹰弹药",
    "Desert Eagle Gold Finish": "沙漠之鹰金色涂装",
    "Desert Eagle Red Dot": "沙漠之鹰红点",
    "No compatibility info": "无兼容性信息",
    "Boots Steel Toe": "钢头靴",
    "Ammo Box": "弹药箱",
    "Glock": "格洛克",
    "Combat Shirt": "战斗衬衫",
    "Cargo Pants": "工装裤",
    "Camo Pants Ghillie": "吉利迷彩裤",
    "Glock Extended Clip": "格洛克加长弹夹",
    "Glock Laser": "格洛克激光器",
    "Glock Suppressor": "格洛克消音器",
    "Helmet Comms": "头盔通讯",
    "Helmet Night Vision": "头盔夜视",
    "IceGripper": "破冰器",
    "Kevlar Vest": "凯夫拉背心",
    "Kevlar Vest Plates": "凯夫拉防弹背心板",
    "Kevlar Vest Pouches": "凯夫拉背心袋",
    "M16 Laser": "M16激光器",
    "M16 Red Dot Sight": "M16红点瞄准镜",
    "M16 Suppressor": "M16消音器",
    "Pants Extra Pockets": "额外的裤子口袋",
    "Pants Knee Pads": "裤子护膝",
    "Revolver": "左轮手枪",
    "Riot Shield": "防暴盾牌",
    "Rob Gun Store": "抢劫枪械店",
    "Shield Reinforced Edge": "护盾加固边",
    "Shield Window Tint": "盾窗色调",
    "Shirt Camo Pattern": "衬衫迷彩图案",
    "Shirt Elbow Pads": "衬衫肘垫",
    "Shotgun": "霰弹枪",
    "Shotgun Choke": "霰弹枪节流器",
    "Shotgun Slug Rounds": "霰弹枪子弹",
    "Shotgun Stock": "霰弹枪枪托",
    "Sniper Rifle": "狙击步枪",
    "Sniper Rifle Bipod": "狙击步枪两脚架",
    "Sniper Rifle High-Cal Ammo": "狙击步枪高强度弹药",
    "Sniper Rifle Thermal Scope": "狙击步枪热瞄准镜",
    "Tactical Boots": "战术靴",
    "weapon or attachment": "武器或附件",
    "You got caught and sent to jail!": "你被抓了，进了监狱！",
    "Pay Fine": "缴纳罚款",
    "Time Remaining:": "剩余时间:",
    "Try to Escape": "尝试逃跑",
    "You got caught robbing the gun store! You're in jail.": "你因为抢劫枪械店被抓了！你在监狱里。",
    "You’re in Jail!": "你在监狱里!",
    "You’ve been caught and locked up.": "你被抓起来了。",
    "You escaped jail!": "你逃离了监狱!",
    "Check out the Level Rewards page to see what you can earn as you level up!": "查看等级奖励页面，看看你可以获得什么，因为你升级了！",
    "Click the Level Rewards button to visit the Level Rewards page.": "点击等级奖励按钮，进入等级奖励页面。",
    "Quest 'Visit the Gun Store' completed! Gained 200 XP and $500.": "任务“访问枪支商店”完成！获得200经验值和$500.",
    "Visit Level Rewards!": "访问等级奖励！",
    "Buy a Chicken Shed": "买一个鸡棚",
    "Go to Downtown, visit the Livestock Market, and purchase a Chicken Shed. If you already own the maximum (2 or 3 based on level), this quest will complete.": "去市中心，参观牲畜市场，买一个鸡舍。如果你已经拥有了最大值（2或3基于等级），这个任务将完成。",
    "Quest 'Visit Level Rewards!' completed! Gained 500 XP and $1000.": "任务“访问级别奖励！”“完成!获得500经验值和$1000",
    "Visit the Livestock Market and purchase a Chicken Shed to start raising chickens, or visit the market if you already own the maximum.": "参观牲畜市场，购买一个鸡棚开始养鸡，或者如果你已经拥有了最大的鸡棚，也可以参观市场。",
    "Finishing Introduction": "完成的介绍",
    "Quest 'Buy a Chicken Shed' completed! Gained 500 XP and $200.": "任务“买鸡舍”完成！获得500经验值和$200。",
    "Seeds!": "种子!",
    "Visit the Gym in Downtown and train one stat to complete your introduction.": "参观市中心的健身房，训练一个属性来完成你的介绍。",
    "Visit the Gym in Downtown and train one stat to completion.": "去市中心的健身房，完成一次训练。",
    "Master Farmer": "农场主",
    "Plant 50 crops total at once on your farm to prove your farming mastery.": "一次在你的农场种植50种作物，以证明你的农业技能。",
    "Plant a total of 50 crops on your farm. Might need to buy more fields!": "在你的农场种植50种农作物。可能需要买更多的田地！",
    "Quest 'Finishing Introduction' completed! Gained 500 XP and $10000.": "任务“完成介绍”完成！获得500经验值和$10000.",
    "Claimed": "已领取",
    "Level 5 Reward claimed! Gained: Annie Oakley Heritage Rough Rider 22LR": "获得5级奖励！获得：安妮·奥克利遗产粗骑22LR",
    "You already own a Farm Fridge!": "你已经拥有一台农场冰箱了！",
    "Auto Harvest": "自动收割",
    "Create Crew": "创建兵团",
    "Create Your Crew": "创建你的兵团",
    "Create Your Farm Crew": "创建你的农场兵团",
    "Create a Farm Crew": "创建一个农场兵团",
    "Crew Bio (up to 200 characters)": "兵团简介 (最多 200 字符)",
    "Crew Name (3–50 characters)": "兵团名称 (3–50 字符)",
    "Farm Crew Barn": "农场兵团谷仓",
    "Join a Farm Crew": "加入一个农场兵团",
    "Apply to Join": "申请加入",
    "Start a new crew for 5,000 coins.": "花费5000金钱创建一个新兵团。",
    "No bio yet.": "暂无简介。",
    "Hired Skilled Worker for $250! Can harvest 25 times, every 4 seconds.": "雇佣技术工人花费了$250！可以收获25次，每隔4秒。",
    "A basic small barn for storage": "一个基本的用于储存的小谷仓",
    "Available Barns": "可用谷仓",
    "Available Houses": "可用房屋",
    "Colonial House": "殖民地住宅",
    "Grandpas Barn": "爷爷的谷仓",
    "Hidden Treasure!": "隐藏的宝藏！",
    "Industrial Barn": "工业仓",
    "Industrial-grade storage facility": "工业级储存设施",
    "Large Barn": "大谷仓",
    "Massive large barn for serious farmers": "巨大的大型谷仓，适合认真的农民",
    "Medium Barn": "中型谷仓",
    "Modern Mansion": "现代豪宅",
    "Premium deluxe barn with premium features": "高级豪华谷仓，拥有高级功能",
    "Ranch Home": "牧场之家",
    "Sell Your Barn": "卖掉你的谷仓",
    "Sell Your Home": "卖掉你的房子",
    "Small Barn": "小谷仓",
    "Spacious medium barn": "宽敞的中型谷仓",
    "Sweet!": "太好了！",
    "The previous owner left behind some high dollar Unlimited Energy Pills!": "前主人留下了一些高价的无限能量药丸！",
    "Victorian Manor": "维多利亚庄园",
    "You currently live in the trailer (default home). Buy a new home above!": "你目前住在拖车里（默认的家）。在上面买一个新家！",
    "You don't currently own a barn. Buy one above to get started!": "你现在没有谷仓。在上面买一个开始吧！",
    "Sell Barn": "出售谷仓",
    "Donate": "捐赠",
    "Farm Fields Owned:": "拥有农场地块:",
    "No items match your filters.": "未查询到符合您过滤器条件的物品",
    "Reset Icons": "重置图标",
    "New File": "新文件",
    "My Files": "我的文件",
    "Desktop": "桌面",
    "Documents": "文档",
    "Dark": "深色",
    "Light": "浅色",
    "Background Image:": "背景图片:",
    "Color Scheme:": "配色方案:",
    "Stock Market": "股市",
    "Save Settings": "保存设置",
    "Submit Bug Report": "提交Bug报告",
    "Submit Suggestion": "提交建议",
    "Suggestion": "建议",
    "Suggestion Box": "建议箱",
    "Power": "关机",
    "Equip": "装备",
    "Mod": "改装",
    "Confirm": "确认",
    "No Attachments": "暂无附件",
    "Reload": "装弹",
    "Unequip": "卸下",
    "Energy is already full!": "能量已满!",
    "Attack Wins": "攻击获胜",
    "Hall of Fame - Farm Simulation Tycoon": "名人堂 - 农场模拟大亨",
    "Mug Wins": "马克杯获胜",
    "Rank": "排名",
    "Pool Wins": "奖池获胜",
    "Top 10 players ranked by various stats": "根据各种数据排名前10名的玩家",
    "Top Attack Wins": "最佳攻击获胜",
    "Top Player Levels": "最高玩家等级",
    "Top Pool Game Losses": "最多奖池游戏失败",
    "Top Pool Game Wins": "最多奖池游戏胜利",
    "Wins": "获胜",
    "XP Level": "经验等级",
    "Total Score": "总分",
    "Overall Stats (Strength + Agility + Defense)": "整体属性（力量+敏捷+防御）",
    "Losses": "失败",
    "Pool Losses": "奖池失败",
    "Top Coin Flip Losses": "最多抛硬币失败",
    "Top Coin Flip Wins": "最多抛硬币胜利",
    "Top Mug Wins": "最多马克杯胜利",
    "Current Inmates": "在押囚犯",
    "Hey there, visitor. What do you want to talk about?": "你好，访客。你想聊些什么？",
    "Jail Visit": "监狱参观",
    "No one’s in jail right now.": "现在没有人在监狱里。",
    "Welcome to the jail. Speak with Officer Mark, the cop on duty.": "欢迎来到监狱。跟执勤的马克警官谈谈。",
    "You’ve got questions, I’ve got answers. Give me more to work with—what’s the deal?": "你有问题，我有答案。给我更多的资料-怎么了？",
    "🏙️ Downtown": "🏙️ 市中心",
    "🏡 Home": "🏡 回家",
    "California": "加州",
    "Explore New Horizons": "探索新领域",
    "Florida": "佛罗里达",
    "Fly Home": "飞回家",
    "Golden beaches, vast farms, and bustling cities await!": "金色的海滩，广阔的农场和繁华的城市等待着你！",
    "New York": "纽约",
    "Ranches, oil fields, and wide-open plains!": "牧场、油田和开阔的平原！",
    "Return to your cozy farm for free!": "免费返回您舒适的农场！",
    "Sunny swamps, citrus groves, and coastal escapes! ($1000)": "阳光明媚的沼泽，柑橘林，和海岸逃生！（$1000）",
    "Texas": "德州",
    "Travel Now": "立即旅行",
    "Urban jungles and upstate farmland adventures!": "城市丛林和北部农田冒险！",
    "Show Chat": "显示聊天",
    "Waiting for Opponent...": "等待对手...",
    "Confirm Wager AI": "确认和AIPK",
    "Confirm Wager PVP": "确认PVPPK",
    "Go Downtown": "前往市中心",
    "Hitting Power": "击球力度",
    "Invite a Player:": "邀请玩家:",
    "Invite Player (PVP)": "邀请玩家 (PVP)",
    "Join Voice": "加入语音",
    "Leave Voice": "离开语音",
    "Live Chat": "实时聊天",
    "Mute Mic": "静音麦克风",
    "Pending Games": "等待游戏",
    "No pending games available.": "暂无等待中的游戏可用。",
    "Play vs AI": "对抗 vs AI",
    "Power:": "力度:",
    "Select a Game": "选择一个游戏",
    "Select a player...": "选择一个玩家...",
    "Your Turn": "你的回合",
    "Your Turn - Place Cue Ball": "你的回合 - 放置主球",
    "Opponent's Turn": "对手回合",
    "Race Chat": "比赛聊天",
    "Place Bet starts the race!": "下注开始比赛！",
    "Tractor Pull Betting": "牵引车拉力竞猜",
    "Race started!": "比赛开始了！",
    "Placing bet...": "正在投注...",
    "Race starting soon!": "比赛即将开始!",
    "Full recovery:": "完全恢复:",
    "Health:": "生命值:",
    "No patients currently admitted.": "目前无患者入院。",
    "| Wallet:": "| 钱包:",
    "Patients": "患者",
    "Restore Health & Energy": "恢复 生命值 & 能量",
    "Bank Balance:": "银行存款余额:",
    "Bank Gold:": "银行黄金:",
    "Bank Services": "银行服务",
    "Cash on Hand:": "手头现金：",
    "Deposit All": "全部存入",
    "Deposit Cash": "存入现金",
    "Deposit Gold": "存入黄金",
    "Enter Amount": "输入数量",
    "Gold on Hand:": "手头黄金：",
    "Interest Rate (Cash):": "利率（现金）：",
    "Next Interest in:": "下一次发放利息：",
    "Return to Downtown": "返回市区",
    "Withdraw Cash": "提取现金",
    "Withdraw Gold": "提取黄金",
    "Select a Player": "选择一个玩家",
    "Send Items to Players": "发送物品给其他玩家",
    "Send this item to another player": "将此物品发送给另一位玩家",
    "Please select a player to send the item to!": "请先选择一个玩家才能发给他物品。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "M16": "M16",
    "AK-47 Extended Mag": "AK-47扩展弹匣",
    "AK-47 Grip": "AK-47握把",
    "AK-47 Scope": "AK-47瞄准镜",
    "AK-47": "AK-47",
    ".50 AE": ".50 AE",
    ".357 Magnum": ".357马格南",
    ".22LR": ".22口径",
    "7.62 FMJ": "7.62 FMJ",
    "Ammo": "弹药",
    "PIC": "PIC",
    "Gityx": "Gityx",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "×": "×",
    "😊": "😊",
    "!": "!",
    "⚡": "⚡",
    "✉️": "✉️",
    "❤️": "❤️",
    "⭐": "⭐",
    "🌾": "🌾",
    "🏡": "🏡",
    "👤": "👤",
    "💰": "💰",
    "🔔": "🔔",
    "🛒": "🛒",
    "🎁": "🎁",
    "🎯": "🎯",
    "$": "$",
    "✏️": "✏️",
    "✓": "✓",
    "📩": "📩",
    "🔊": "🔊",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    ">>": ">>",
    ">": ">",
    "<<": "<<",
    "<": "<",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Total Stats: ": "总属性: ",
    "Strongest Farmers (Top ": "最强农夫 (前 ",
    "Most Hated Farmer: ": "最令人讨厌的农夫: ",
    "Most Liked Farmer: ": "最受人喜爱的农夫: ",
    "Day of the Season: ": "季节天数: ",
    "Online Players ": "在线玩家 ",
    "Worker Uses: ": "使用中的工人: ",
    "Guest_": "游客_",
    "Barn: ": "谷仓: ",
    "Armor: ": "盔甲: ",
    "Pants: ": "裤子: ",
    "Sidearm: ": "配枪: ",
    "Weapon: ": "武器: ",
    "Shoes: ": "鞋子: ",
    "Shirt: ": "衬衫: ",
    "Harvested Hay to Barn - ": "已收割 干草 到谷仓 - ",
    "Harvested Carrots to Barn - ": "已收割 胡萝卜 到谷仓 - ",
    "Harvested Corn to Barn - ": "已收割 玉米 到谷仓 - ",
    "Harvested Tomatoes to Barn - ": "已收割 西红柿 到谷仓 - ",
    "Harvested Wheat to Barn - ": "已收割 小麦 到谷仓 - ",
    "Harvested Potatoes to Barn - ": "已收割 土豆 到谷仓 - ",
    "Harvested Wheat to Barn and ": "已收割 小麦 到谷仓 - ",
    "Straw: ": "稻草: ",
    "Progress: ": "进度: ",
    "Dog Food: ": "狗粮: ",
    "Small Dog House x": "小型狗屋 x",
    "Claimable (Lvl ": "可领取 (等级 ",
    "Pending: ": "等待中: ",
    "Rewarded: ": "已获得奖励: ",
    "Total Referrals: ": "累计推荐: ",
    "Not enough energy (Need ": "没有足够的能量 (需要 ",
    "Uses Left: ": "剩余使用次数: ",
    "Energy: ": "能量: ",
    "Coins: ": "金钱: ",
    "Strength +1! Energy: ": "力量 +1! 能量: ",
    "Agility +1! Energy: ": "敏捷 +1! 能量: ",
    "Defense +1! Energy: ": "防御 +1! 能量: ",
    "You will bet: ": "你可以PK: ",
    "Coin Flip ": "抛硬币 ",
    "Item Flip ": "抛物品 ",
    "Current Bet: ": "当前下注: ",
    "Dealer's Hand (Value: ": "庄家手牌 (价值: ",
    "Your Hand (Value: ": "你的手牌 (价值: ",
    "Bust! You lose ": "完蛋! 你输了 ",
    "Your Chips: ": "你的筹码: ",
    "You win! Payout: ": "你赢了！获得：",
    "Placed Item Flip bet: ": "放置物品下注: ",
    "You won the Coin Flip! Gained ": "你在抛硬币中获胜! 获得了 ",
    "You lost the Coin Flip! Lost ": "你在抛硬币中获胜! 失去了 ",
    "! Gained ": "! 获得了 ",
    "won a Coin Flip against you! Lost ": "跟你掷硬币赢了！你失去了",
    "Goat Shelter x": "山羊圈 x",
    "Not enough money (Need ": "金钱不足 (需要 ",
    "Qty: ": "数量: ",
    "Seller: ": "卖家: ",
    "Total: $": "总计: $",
    "House Health: ": "房屋生命值: ",
    "House: ": "房屋: ",
    "Sleep Timer: ": "睡觉计时器: ",
    "Inside ": "正在 ",
    "Waking up in ": "将睡醒于 ",
    "Season: ": "季节: ",
    "Cattle Pen x": "牛栏 x",
    "Chicken Shed x": "鸡棚 x",
    "Ammo: ": "弹药: ",
    "Fits: ": "适合: ",
    "Used by: ": "用于: ",
    "Your Money: $": "你的金钱: $",
    "Fine to Pay: $": "罚款: $",
    "Escape Chance: ": "逃跑成功率: ",
    "Sell for ": "出售获得 ",
    "Not enough energy! Need at least ": "没有足够的能量! 需要至少 ",
    "Instantly harvests all ready crops (": "立即收获所有成熟的作物 (",
    "Text Editor": "文本编辑器",
    "Bug Report": "Bug报告",
    "File Explorer": "文件管理器",
    "Settings": "设置",
    "Voice: ": "语音: ",
    "Wager": "赌注",
    "AI Wager": "AI赌注",
    "Cash: ": "现金: ",
    "Help Line: ": "辅助线: ",
    "You are solids": "你进洞了",
    "Money: ": "金钱: ",
    "Bet Amount": "投注金额",
    "Race starts in ": "距离比赛开始还有",
    "Push! Bet returned: $": "平手! 投注返还：$",
    "You are stripes": "你连杆了",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " farmers online in the last 24 hours!": "农夫于最近24小时内在线！",
    " Enemies)": " 敌人)",
    " Friends)": " 朋友)",
    ", no straw remaining": ", 没有稻草剩余",
    ", no feed remaining": ", 没有饲料剩余",
    ", expires in ~36 minutes": ", 距离过期 ~36 分钟",
    " Uses)": " 使用次数)",
    "s until next harvest": "秒 直到下一次收割",
    "x Annie Oakley Heritage Rough Rider 22LR": "x 安妮奥克利传统粗糙骑手22LR",
    "x Tactical Helmet": "x 战术头盔",
    "x Wool": "x 羊毛",
    "x Goat Milk": "x 羊奶",
    " Item Bet vs. Players)": " 物品投注 vs. 玩家)",
    " Bet vs. Players)": " 投注 vs. 玩家)",
    " x Carrots.": " x 胡萝卜.",
    " Light Armor Rounds": " 轻型装甲弹",
    "'s Home": " 的家",
    " per 10": " 每 10",
    " uses left)": " 次数剩余)",
    " - FarmOS": " - FarmOS",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\(([\d\.]+):([\d\.]+):([\d\.]+)\)$/,
    /^\(([\d\.]+):([\d\.]+):([\d\.]+)\)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Interest of (.+) credited to your bank for (.+) day\(s\)$/, '你的存款在 $2 天内产生了 $1 利息，已存入您的银行'],
    [/^(.+) wins! You lose (.+).$/, '$1 获胜! 你输掉了 $2.'],
    [/^You won (.+) betting on Green Giant!$/, '你赢得了 $1 通过下注在 绿巨人 身上!'],
    [/^You won (.+) betting on Yellow Yielder!$/, '你赢得了 $1 通过下注在 黄色屈服者 身上!'],
    [/^You won (.+) betting on Blue Beast!$/, '你赢得了 $1 通过下注在 蓝色野兽 身上!'],
    [/^You won (.+) betting on Red Rocket!$/, '你赢得了 $1 通过下注在 红色火箭 身上!'],
    [/^You lost (.+). Yellow Yielder won!$/, '你输掉了 $1. 黄色屈服者获胜!'],
    [/^You lost (.+). Green Giant won!$/, '你输掉了 $1. 绿巨人获胜!'],
    [/^You lost (.+). Blue Beast won!$/, '你输掉了 $1. 蓝色野兽获胜!'],
    [/^You lost (.+). Red Rocket won!$/, '你输掉了 $1. 红色火箭获胜!'],
    [/^Repair House \((.+), (.+) Energy\)$/, '修理房屋 ($1, $2 能量)'],
    [/^Listed (.+) Carrots for (.+)!$/, '上架了 $1 或萝卜以 $2 的单价!'],
    [/^Available Listings \((.+) total\)$/, '可用挂单 (总计 $1)'],
    [/^Collected (.+) Beef! \((.+) Energy\)$/, '已收集 $1 牛肉! ($2 能量)'],
    [/^Collected (.+) Eggs! \((.+) Energy\)$/, '已收集 $1 鸡蛋! ($2 能量)'],
    [/^Collected (.+) Goat Milk! \((.+) Energy\)$/, '已收集 $1 羊奶! ($2 能量)'],
    [/^Purchased (.+) lighter\(s\) for (.+)! Each has 10 uses.$/, '购买了 $1 打火机 花费了 $2! 每个可以用10次.'],
    [/^Purchased (.+) Farm\(s\) for (.+)! Farm level increased to (.+). Now you can grow up to (.+) crops.$/, '购买了 $1 农场 花费了 $2! 农场等级提升到了 $3. 现在你最多可以种植 $4 作物.'],
    [/^Purchased (.+) Chicken Shed\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 鸡棚 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) .22LR\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 .22口径弹药 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) Combat Shirt\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 战术衬衫 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) Combat Boots\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 战术靴 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) Kevlar Vest\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 凯夫拉背心 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) Tactical Helmet\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 战术头盔 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) Cargo Pants\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 工装裤 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) Goat Shelter\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 山羊圈 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) Cattle Pen\(s\) for (.+)! Added to your Animal Pasture.$/, '购买了 $1 牛栏 花费了 $2! 已添加到你的动物牧场。'],
    [/^Purchased (.+) Beef Cattle\(s\) for (.+)! Added to your barn.$/, '购买了 $1 肉牛 花费了 $2! 已添加到你的谷仓。'],
    [/^Purchased (.+) Goat\(s\) for (.+)! Added to your barn.$/, '购买了 $1 山羊 花费了 $2! 已添加到你的谷仓。'],
    [/^Purchased (.+) Chicken\(s\) for (.+)! Added to your barn.$/, '购买了 $1 鸡 花费了 $2! 已添加到你的谷仓。'],
    [/^Purchased Auto-Harvest Tractor for (.+)! You can now use auto-harvest.$/, '购买了自动采集拖拉机花费了 $1！你现在可以使用自动收割了。'],
    [/^Purchased Small Barn for (.+)! Storage: (.+) items$/, '购买了 小型谷仓 花费了 $1! 存储: $2 物品'],
    [/^Min: 10, Max: 10,000,000. You can place up to (.+) more bets.$/, '最小：10，最大：10,000,000。你最多可以下注 $1 次。'],
    [/^Bet of (.+) placed in Coin Flip queue.$/, '在掷硬币队列中下注了 $1。'],
    [/^Deposited (.+) from cash to chips!$/, '你把 $1 现金换成了筹码！'],
    [/^Welcome to the Games, farmer! Your Chips: (.+) \| Farm Cash: (.+)$/, '欢迎来到游戏, 农夫! 你的筹码: $1 | 农场现金: $2'],
    [/^Workers instantly harvested (.+) crop\(s\) to Barn! \+(.+) XP$/, '工人立即收获 $1 作物到谷仓！+$1 经验值'],
    [/^Instantly harvests all ready crops \((.+) uses left\)$/, '立即收获所有成熟的作物（剩余$1次）'],
    [/^Cannot sell (.+) Tomatoes \- only (.+) available!$/, '不能出售 $1 西红柿 - 仅 $2 可用!'],
    [/^Active (.+) minutes ago$/, '活动于 $1 分钟前'],
    [/^Added (.+) Chicken to Chicken Shed! Shed is now full.$/, '添加了 $1 鸡 到 鸡棚！鸡棚现在已满。'],
    [/^Added (.+) Beef Cattle to Cattle Pen!$/, '添加了 $1 肉牛 到 牛栏！'],
    [/^Added (.+) Dog Food to Small Dog House! Feed now at (.+), lasts \~(.+) minutes.$/, '添加了 $1 狗粮 到 小型狗屋！现在喂养 $2，持续约 $3 分钟。'],
    [/^Added (.+) Straw to Small Dog House! Feed now at (.+), lasts \~(.+) minutes.$/, '添加了 $1 稻草 到 小型狗屋！现在喂养 $2，持续约 $3 分钟。'],
    [/^Added (.+) Wheat to Chicken Shed! Feed now at (.+), lasts \~(.+) hours.$/, '添加了 $1 小麦 到 鸡棚！现在喂养 $2，持续约 $3 小时。'],
    [/^Added (.+) Hay to Goat Shelter! Feed now at (.+), lasts \~(.+) hours.$/, '添加了 $1 干草 到 山羊圈！现在喂养 $2，持续约 $3 小时。'],
    [/^Added (.+) Hay to Cattle Pen! Feed now at (.+), lasts \~(.+) hours.$/, '添加了 $1 干草 到 牛栏! 现在喂养 $2，持续约 $3 小时。'],
    [/^Added (.+) Straw to Goat Shelter! Straw now at (.+), lasts \~(.+) hours.$/, '添加了 $1 稻草 到 山羊圈！稻草现在 $2，持续约 $3 小时。'],
    [/^Added (.+) Straw to Cattle Pen! Straw now at (.+), lasts \~(.+) hours.$/, '添加了 $1 稻草 到 牛栏！稻草现在 $2，持续约 $3 小时。'],
    [/^Cost: (.+) \/ (.+) Energy \/ (.+) XP$/, '成本: $1 / $2 能量 / $3 经验值'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Energy Drinks$/, '$1 能量饮料'],
    [/^([\d\.,]+) Health Packs$/, '$1 医疗包'],
    [/^([\d\.,]+) gold$/, '$1 黄金'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) Gold$/, '$1 黄金'],
    [/^([\d\.,]+)h ago$/, '$1 小时前'],
    [/^([\d\.,]+)d ago$/, '$1 天前'],
    [/^([\d\.,]+) seconds ago$/, '$1 秒前'],
    [/^([\d\.,]+) x Carrots and kept ([\d\.,]+) x Carrots!$/, '$1 x 胡萝卜，保留 $2 x胡萝卜!'],
    [/^\+([\d\.,]+) XP$/, '+$1 经验值'],
    [/^\+([\d\.,]+) XP \- Level ([\d\.,]+) achieved!$/, '+$1 经验值 - 达到等级 $2!'],
    [/^([\d\.,]+) Straw \- \+([\d\.,]+) XP$/, '$1 稻草 - +$2 经验值'],
    [/^([\d\.,]+) Straw \- \+([\d\.,]+) XP \- Level ([\d\.,]+) achieved!$/, '$1 稻草 - +$2 经验值 - 达到等级 $3!'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\-([\d\.,]+) elves$/, '-$1 精灵'],
    [/^Lvl ([\d\.,]+): ([\d\.,]+)\/([\d\.,]+)$/, '等级 $1:$2/$3'],
    [/^Growing: (.+) \| Energy: ([\d\.,]+) \| Health: ([\d\.,]+) \|$/, '生长: $1 | 能量: $2 | 生命值: $3 |'],
    [/^Wheat planted! Cost: (.+), Energy: (.+), (.+) XP$/, '小麦已种植! 成本: $1, 能量: $2, $3 经验值'],
    [/^Corn planted! Cost: (.+), Energy: (.+), (.+) XP$/, '玉米已种植! 成本: $1, 能量: $2, $3 经验值'],
    [/^Hay planted! Cost: (.+), Energy: (.+), (.+) XP$/, '干草已种植! 成本: $1, 能量: $2, $3 经验值'],
    [/^Carrots planted! Cost: (.+), Energy: (.+), (.+) XP$/, '胡萝卜已种植! 成本: $1, 能量: $2, $3 经验值'],
    [/^Potatoes planted! Cost: (.+), Energy: (.+), (.+) XP$/, '土豆已种植! 成本: $1, 能量: $2, $3 经验值'],
    [/^Tomatoes planted! Cost: (.+), Energy: (.+), (.+) XP$/, '西红柿已种植! 成本: $1, 能量: $2, $3 经验值'],
    [/^Tomatoes planted! Cost: (.+), Energy: (.+), (.+) XP \- Level (.+) achieved!$/, '西红柿已种植! 成本: $1, 能量: $2, $3 经验值 - 达到等级 $4!'],
    [/^Potatoes planted! Cost: (.+), Energy: (.+), (.+) XP \- Level (.+) achieved!$/, '土豆已种植! 成本: $1, 能量: $2, $3 经验值 - 达到等级 $4!'],
    [/^Hay planted! Cost: (.+), Energy: (.+), (.+) XP \- Level (.+) achieved!$/, '干草已种植! 成本: $1, 能量: $2, $3 经验值 - 达到等级 $4!'],
    [/^Corn planted! Cost: (.+), Energy: (.+), (.+) XP \- Level (.+) achieved!$/, '玉米已种植! 成本: $1, 能量: $2, $3 经验值 - 达到等级 $4!'],
    [/^Wheat planted! Cost: (.+), Energy: (.+), (.+) XP \- Level (.+) achieved!$/, '小麦已种植! 成本: $1, 能量: $2, $3 经验值 - 达到等级 $4!'],
    [/^Level ([\d\.,]+) 🌾$/, '等级 $1 🌾'],
    [/^Storage: ([\d\.,]+) items$/, '存储: $1 物品'],
    [/^Need ([\d\.,]+) energy to harvest!$/, '需要 $1 能量才能收割！'],
    [/^Level ([\d\.,]+) Reward$/, '等级 $1 奖励'],
    [/^Level ([\d\.,]+) Required$/, '要求等级 $1'],
    [/^Requires level ([\d\.,]+)$/, '要求等级 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Level: ([\d\.,]+) \| Crew XP: ([\d\.,]+)$/, '等级: $1 | 兵团经验值: $2'],
    [/^Your Coins: \$([\d\.,]+) \| Cost: ([\d\.,]+) Coins$/, '你的金钱: $ $1 | 成本: $2 金钱'],
    [/^Auto-harvested ([\d\.,]+) crops to Barn!$/, '自动收割了 $1 作物到谷仓!'],
    [/^Active ([\d\.,]+) minute ago$/, '活动于 $1 分钟前'],
    [/^Annie Oakley Heritage Rough Rider 22LR \(x([\d\.,]+)\)$/, '安妮·奥克利传统粗糙骑手22LR (x$1)'],
    [/^Beef \(x([\d\.,]+)\)$/, '牛肉 (x$1)'],
    [/^Energy Drink \(x([\d\.,]+)\)$/, '能量饮料 (x$1)'],
    [/^Health Pack \(x([\d\.,]+)\)$/, '医疗包 (x$1)'],
    [/^lighter \(x([\d\.,]+)\)$/, '打火机 (x$1)'],
    [/^Small Dog House \(x([\d\.,]+)\)$/, '小型狗屋 (x$1)'],
    [/^Manure \(x([\d\.,]+)\)$/, '粪肥 (x$1)'],
    [/^Eggs \(x([\d\.,]+)\)$/, '鸡蛋 (x$1)'],
    [/^Wheat \(x([\d\.,]+)\)$/, '小麦 (x$1)'],
    [/^Hay \(x([\d\.,]+)\)$/, '干草 (x$1)'],
    [/^Goat Milk \(x([\d\.,]+)\)$/, '羊奶 (x$1)'],
    [/^Straw \(x([\d\.,]+)\)$/, '稻草 (x$1)'],
    [/^Tomatoes \(x([\d\.,]+)\)$/, '西红柿 (x$1)'],
    [/^Corn \(x([\d\.,]+)\)$/, '玉米 (x$1)'],
    [/^Potatoes \(x([\d\.,]+)\)$/, '土豆 (x$1)'],
    [/^Carrots \(x([\d\.,]+)\)$/, '胡萝卜 (x$1)'],
    [/^Yellow Yielder \(([\d\.,]+)x\)$/, '黄色屈服者 ($1x)'],
    [/^Blue Beast \(([\d\.,]+)x\)$/, '蓝色野兽 ($1x)'],
    [/^Green Giant \(([\d\.,]+)x\)$/, '绿巨人 ($1x)'],
    [/^Red Rocket \(([\d\.,]+)x\)$/, '红色火箭 ($1x)'],
    [/^Carrots \(([\d\.,]+) available\)$/, '胡萝卜 ($1 可用)'],
    [/^Hay \(([\d\.,]+) available\)$/, '干草 ($1 可用)'],
    [/^Corn \(([\d\.,]+) available\)$/, '玉米 ($1 可用)'],
    [/^Straw \(([\d\.,]+) available\)$/, '稻草 ($1 可用)'],
    [/^Small Dog House \(([\d\.,]+) available\)$/, '小型狗屋 ($1 可用)'],
    [/^Health Pack \(([\d\.,]+) available\)$/, '医疗包 ($1 可用)'],
    [/^Energy Drink \(([\d\.,]+) available\)$/, '能量饮料 ($1 可用)'],
    [/^❌ Need ([\d\.,]+)\+ dogs with ([\d\.,]+)\+ training$/, '❌ 需要 $1+ 狗和 $2+ 训练'],
    [/^Sold ([\d\.,]+) Goat Milk for \$([\d\.,]+)!$/, '出售 $1 羊奶 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Wheat for \$([\d\.,]+)!$/, '出售 $1 小麦 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Manure for \$([\d\.,]+)!$/, '出售 $1 粪肥 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Eggs for \$([\d\.,]+)!$/, '出售 $1 鸡蛋 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Straw for \$([\d\.,]+)!$/, '出售 $1 稻草 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Potatoes for \$([\d\.,]+)!$/, '出售 $1 土豆 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Tomatoes for \$([\d\.,]+)!$/, '出售 $1 西红柿 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Carrots for \$([\d\.,]+)!$/, '出售 $1 胡萝卜 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Hay for \$([\d\.,]+)!$/, '出售 $1 干草 获得了 $ $2!'],
    [/^Sold ([\d\.,]+) Corn for \$([\d\.,]+)!$/, '出售 $1 玉米 获得了 $ $2!'],
    [/^Rewards: ([\d\.,]+) XP, \$([\d\.,]+)$/, '奖励: $1 经验值, $ $2'],
    [/^Rewards:\n(.+)Annie Oakley Heritage Rough Rider 22LR$/, '奖励:\n$1安妮·奥克利传承粗骑22LR'],
    [/^Rewards:\n(.+)\$(.+), (.+) Hay$/, '奖励:\n$1 \$ $2, $3 干草'],
    [/^Rewards:\n(.+)\$(.+), (.+) XP$/, '奖励:\n$1 \$ $2, $3 经验值'],
    [/^Rewards:\n(.+)\$(.+), (.+) Gold$/, '奖励:\n$1 \$ $2, $3 黄金'],
    [/^Rewards:\n(.+)\$(.+), (.+) XP, (.+) Strength, (.+) Agility, (.+) Defense$/, '奖励:\n$1 \$ $2, $3 经验值, $4 力量, $5 敏捷, $6 防御'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+)\n(.+), expires in (.+) minutes$/, '$1\n$2, 距离过期 $3 分钟'],
    [/^Wheat: (.+)\n(.+), expires in (.+) hours$/, '小麦: $1\n$2, 距离过期 $3 小时'],
    [/^Hay: (.+)\n(.+), expires in (.+) hours$/, '干草: $1\n$2, 距离过期 $3 小时'],
    [/^(.+)\n(.+), expires in (.+) hours$/, '$1\n$2, 距离过期 $3 小时'],
    [/^Capacity: (.+) dogs$/, '容量: $1 狗'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Price: (.+) each$/, '价格：$1 每个'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Animals: (.+)\/(.+) Goat$/, '动物：$1\/$2 山羊'],
    [/^Animals: (.+)\/(.+) Beef Cattle$/, '动物：$1\/$2 肉牛'],
    [/^Animals: (.+)\/(.+) Chicken$/, '动物：$1\/$2 鸡'],
    [/^Wheat: (.+)\/(.+)\n(.+)$/, '小麦：$1\/$2\n$3'],
    [/^Hay: (.+)\/(.+)\n(.+)$/, '干草：$1\/$2\n$3'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();