// ==UserScript==
// @name         Idle Crusade 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.1
// @description  网页游戏 Idle Crusade (https://idlecrusade.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Idle Crusade.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://idlecrusade.com/images/Idle%20Crusade.png
// @license      MIT
// @include      *https://idlecrusade.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/idle-crusade-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/idle-crusade-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/11/07 22:22
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "⚔️ Combat": "⚔️ 战斗",
    "Location": "位置",
    "🔨 Active Skills": "🔨 活跃技能",
    "Contact": "联系",
    "Compete": "竞技",
    "Auto-Save": "自动保存",
    "Compete with players worldwide": "与全球玩家同场竞技",
    "HP:": "生命值:",
    "Log In": "登录",
    "Play Now": "开始游戏",
    "Unknown": "未知",
    "Version:": "版本:",
    "Total Level:": "总等级:",
    "Train": "训练",
    "Train • Progress • Compete": "训练 • 进度 • 竞技",
    "📊 Quick Stats": "📊 快速统计",
    "An idle multiplayer game inspired by Old School RuneScape.\n                    Train your skills, level up, and compete with players around the world.\n                    Progress even when you're offline!": "一款受《Old School RuneScape》启发的放置多人游戏。训练你的技能，升级，并与世界各地的玩家竞争。即使离线也能进步！",
    "🎮 Current Activities": "🎮 当前活跃",
    "ACTIVITY": "活动",
    "Authentic XP System": "正宗的经验系统",
    "Create": "创建",
    "Game Features": "游戏功能",
    "Home": "首页",
    "How It Works": "它是如何工作的",
    "Idle Crusade": "十字军东征放置",
    "Idle Progression": "放置进度",
    "Keep training when you're away": "当你不在的时候继续训练",
    "Leaderboards": "排行榜",
    "Level up and climb the leaderboards": "提升等级，登上排行榜",
    "Lumford Fields": "拉姆福德原野",
    "No active skills": "无主动技能",
    "Not in combat": "不在战斗中",
    "Offline Progress": "离线进度",
    "OSRS-style experience and leveling": "osrs风格的经验和升级",
    "Players online:": "在线玩家：",
    "Privacy": "隐私",
    "Progress automatically while playing": "在游戏中自动前进",
    "See all features": "查看所有功能",
    "Select skills and start training automatically": "选择技能并自动开始训练",
    "Sign Up": "注册",
    "Sign up and choose your character": "注册并选择你的角色",
    "Terms": "条款",
    "Train all skills from Attack to Farming": "训练所有技能，从攻击到农场",
    "Your progress is always saved": "你的进度总是会被保存下来",
    "Show less": "收起",
    "← Back to Home": "← 返回首页",
    "Already have an account?": "已有账号？",
    "Choose Your Character Type": "选择你的角色类型",
    "Confirm Password": "确认密码",
    "Create your account to start playing": "创建您的帐户即刻开玩",
    "Email": "电子邮箱",
    "Forgot Password?": "忘记密码？",
    "Password": "密码",
    "Type A": "类型 A",
    "Type B": "类型 B",
    "Username": "用户名",
    "Map": "地图",
    "XP": "经验值",
    "Trade": "交易",
    "Logout": "登出",
    "Chat": "聊天",
    "Combat": "战斗",
    "📦 Inventory": "📦 库存",
    "General": "常规",
    "Inventory": "库存",
    "Inventory is empty": "库存是空的",
    "Level": "等级",
    "Loading messages...": "加载消息...",
    "Online": "在线",
    "Production": "生产",
    "Profile": "个人资料",
    "Recruitment": "招募",
    "Select a skill to train and view activities": "选择一个技能来训练和查看活动",
    "Send": "发送",
    "Skills": "技能",
    "DEV": "开发者",
    "No messages yet. Be the first to chat!": "还没有消息。做第一个聊天的人！",
    "Rank": "排名",
    "Player": "玩家",
    "Level:": "等级:",
    "Leaderboard": "排行榜",
    "Ashen Plains": "灰色平原",
    "Brinewater Coast": "盐水海岸",
    "Celestine Ruins": "塞莱斯廷废墟",
    "Celestine Ruins (Aether Rift)": "塞莱斯廷废墟(以太裂痕)",
    "Ebon Hollow": "乌木山谷",
    "Ebon Hollow (Deep Veins)": "乌木山谷（深脉）",
    "Eldertide Frontier": "埃尔德泰边境",
    "Frostveil Peaks": "霜面纱峰",
    "Ironvale Mines": "铁谷矿山",
    "Lumford Fields": "拉姆福德原野",
    "Mistwood Grove": "翠木林",
    "Oakridge Forest (Mine Site)": "橡树岭森林（矿场）",
    "Oakridge Forest / Ironvale Mines": "橡树岭森林/铁谷矿山",
    "Oakridge Forest": "橡树岭森林",
    "Shattered Realm": "破碎之境",
    "Stormport Depths": "风暴港深处",
    "Stormport Docks": "风暴港码头",
    "Activities": "活动",
    "Adamant Ore": "艾德曼矿石",
    "Aetherium Ore ✨": "以太矿石 ✨",
    "Astral Ore ⭐": "星体矿石 ⭐",
    "Coal": "煤",
    "Copper Ore": "铜矿石",
    "Currently Training": "正在训练中",
    "Dragonite Ore 🐉": "龙岩矿石 🐉",
    "Eldrite Ore 🌌": "电极石矿石 🌌",
    "Ethereal Ore 🌫️": "以太矿石 🌫️",
    "Gold Ore": "金矿石",
    "Iron Ore": "铁矿石",
    "Loading activities...": "正在加载活动...",
    "Mine Copper Ore": "开采铜矿石",
    "Mithril Ore": "秘银矿石",
    "No messages yet. Be the first to chat!": "还没有留言。做第一个聊天的人！",
    "Obsidium Ore 🌋": "黑曜石矿石 🌋",
    "Aetherium Ore": "以太矿石",
    "Astral Ore": "星体矿石",
    "Dragonite Ore": "龙石矿石",
    "Eldrite Ore": "电极石矿石",
    "Ethereal Ore": "空灵矿石",
    "Mithril Ore": "秘银矿石",
    "Obsidium Ore": "黑曜石矿石",
    "Runite Ore": "符文石矿石",
    "Soulsteel Ore": "灵魂钢矿石",
    "Tin Ore": "锡矿石",
    "Silver Ore": "银矿石",
    "Soulsteel Ore 💀": "灵魂钢矿石 💀",
    "Stats": "属性",
    "Stop Training": "停止训练",
    "To Next:": "到下一级:",
    "XP:": "经验值：",
    "Training": "训练中",
    "Sapwood Tree": "边材树",
    "Chicken": "鸡",
    "Rat": "老鼠",
    "Travel Here": "旅行到这里",
    "Traveling to:": "旅行到:",
    "My Location": "我的位置",
    "Tin": "锡",
    "Players in Area": "区域内玩家",
    "Area": "区域",
    "🔒 Locked": "🔒 未解锁",
    "👁️ View Area": "👁️ 查看区域",
    "Activity:": "活动:",
    "Available Areas": "可用区域",
    "🔒 Under Development": "🔒 开发中",
    "Coordinates": "坐标",
    "Click to view profile": "点击查看个人资料",
    "Current Location": "当前位置",
    "Players currently in your area": "当前在您所在区域的玩家",
    "Mud Slime": "泥浆史莱姆",
    "Infernal Depths": "地狱深处",
    "Goblin": "哥布林",
    "Continue Game": "继续游戏",
    "+XP": "+经验值",
    "HP Level -": "生命值等级 -",
    "Level -": "等级 -",
    "You": "你",
    "Strength": "力量",
    "Total This Fight": "本次战斗总计",
    "⚔️ Attack": "⚔️ 攻击",
    "⚔️ Combat Stance": "⚔️ 战斗姿态",
    "⚔️ Equipment": "⚔️ 装备",
    "✨ XP Gains": "✨ 获得经验",
    "✨ XP Per Kill": "✨ 每次击杀经验",
    "❤️ Hitpoints": "❤️ 生命值",
    "🍽️ Food": "🍽️ 食物",
    "📊 Combat Levels": "📊 战斗等级",
    "📜 Combat Log": "📜 战斗日志",
    "Accurate": "精准",
    "Aggressive": "挑衅",
    "Attack": "攻击",
    "Battle": "战斗",
    "Combat log will appear here...": "战斗记录会出现在这里…",
    "Controlled": "受控",
    "Defence": "防御",
    "Defense": "防御",
    "Defensive": "防守",
    "Hitpoints": "生命值",
    "No equipment": "暂无装备",
    "No food available": "没有食物",
    "Stop Combat Training": "停止战斗训练",
    "⚔️ In Combat - Return to Combat": "⚔️ 战斗中 - 返回战斗",
    "🏦 Bank": "🏦 银行",
    "🐴 Mount": "🐴 坐骑",
    "Bank": "银行",
    "Body": "身体",
    "Boots": "靴子",
    "Empty": "空",
    "Equipment": "装备",
    "Gloves": "手套",
    "Helm": "头盔",
    "Hood": "兜帽",
    "Inventory & Equipment": "库存&装备",
    "Legs": "腿",
    "Robe Bottom": "长袍下衣",
    "Shield": "盾牌",
    "Tool": "工具",
    "Weapon": "武器",
    " Resource": "资源",
    "Used to smelt Copper Bar.": "用于冶炼铜锭。",
    ": 25% each to Attack, Strength, Defense, HP": ": 25% 到攻击，力量，防御，生命值",
    "💎 Drops:": "💎 掉落:",
    "🐺 Monsters": "🐺 怪物",
    "👑 Boss Battles": "👑 Boss战",
    "⚔️ Combat Training": "⚔️ 战斗训练中",
    "⚔️ Solo Boss Battles:": "⚔️ 单人Boss战:",
    "Defense:": "防御:",
    "Warning:": "警告:",
    "Tip:": "提示:",
    "Attack:": "攻击:",
    "Boss Battles:": "Boss战:",
    "Combat Stance": "战斗姿态",
    "A corrupted boar from Lumford Forest. Uses": "一只来自拉姆福德森林的腐败野猪。使用",
    "Choose a location to fight monsters. Your XP gains are controlled by your": "选择一个地点与怪物战斗。你的XP收益由你控制",
    "during battle.": "在战斗中。",
    "Fight bosses alone! Test your skills and earn powerful loot.": "独自对抗boss ！测试你的技能，获得强大的战利品。",
    "Fight powerful bosses! You can fight solo, but bringing a party makes it easier and more rewarding. The boss attacks all party members, and everyone contributes damage.": "与强大的boss战斗！你可以单打独斗，但带一个团队会让战斗更容易，也更有回报。boss会攻击所有队友，每个人都会造成伤害。",
    "Location Selection": "位置选择",
    "Once in battle, select your combat stance to control XP distribution:": "一旦进入战斗，选择你的战斗姿态来控制XP分配：",
    "special attack every 10s (double damage + stun).": "每10秒发动一次特殊攻击（双倍伤害+晕眩）。",
    "Start Boss Battle": "开始Boss战",
    "Start Combat Training": "开始战斗训练",
    "The Corrupted Boar": "腐败的野猪",
    "Vine Charge": "魔藤蓄力",
    "You don't have any equipment. You can still fight, but you'll have reduced bonuses. Get equipment through smithing, monster drops, or buying from shops.": "你没有任何装备。你仍然可以战斗，但你的奖励会减少。通过锻造，怪物掉落或从商店购买获得装备。",
    " Ingredient": "食材",
    "✨ Unique ✨": "✨独特✨",
    "A pouch containing 50-80 gold coins from defeated enemies.": "一个装有50-80金币的袋子，来自被击败的敌人。",
    "A rare charm imbued with the essence of the corrupted boar.": "一种罕见的符咒，充满了腐化野猪的精髓。",
    "A shard of corrupted vine energy. Used for enchanting and potion crafting.": "腐化的藤蔓能量碎片。用于附魔和制作药剂。",
    "A small blade carved from boar tusks.": "用野猪牙雕刻的小刀片。",
    "Accessory": "配饰",
    "Armor (Body)": "盔甲（身体）",
    "Boarhide Armor": "兽皮盔甲",
    "Boarhide Charm": "野猪魔咒",
    "Cooks into:": "烹饪成：",
    "Corrupted Vine Shard": "腐烂的藤蔓碎片",
    "Crafting Material": "制作材料",
    "Currency": "货币",
    "Early chest armor crafted from boar hide.": "早期用野猪皮制作的胸甲。",
    "Hearty Boar Steak (+40 HP, +5% Strength for 1m)": "丰盛的野猪牛排（+40 生命值，+5% 力量，持续 1 分钟）",
    "Hitpoints:": "点数:",
    "Lumford Coin Pouch": "拉姆福德钱袋",
    "Raw meat from a wild boar. Can be cooked into Hearty Boar Steak.": "野猪的生肉。可以煮成丰盛的野猪牛排。",
    "Strength:": "力量:",
    "Tusken Dagger": "獠牙匕首",
    "Wild Boar Meat": "野猪肉",
    "Silver": "银",
    "Adamant": "艾德曼",
    "All Bars": "所有金属锭",
    "Copper": "铜",
    "Gold": "金",
    "Iron": "铁",
    "Steel": "钢",
    "Aetherium": "以太",
    "Aetherium Bar ✨": "以太锭 ✨",
    "Astral": "星体",
    "Astral Bar ⭐": "星体锭 ⭐",
    "Astral Coal": "星体煤",
    "Celestial Ember": "天体灰烬",
    "Dragonite": "龙岩",
    "Dragonite Bar 🐉": "龙岩锭 🐉",
    "Eldrite": "电极石",
    "Eldrite Bar 🌌": "电极石锭 🌌",
    "Ethereal": "空灵",
    "Ethereal Bar 🌫️": "以太锭 🌫️",
    "Filter by Material:": "按材质过滤：",
    "Lava Shard": "熔岩碎片",
    "Mana Crystal": "法力水晶",
    "Mithril": "秘银",
    "Obsidium": "黑曜石",
    "Obsidium Bar 🌋": "黑曜石锭 🌋",
    "Required:": "要求:",
    "Runite": "符文石",
    "Soulsteel": "灵魂钢",
    "Soulsteel Bar 💀": "灵魂钢锭 💀",
    "Spirit Dust": "灵尘",
    "Voidstone": "虚空石",
    "🏆 Achievements": "🏆 成就",
    "💀 Top Monsters": "💀 最高怪物",
    "⏱️ Updated just now": "⏱️ 更新于刚刚",
    "Coming Soon": "敬请期待",
    "All skills": "全部技能",
    "Magic": "魔法",
    "Monster Kills": "击杀怪物",
    "Prayer": "玩家",
    "Skill": "技能",
    "Skills Overview": "技能概览",
    "Top items": "最多物品",
    "Top Skills": "最高技能",
    "Total Level": "总等级",
    "Train Skills": "训练技能",
    "Total XP": "总经验值",
    "World": "世界",
    "Agility": "敏捷",
    "Combat statistics": "战斗统计",
    "Construction": "建造",
    "Continue your training": "继续你的训练",
    "Crafting": "制作",
    "Currently equipped": "当前装备",
    "Explore areas": "探索区域",
    "Fight monsters": "对抗怪物",
    "Highest levels": "最高等级",
    "Hunter": "猎人",
    "No items in inventory": "背包中没有物品",
    "Overall Rank": "总排名",
    "Ranged": "远程",
    "Return to homepage": "返回主页",
    "Runecrafting": "符文制作",
    "Sapwood Log": "边材原木",
    "Slayer": "杀手",
    "Thieving": "偷窃",
    "⚔️ Monster Kills Leaderboard": "⚔️ 怪物击杀排行榜",
    "🏆 Leaderboards": "🏆 排行榜",
    "Loading leaderboard...": "排行榜加载中...",
    "Loading monsters...": "怪物加载中...",
    "Select a monster to view leaderboard...": "选择一个怪物以查看排行榜...",
    "Select Monster": "选择怪物",
    "Select Skill:": "选择技能:",
    "Total": "总计",
    "Ashbark Log": "梣木原木",
    "Minnow": "鲦鱼",
    "Mudfin": "泥鳍",
    "Silver Perch": "银鲈鱼",
    "Troutlet": "小鲑鱼",
    "🐟☀️ Raw Sun Carp": "🐟☀️ 生太阳鲤鱼",
    "🐟⚡ Raw Tempest Herring": "🐟⚡ 生风暴鲱鱼",
    "🐟✨ Raw Spirit Koi": "🐟✨ 生精灵锦鲤",
    "🐟❄️ Raw Frost Salmon": "🐟❄️ 生冻鲑鱼",
    "🐟⭐ Raw Starwhale Fry": "🐟⭐ 生星鲸鱼苗",
    "🐟🌊 Raw Cavern Bass": "🐟🌊 生洞鲈鱼",
    "🐟🌑 Raw Void Manta": "🐟🌑 生虚空蝠鲼",
    "🐟🌙 Raw Moon Eel": "🐟🌙 生月鳗鱼",
    "🐟🌿 Raw Ancient Pike": "🐟🌿 生古代梭子鱼",
    "🐟👻 Raw Soulfish": "🐟👻 生灵魂鱼",
    "🐟💎 Raw Aetherfin": "🐟💎 生以太",
    "🐟🔥 Raw Ember Snap": "🐟🔥 生原始灰烬",
    "(3h 0m)\n⏸️ Your training activity has been stopped after 3h 0m (max offline time)": "（3h 0m）\n⏸️您的训练活动在3h 0m（最大离线时间）后已停止",
    "Aetherfin": "以太鳍",
    "Aetherflow Lake": "以太流湖",
    "Ancient Pike": "古梭子鱼",
    "Astralis Depths": "星辰深处",
    "Blazebay Reefs": "火焰礁",
    "Cavern Bass": "洞穴鲈鱼",
    "Duskwater River": "暗水河",
    "Eldergleam River": "接骨木河",
    "Ember Snap": "生原始灰烬",
    "Ethereal Springs": "空灵之泉",
    "Frost Salmon": "冻鲑鱼",
    "Frostmere Fjord": "霜之峡湾",
    "Greyvale Lake": "灰谷湖",
    "Lumford Pond": "拉姆福德池塘",
    "Moon Eel": "月鳗",
    "Moonlit Lagoon": "月光泻湖",
    "Mudfin": "泥鳅",
    "Oakridge Stream": "橡树岭小溪",
    "Silver Perch": "银鲈鱼",
    "Soulfish": "灵魂鱼",
    "Soulrift Pools": "灵魂裂谷池",
    "Spirit Koi": "精灵锦鲤",
    "Starwhale Fry": "星鲸鱼苗",
    "Stormtide Coast": "风暴海岸",
    "Sun Carp": "太阳鲤鱼",
    "Sunshore Bay": "阳光湾",
    "Tempest Herring": "风暴鲱鱼",
    "Troutlet": "小鲑鱼",
    "Umberdeep Waters": "安伯深水区",
    "Void Manta": "虚空蝠鲼",
    "Voidcurrent Sea": "空流之海",
    "💰 Gold": "💰 金币",
    "🍖 Baked Silver Perch": "🍖 烤银鲈鱼",
    "🍖 Fried Mudfin Catfish": "🍖 炸泥鳍鲶鱼",
    "🍖 Grilled Troutlet": "🍖 烤小鲑鱼",
    "🍖☀️ Seared Sun Carp": "🍖☀️ 烤太阳鲤鱼",
    "🍖⚡ Tempest Grilled Herring": "🍖⚡ 风暴烤鲱鱼",
    "🍖✨ Spirit Koi Fillet": "🍖✨ 精灵锦鲤鱼片",
    "🍖❄️ Smoked Frost Salmon": "🍖❄️ 烟熏霜鲑鱼",
    "🍖⭐ Starwhale Feast": "🍖⭐ 星鲸盛宴",
    "🍖🌊 Stuffed Cavern Bass": "🍖🌊 塞洞鲈鱼",
    "🍖🌑 Void Manta Roast": "🍖🌑 虚空蝠鲼烤肉",
    "🍖🌙 Steamed Moon Eel": "🍖🌙 清蒸月鳗",
    "🍖🌿 Eldergleam Chowder": "🍖🌿 接骨木杂烩",
    "🍖👻 Soulfish Steak": "🍖👻 灵魂鱼牛排",
    "🍖💎 Aetherfin Supreme": "🍖💎 以太至尊",
    "🍖🔥 Spicy Ember Snapper": "🍖🔥 辣烬鲷鱼",
    "Aetherfin Supreme": "以太至尊",
    "Baked Silver Perch": "烤银鲈鱼",
    "Eldergleam Chowder": "接骨木杂烩",
    "Fried Mudfin Catfish": "炸泥鳍鲶鱼",
    "Grilled Troutlet": "烤小鲑鱼",
    "Marketplace": "市场",
    "Seared Sun Carp": "烤太阳鲤鱼",
    "Smoked Frost Salmon": "烟熏霜鲑鱼",
    "Soulfish Steak": "灵魂鱼排",
    "Spicy Ember Snapper": "辣烬鲷鱼",
    "Spirit Koi Fillet": "锦鲤鱼片",
    "Starwhale Feast": "星鲸盛宴",
    "Steamed Moon Eel": "清蒸月鳗",
    "Stuffed Cavern Bass": "塞洞鲈鱼",
    "Tempest Grilled Herring": "风暴烤鲱鱼",
    "Train 🍖 Cooked Minnow": "训练🍖煮鲦鱼",
    "Void Manta Roast": "虚空蝠鲼烤肉",
    "Price": "价格",
    "Item": "物品",
    "Next →": "下一页 →",
    "High to Low": "从高到低",
    "Low to High": "从低到高",
    "Resources": "资源",
    "Seller": "卖家",
    "Sort By": "排序",
    "Status": "状态",
    "Time": "时间",
    "Weapons": "武器",
    "Time Left": "剩余时间",
    "Food": "食物",
    "Categories": "类别",
    "Armor": "护甲",
    "Buyer": "买家",
    "Actions": "动作",
    "All Items": "全部物品",
    "← Previous": "← 上一页",
    "+ Create Buy Order": "+ 创建收购订单",
    "+ New Listing": "+ 新卖单",
    "💰 Recent Sales": "💰 最近售出",
    "🛒 Browse": "🛒 浏览",
    "🧭 Marketplace": "🧭 市场",
    "📜 Buy Orders": "📜 收购订单",
    "📦 My Listings": "📦 我的挂单",
    "Be the first to list an item for sale!": "成为第一个上架商品的人！",
    "Create a buy order to request items from other players!": "创建收购订单，从其他玩家那里求购物品！",
    "No active buy orders": "暂无可用买入订单",
    "No items listed": "暂无物品在售",
    "No listings yet. Create your first listing!": "暂无物品在售。创建您的第一个挂单！",
    "No sales yet. Be the first to trade!": "暂无物品在售。成为第一个交易的人！",
    "Quantity": "数量",
    "Recent Marketplace Sales": "近期市场销售",
    "Create Buy Order": "创建买入订单",
    "Create Listing": "创建挂单",
    "Create New Listing": "创建新挂单",
    "Duration": "持续时间",
    "Item Name": "物品名称",
    "Listing Fee (2%):": "上架费（2%）：",
    "Price Per Unit (gold)": "单价（金币）",
    "Quantity Wanted": "想要的数量",
    "Sale Tax (10%):": "销售税（10%）：",
    "Select Item": "选择项目",
    "Total Cost:": "总成本:",
    "Total Sale Price:": "总售价：",
    "You'll Receive:": "你会收到:",
    "Your Gold:": "您的金币：",
    "⚡ Stormpine Fire": "⚡ 风暴之火",
    "✨ Starleaf Fire": "✨ 星叶火",
    "❄️ Frostelm Fire": "❄️ 霜之火",
    "⭐ Astralis Fire 🔥": "⭐ 星界火 🔥",
    "🌌 Voidwood Fire": "🌌 虚空之火",
    "🌫️ Gloomwillow Fire": "🌫️ 冥柳火",
    "🌳 Umberroot Fire": "🌳 翁贝根火",
    "🌿 Eldergrove Fire": "🌿 接骨木林火",
    "💀 Soulbark Fire": "💀 魂吠之火",
    "🔥 Blazewood Fire": "🔥 柴火",
    "🔥 Firemaking": "🔥 生火",
    "Ashbark Fire": "梣树火",
    "Astralis Log": "星辰原木",
    "Birchen Fire": "桦木火",
    "Birchen Log": "桦木原木",
    "Blazewood Log": "红木原木",
    "Burn Sapwood Fire": "燃烧边木火",
    "Eldergrove Log": "接骨木原木",
    "Frostelm Log": "凛冬原木",
    "Gloomwillow Log": "幽柳原木",
    "Ironbark Fire": "铁皮木火",
    "Ironbark Log": "铁皮木日志",
    "Moonwillow Fire": "月柳火",
    "Moonwillow Log": "月柳原木",
    "Sapwood Fire": "边材火",
    "Soulbark Log": "魂吠原木",
    "Starleaf Log": "星叶原木",
    "Stormpine Log": "风暴原木",
    "Sunwood Fire": "太阳木火",
    "Sunwood Log": "太阳木原木",
    "Umberroot Log": "翁贝根原木",
    "Voidwood Log": "虚空木原木",
    "": "",
    "Missing items": "缺少物品",
    "(2x damage) and enters": "（2倍伤害）并进入",
    "⚠️ Travel to this location first": "⚠️请先前往此位置",
    "A massive goblin warlord from Oakridge Forest. Uses": "来自橡树岭森林的大块头哥布林军阀。使用",
    "at 30% HP (+30% attack speed).": "在30%的生命（+30%攻击速度）。",
    "Current Location:": "当前位置:",
    "Double Chop": "双斩",
    "Forest Dryad": "森林仙女",
    "Forest Spider": "森林蜘蛛",
    "Goblin Warrior": "哥布林战士",
    "Greedy Rage": "贪婪之怒",
    "Gruknar the Timberlord": "森林领主格鲁克纳",
    "Oak Wolf": "橡树狼",
    "Oakridge Forest 🔒": "橡树岭森林🔒",
    " Material": "材料",
    "A-Z": "A-Z",
    "A tiny cooked fish. Restores 5 HP.": "一条煮熟的小鱼。恢复5点生命值。",
    "Heals:": "治疗:",
    "Can be cooked into Cooked Minnow.": "可以煮成熟鲦鱼。",
    "Sell": "出售",
    "Used to smith Copper equipment.": "用于铸造铜装备。",
    "No description available": "暂无可用的描述",
    "Astral Collector": "星体收集器",
    "Beggar Pouch": "乞丐袋",
    "Celestine Priest": "塞莱斯廷神父",
    "Fire Cultist": "火教徒",
    "Miner Satchel": "矿工挎包",
    "Phantom Banker": "幻影银行家",
    "Pickpocket Beggar Pouch": "扒手乞丐袋",
    "Shadow Trader": "影子商人",
    "Swamp Hermit": "沼泽隐士",
    "Void Aristocrat": "虚空贵族",
    "Woodland Merchant": "林地商人",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Green": "Green",
    "Trygve86": "Trygve86",
    "Schizocidal": "Schizocidal",
    "Crush": "Crush",
    "Cheese": "Cheese",
    "Mega": "Mega",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "-/-": "-/-",
    "✕": "✕",
    "▶": "▶",
    "© 2025 Idle Crusade. All rights reserved.": "© 2025 Idle Crusade. All rights reserved.",
    "💬": "💬",
    "×": "×",
    "🔒": "🔒",
    "⚔️": "⚔️",
    "🎯": "🎯",
    "🏆": "🏆",
    "X:": "X:",
    "Y:": "Y:",
    "gityx": "gityx",
    "▼": "▼",
    "❤️": "❤️",
    "👤": "👤",
    "👾": "👾",
    "💀": "💀",
    "💪": "💪",
    "🗺️": "🗺️",
    "🛑": "🛑",
    "🛡️": "🛡️",
    "•": "•",
    "⚠️": "⚠️",
    "💡": "💡",
    "👑": "👑",
    "❌": "❌",
    "🔨": "🔨",
    "🏠": "🏠",
    "👢": "👢",
    "🗡️": "🗡️",
    "🦵": "🦵",
    "🧤": "🧤",
    "🪖": "🪖",
    "🎣": "🎣",
    "🍳": "🍳",
    "🛒": "🛒",
    "📜": "📜",
    "📦": "📦",
    "🔥": "🔥",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Rewards: ": "奖励: ",
    "Fishing": "钓鱼",
    "Cooking": "烹饪",
    "Woodcutting": "伐木",
    "Mining": "采矿",
    "Smithing": "锻造",
    "Time remaining: ": "剩余时间：",
    " - ": " - ",
    "⚔️ Combat: ": "⚔️ 战斗: ",
    "📍 ": "📍 ",
    "Combat - ": "战斗 - ",
    "⚡ Mining: ": "⚡ 采矿: ",
    "⚡ Woodcutting: ": "⚡ 伐木: ",
    "⚡ Smithing: ": "⚡ 锻造: ",
    "Atk +": "攻击 +",
    "Str +": "力量 +",
    "Def +": "防御 +",
    "💀 Kills: ": "💀 击杀: ",
    "⚔️ Fighting ": "⚔️ 对抗 ",
    "Combat stance: ": "战斗姿态: ",
    "Smelt ": "冶炼 ",
    "Cooked ": "煮熟的",
    "🍖 Cooked ": "🍖 煮熟的",
    "Raw ": "生",
    "🐟 Raw ": "🐟 生",
    "Started training 🐟 ": "开始训练 🐟 ",
    "Fish 🐟 ": "垂钓 🐟 ",
    "💰 Sell ": "💰 出售 ",
    "Started training 🍖 Cooked ": "开始训练 🍖 煮",
    "Price: ": "价格: ",
    "Farming": "农业",
    "Firemaking": "生火",
    "Fletching": "造箭",
    "Herblore": "草药学",
    "Started training ": "开始训练",
    "📊 Welcome back! You gained progress while offline ": "📊 欢迎回来！您获得了进展在离线的",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    "\n                                ": "\n                                ",
    " (You)": " (你)",
    " Map": " 地图",
    " slots": " 槽位",
    " Bar": "锭",
    " Gloves": " 手套",
    " Platelegs": " 板腿",
    " Helm": " 头盔",
    " Scimitar": " 弯刀",
    " Platebody": " 板甲",
    " (when sold)": " (售出时)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)s$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^ \(([\d\.]+)\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) \|$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\#([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)\% • ([\d\.,]+)\/([\d\.,]+) XP$/, '$1% • $2/$3 经验值'],
    [/^: ([\d\.]+)\% Strength, ([\d\.]+)\% HP$/, ': $1% 力量, $2% 生命值'],
    [/^: ([\d\.]+)\% Defense, ([\d\.]+)\% HP$/, ': $1% 防御, $2% 生命值'],
    [/^: ([\d\.]+)\% Attack, ([\d\.]+)\% HP$/, ': $1% 攻击, $2% 生命值'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+)g$/, '$1 金币'],
    [/^\(([\d\.,]+)g\)$/, '($1 金币)'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) kills$/, '$1 击杀'],
    [/^([\d\.,]+) Hours$/, '$1 小时'],
    [/^([\d\.,]+) XP$/, '$1 经验值'],
    [/^\~([\d\.,]+) XP$/, '~$1 经验值'],
    [/^\+([\d\.,]+) HP$/, '+$1 生命值'],
    [/^\+([\d\.,]+) Gold$/, '+$1 金币'],
    [/^Minnow \(\+([\d\.,]+) HP\)$/, '鲦鱼 (+$1 生命值)'],
    [/^([\d\.,]+) XP to next level$/, '$1 经验值到下一级'],
    [/^([\d\.,]+) XP to next level • ([\d\.,]+) actions • ([\d\.,]+)m ([\d\.,]+)s$/, '$1 经验值到下一级 • $2 动作 • $3分 $4秒'],
    [/^([\d\.,]+) XP per action • ([\d\.,]+)s$/, '每次动作 $1 经验值 • $2秒'],
    [/^⏱️ ([\d\.,]+) min$/, '⏱️ $1 分钟'],
    [/^([\d\.,]+)d ago$/, '$1 天前'],
    [/^([\d\.,]+)h ago$/, '$1 小时前'],
    [/^([\d\.,]+)m ago$/, '$1 分钟前'],
    [/^([\d\.,]+)s ago$/, '$1 秒前'],
    [/^([\d\.,]+) Skills to Master$/, '精通 $1 技能'],
    [/^Requires level ([\d\.,]+)$/, '要求等级 $1'],
    [/^🔒 Requires level ([\d\.,]+)$/, '🔒 要求等级 $1'],
    [/^Level ([\d\.,]+)\–([\d\.,]+)$/, '等级 $1-$2'],
    [/^Level(.+)([\d\.,]+)\-([\d\.,]+)(.+)Monsters$/, '等级 $2-$3 怪物'],
    [/^Level ([\d\.,]+) • Solo Boss$/, '等级 $1 • 单挑Boss'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^HP Level ([\d\.,]+)$/, '生命值等级 $1'],
    [/^You hit Rat for ([\d\.,]+) damage$/, '你击中了 老鼠 并造成了 $1 伤害'],
    [/^You hit Chicken for ([\d\.,]+) damage$/, '你击中了 鸡 并造成了 $1 伤害'],
    [/^Coal x([\d\.,]+)$/, '煤 x$1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Thieving \(([\d\.,]+)\)$/, '盗窃 ($1)'],
    [/^Total Level: ([\d\.,]+)$/, '总等级: $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Page ([\d\.,]+) of ([\d\.,]+)$/, '页数 $1 / $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();