// ==UserScript==
// @name         Llama Legends 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.6
// @description  网页游戏 Llama Legends (https://theluigiplayer.lamaz.dev/llama-legends/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Llama Legends.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://theluigiplayer.lamaz.dev/llama-legends/images/favicons/favicon-32x32.png
// @license      MIT
// @include      *https://theluigiplayer.lamaz.dev/llama-legends/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/llama-legends-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/llama-legends-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/12/28 21:36
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Album": "相册",
    "Card Shop": "卡片商店",
    "Christmas": "圣诞节",
    "Common": "普通",
    "Daily Missions": "每日任务",
    "Epic": "史诗",
    "Drop Rates": "掉率",
    "Divine": "神圣",
    "CONTAINS 1 RANDOM CARD": "包含 1 张随机卡片",
    "Legendary": "传说",
    "LEGENDS": "传奇",
    "LLAMA": "羊驼",
    "Llama Legends": "羊驼",
    "MEGA VALUE BUNDLE": "超值包",
    "Open Booster Pack": "打开助推器包",
    "Polishing hooves...": "擦亮蹄子...",
    "Profile": "个人资料",
    "Rare": "稀有",
    "Work": "工作",
    "Llama Legends Season 1 contains 100 unique cards.": "羊驼传奇第 1 赛季包含 100 张独特的卡片。",
    "Close": "关闭",
    "Total:": "总计:",
    "Booster Pack Info": "助推器卡包信息",
    "Lvl": "等级",
    "Manual": "手动",
    "Llama Intern": "羊驼实习生",
    "Llama Manager": "羊驼经理",
    "Upgrades": "升级",
    "Marketing Campaign": "营销活动",
    "Buy": "购买",
    "Better Shovel": "更好的铲子",
    "Home Office": "家庭办公室",
    "Llama Bank": "羊驼银行",
    "Llama Business Inc.": "羊驼商业公司",
    "Click the Llama to earn money!": "点击羊驼赚钱!",
    "Espresso Machine": "意式浓缩咖啡机",
    "Llama Coins / Click": "羊驼币 / 点击",
    "Llama Coins / Sec": "羊驼币 / 秒",
    "HOLLYWOOL": "好莱坞",
    "Llama Wars": "羊驼大战",
    "Basic": "基础",
    "NEW!": "新!",
    "Open Again": "再次打开",
    "The Original": "原版",
    "Forest Dweller": "森林居民",
    "Ranger": "游侠",
    "Something Special (+100 Llama Coins)": "特殊物品（+100羊驼币）",
    "All Rarities": "所有稀有度",
    "All Series": "所有系列",
    "Cards": "卡片",
    "Condition": "条件",
    "Count": "数量",
    "Date": "日期",
    "Favorites": "收藏",
    "Hollywool": "好莱坞",
    "No.": "编号",
    "Promos": "促销",
    "Rarity": "稀有度",
    "Total Value": "总价值",
    "Total Progress": "总进度",
    "Can't see the forest for the trees. Knows every mushroom by name.": "只见树木不见森林。知道每种蘑菇的名字。",
    "Grade": "评分",
    "Owned": "拥有",
    "Just a llama. No tricks, no frills. Solid.": "只是一只大羊驼。没有诡计，没有装饰。真的。",
    "Sell Extras": "出售额外",
    "Series": "系列",
    "Value": "价值",
    "Year": "年份",
    "Available": "可用",
    "Collect All": "全部领取",
    "free!": "免费!",
    "A starter bonus for you!": "给你的新手奖励！",
    "Gift Box": "礼物盒",
    "History": "历史",
    "No gifts claimed yet.": "暂未领取礼物。",
    "No more gifts available.": "没有更多的礼物可用。",
    "Our herd has grown!": "我们的牧群壮大了！",
    "Redeem": "兑换",
    "Redeem Promo Code": "兑换优惠码",
    "Welcome Gift": "欢迎礼物",
    "MAX": "最大",
    "Claimed": "已领取",
    "WELCOME_1000": "欢迎_1000",
    "Claim": "领取",
    "Reset in": "距离重置",
    "Progress": "进度",
    "Dashboard": "仪表板",
    "GUEST": "游客",
    "Help Center": "帮助中心",
    "": "",
    "Game Statistics": "游戏统计",
    "Last Sync:": "最近同步:",
    "LOCAL DEVICE": "本地设备",
    "Never": "从未",
    "Sign in": "登录",
    "Support Center": "支持中心",
    "Unlocked": "已解锁",
    "View Details": "查看详情",
    "No account?": "还没有账户?",
    "OR": "或",
    "Password": "密码",
    "Register": "注册",
    "Sign in with Google": "使用 Google 快速登录",
    "Forgot Password?": "忘记密码?",
    "Email Address": "邮箱地址",
    "Already registered?": "已有账户?",
    "Reset Password": "重置密码",
    "Send Link": "发送链接",
    "Username": "用户名",
    "Released 2025": "发布于 2025",
    "I know AI art is a controversial topic. For me, using it was the only way to create a game with this much content (200+ unique cards) as a solo dev with zero budget, which allows me to keep the game 100% free and release updates quickly and to generate artwork inspired by popculture.": "我知道AI艺术是一个有争议的话题。对我来说，作为一个零预算的独立开发者，使用它是创造一款拥有如此多内容（200多张独特纸卡片）的游戏的唯一方法，这让我能够保持游戏100%免费，快速发布更新，并生成受流行文化启发的美术作品。",
    "AI Art & Development": "AI美术与开发",
    "Backend via Google Firebase": "后端通过谷歌Firebase",
    "Bluesky": "Bluesky",
    "Built with React & Vite": "用React和Vite构建",
    "Community & Socials": "社区和社交",
    "Forever Free": "永远的自由",
    "GameJolt": "GameJolt",
    "Hosted on Cloudflare Pages": "托管在Cloudflare页面",
    "LamaZ Game Studio": "LamaZ Game Studio",
    "Llama Legends is a passion project. It was made for the fun of it and will always remain free.": "《羊驼传奇》是一个充满激情的项目。它是为了好玩而制作的，并将永远保持免费。",
    "Mastodon": "Mastodon",
    "Technology": "技术",
    "Firebase: Error (auth/network-request-failed).": "Firebase：错误（认证/网络请求失败）。",
    "Sync & Check": "同步 & 检查",
    "Synced": "已同步",
    "Cloud Sync": "云同步",
    "Active": "活跃",
    "Audio": "音频",
    "Data & Savegame": "数据 & 存档",
    "Deutsch": "德语",
    "English": "英语",
    "Export Save": "导出存档",
    "Import Save": "导入存档",
    "Language": "语言",
    "Last": "最近",
    "Master Volume": "主音量",
    "Music": "音乐",
    "Reset Save": "重置存档",
    "Sound Effects": "音效",
    "Status": "状态",
    "Cost:": "成本:",
    "Coin Pouch": "钱袋",
    "Candy Canes:": "Candy Canes:",
    "EVENT": "活动",
    "Go to": "前往",
    "UPDATE": "更新",
    "Use the code:": "使用代码:",
    "Your prayers to the": "你的祈祷",
    "🚀 UPGRADE": "🚀 升级",
    "WARS": "大战",
    "Royal Llama Guard": "皇家羊驼卫队",
    "Pack Results": "拆包结果",
    "Back": "返回",
    "HOLLY": "冬青",
    "GRADED": "评分",
    "The Ruler": "统治者",
    "Accountant": "会计",
    "Admiral": "海军上将",
    "Alchemist": "炼金术士",
    "Angel": "天使",
    "Architect": "建筑师",
    "Artist": "艺术家",
    "Astronaut": "宇航员",
    "Astronomer": "天文学家",
    "Bandit": "强盗",
    "Barber": "理发师",
    "Barista": "咖啡师",
    "Baron": "男爵",
    "Beekeeper": "养蜂人",
    "Bouncer": "保镖",
    "Boxer": "拳击手",
    "Bus Driver": "巴士司机",
    "Butcher": "屠夫",
    "Camper": "露营者",
    "Cardinal": "红衣主教",
    "Cashier": "收银员",
    "Chef": "厨师",
    "Chemist": "化学家",
    "Chieftain": "酋长",
    "Chimney Sweep": "扫烟囱的人",
    "Climber": "登山者",
    "Clown": "小丑",
    "Construction": "建设",
    "Cowboy": "牛仔",
    "Critic": "评论家",
    "Cyclops": "独眼巨人",
    "Dentist": "牙医",
    "Detective": "侦探",
    "Drama": "戏剧",
    "Emperor": "皇帝",
    "Firefighter": "消防队员",
    "Fisherman": "渔夫",
    "Fitness": "健身",
    "Gamer": "玩家",
    "Gardener": "园丁",
    "Gladiator": "角斗士",
    "God": "上帝",
    "Hacker": "黑客",
    "Hipster": "潮人",
    "Hydra": "九头蛇",
    "Influencer": "影响者",
    "Janitor": "清洁工",
    "Judge": "法官",
    "Karen": "凯伦",
    "Knight": "骑士",
    "Librarian": "图书管理员",
    "Lifeguard": "救生员",
    "Magician": "魔术师",
    "Maharaja": "王公",
    "Mailman": "邮差",
    "Matador": "斗牛士",
    "Mechanic": "机械师",
    "Mummy": "木乃伊",
    "Musketeer": "火枪手",
    "Ninja": "忍者",
    "No Probllama": "没问题。",
    "Office": "办公室",
    "Oktoberfest": "啤酒节",
    "Oracle": "甲骨文",
    "Phoenix": "凤凰城",
    "Pilot": "飞行员",
    "Pirate": "海盗",
    "Politician": "政治家",
    "Punk": "朋克",
    "Rapper": "说唱歌手",
    "Robot": "机器人",
    "Samurai": "武士",
    "Scout": "童子军",
    "Shogun": "将军",
    "Sleepy": "困倦",
    "Soldier": "士兵",
    "Spiritual": "精神",
    "Sumo": "相扑",
    "Surfer": "冲浪者",
    "Taxi": "出租车",
    "Teacher": "老师",
    "Tinfoil": "锡纸",
    "Tourist": "旅客",
    "Tsar": "沙皇",
    "Unicorn": "独角兽",
    "Vampire": "吸血鬼",
    "Vegan": "素食主义者",
    "Viking": "维京人",
    "Yeti": "雪人",
    "Yoga": "瑜伽",
    "Back to Profile": "返回个人资料",
    "Cards Sold": "售出卡片",
    "Collection": "收藏",
    "Economy": "经济",
    "Llama Clicks": "羊驼点击",
    "Llama Coins Earned": "赚取的羊驼币",
    "Llama Coins Spent": "花费的羊驼币",
    "Packs Opened": "打开的卡包",
    "Perfect Cards": "完美卡片",
    "Started playing": "开始游戏时间",
    "Total Cards Owned": "拥有总卡片",
    "Unique Cards": "独特卡片",
    "Upgrades Purchased": "购买的升级",
    "Perfect Start": "完美的开始",
    "Rarities": "稀有度",
    "Perfection": "完美度",
    "Promo Reward": "优惠奖励",
    "Own an 'Epic' card.": "拥有一张史诗卡片。",
    "Own a 'Rare' card.": "拥有一张稀有卡片。",
    "Collect your first card.": "收集你的第一张卡片。",
    "Collect your first Hollywool card.": "收集你的第一张好莱坞卡。",
    "Collect your first Llama Wars card.": "收集你的第一张羊驼大战卡片",
    "Collector": "收藏家",
    "Complete Season 1 (100 Cards).": "完成第1赛季（100张卡）",
    "Complete the Hollywool Series (50 Cards).": "完成好莱坞系列（50张卡）",
    "Complete the Llama Wars Series (50 Cards).": "完成“羊驼大战”系列（50张卡）",
    "D3uzb8UZfKYCsJ6OiM6DRsP2Oei1": "D3uzb8UZfKYCsJ6OiM6DRsP2Oei1",
    "likexiazai@qq.com": "likexiazai@qq.com",
    "Lock a card in your album.": "在相册里锁上一张卡片。",
    "Milestones of your Llama Trainer career.": "你的美洲驼驯兽师生涯的里程碑。",
    "Own at least one card of every rarity.": "每种稀有度至少拥有一张卡片",
    "Pull a Legendary card.": "抽取1张传说卡片",
    "Pull an extremely rare 'Divine' card.": "抽取一张极其罕见的“神圣”卡片。",
    "Pull your first duplicate.": "抽到你的第一张重复卡片。",
    "Warehouse": "仓库",
    "Warmed Up": "热身",
    "Own 10 cards with a grade between 4.0 and 6.0.": "拥有10张评分在4.0到6.0之间的卡片。",
    "Own 10 cards with a perfect 10.0 grade.": "拥有10张满分为10.0的卡片",
    "Own 10 copies of the same card.": "拥有10张相同的卡片。",
    "Own 2 different Divine cards.": "拥有2张不同的神圣卡片",
    "Own 20 cards with Grade 3.0 or worse.": "拥有20张评分3.0或更低的卡片",
    "Own 20 different Common cards.": "拥有20张不同的普通卡片。",
    "Own 3 cards with a perfect 10.0 grade.": "拥有3张完美的评分10.0的卡片。",
    "Own 5 cards with a grade worse than 2.0.": "拥有5张评分低于2.0的卡片。",
    "Own 5 cards with a perfect 10.0 grade.": "拥有5张满分10.0的完美卡片。",
    "Own 50 cards with Grade 8.0 or better.": "拥有50张8.0或以上等级的卡片。",
    "Own all 100 cards from Season 1 with a perfect Grade.": "拥有第一季全部100张卡片并获得完美等级",
    "Own all 50 cards from Hollywool with a perfect Grade.": "拥有所有50张来自好莱坞的卡片，并拥有完美的等级。",
    "Own all 50 cards from Llama Wars with a perfect Grade": "拥有《羊驼之战》全部50张卡片并获得完美等级",
    "Sell all duplicates": "出售所有重复卡片",
    "From": "从",
    "Gift Rain": "礼物雨",
    "Christmas Market": "圣诞市场",
    "Candy Canes": "拐杖糖",
    "Catch gifts and candy canes! Avoid the coal!": "抓住礼物和拐杖糖！避开煤！",
    "Leaderboard": "排行榜",
    "Promo": "促销",
    "Play": "玩游戏",
    "Play Free": "免费玩",
    "Rudolph": "鲁道夫",
    "Santa": "圣诞老人",
    "St. Nicholas": "圣尼古拉斯",
    "Top 50": "前50名",
    "Limited Time Event": "限时活动",
    "Llama Bells Event": "羊驼铃铛活动",
    "Time's Up!": "时间到!",
    "Free in:": "距离免费还有:",
    "Gift Rain Leaderboard": "礼物雨排行榜",
    "NEW HIGHSCORE!": "新高分记录!",
    "No scores yet.": "暂无分数。",
    "Top Collectors": "最佳收藏家",
    "News": "新闻",
    "No news available.": "暂无可用新闻。",
    "ERROR": "错误",
    "Error": "错误",
    "LOADING": "加载中",
    "Verbindung fehlgeschlagen.": "连接失败.",
    "UPGRADE": "升级",
    "Northman": "诺斯曼",
    "The Butcher": "屠夫",
    "The Coder": "程序员",
    "The Dancer": "舞蹈家",
    "The Great": "大帝",
    "The Guardian": "守护者",
    "The Illusionist": "幻术师",
    "Conscious Eater": "意识进食者",
    "Dancer": "舞者",
    "Lucky Charm": "幸运符",
    "MC Spit": "MC吐槽",
    "Outlaw": "不法之徒",
    "Punctual": "守时",
    "Sleepyhead": "懒鬼",
    "The Buccaneer": "海盗",
    "The Champion": "冠军",
    "The Chauffeur": "司机",
    "The Coffee Artist": "咖啡艺术家",
    "The Gunslinger": "枪手",
    "The Gym Bro": "健身哥",
    "The Medic": "医师",
    "The Orator": "演说家",
    "The Quiet One": "安静的人",
    "The Rebel": "反叛者",
    "Commander": "指挥官",
    "Disc Jockey": "唱片骑手",
    "Model X-1000": "型号X-1000",
    "Summit Striker": "巅峰突击者",
    "The Educator": "教育家",
    "The Guru": "导师",
    "The Monarch": "君主",
    "The Pharaoh": "法老",
    "The Rescuer": "拯救者",
    "The Ruminant": "反刍动物",
    "The Sleuth": "侦探",
    "Admiral Ackllama": "阿克拉马上将",
    "Ahsoka": "阿索卡",
    "Battle": "战斗",
    "BB-Llama": "BB-羊驼",
    "Boba": "波巴",
    "Bounty Hunter": "赏金猎人",
    "C-3PLlama": "C-3P羊驼",
    "Cantina": "酒吧",
    "Clone": "克隆",
    "Count Doollama": "多拉伯爵",
    "Ewok": "伊渥克",
    "Finn": "芬恩",
    "Gamorrean": "加魔人",
    "General Fleecevious": "弗莱克维斯将军",
    "Geonosian": "吉奥诺西斯",
    "Grand Admiral": "大海军上将",
    "Greedo": "格林多",
    "Grogu": "格鲁古",
    "Han Sollama": "汉索拉玛",
    "Jabba the": "贾巴",
    "Kylo": "凯洛",
    "Llama Binks": "大羊驼宾克斯",
    "Llama Calrissian": "大羊驼·卡瑞辛",
    "Llamando": "美洲驼",
    "Llamawn": "拉姆芒",
    "Mace": "狼牙棒",
    "Mass Opening": "批量拆包",
    "Master Yollama": "尤拉马大师",
    "Mouse": "鼠标",
    "No. 99": "99号",
    "Obi-Wan Kenollama": "欧比旺·科诺拉玛",
    "Padmé Amillama": "阿米拉玛大师",
    "Poe": "坡",
    "Porg": "猪肉",
    "Qui-Gon": "奎刚",
    "R2-DLlama": "R2-D羊驼",
    "Rancor": "怨恨",
    "Rey": "雷伊",
    "Roger Roger": "罗杰·罗杰",
    "Scout Trooper": "侦察骑兵",
    "Snow Trooper": "雪警",
    "Stormllama": "风暴驼",
    "The Astromech": "天体机械师",
    "The Ball": "舞会",
    "The Biker": "飞车党",
    "The Charmer": "的魔术师",
    "The Clumsy One": "笨拙的人",
    "The Collector": "收集器",
    "The Count": "计数",
    "The Defector": "叛逃者",
    "The Foundling": "弃婴",
    "The Gangster": "歹徒",
    "The Guard": "警卫",
    "The Insect": "昆虫",
    "The Knight": "骑士",
    "The Mandalorian": "曼德罗瑞",
    "The Master": "大师",
    "The Maverick": "独行侠",
    "The Mentor": "导师",
    "The Musician": "这位音乐家",
    "The Padawan": "学徒",
    "The Palace Guard": "皇宫卫队",
    "The Pet": "宠物",
    "The Pilot": "飞行员",
    "The Queen": "女王",
    "The Raider": "突袭者",
    "The Rodian": "罗迪亚人",
    "The Sage": "圣人",
    "The Scavenger": "清道夫",
    "The Smuggler": "走私者",
    "The Snack": "零食",
    "The Snow Monster": "雪怪",
    "The Soldier": "士兵",
    "The Speedster": "极速者",
    "The Strategist": "战略家",
    "The Teddy": "泰迪",
    "The Translator": "翻译",
    "Tusken": "塔斯肯",
    "Wampa": "万帕",
    "Winter Proof": "冬天的证据",
    "Agent L": "代理人L",
    "Avenging Angel": "复仇天使",
    "Best Friends": "最好的朋友",
    "Boogeyman": "妖怪",
    "Borat": "波拉特",
    "Braveheart": "勇敢的心",
    "Casabllama": "卡萨布兰卡",
    "Charlie": "查理",
    "Django": "姜戈",
    "Doc Brown": "布朗医生",
    "Dorothy": "多萝西",
    "Drill Instructor": "教官",
    "E.T.": "E.T.",
    "Forrest": "阿甘",
    "Freedom Fighter": "自由斗士",
    "Full Metal": "全金属",
    "Gatsby": "盖茨比",
    "Indiana": "印第安纳州",
    "Intouchable Llamas": "不可接触的大羊驼",
    "Jack Sparrollama": "杰克·斯帕罗玛",
    "John Carter": "约翰·卡特",
    "John Wick": "约翰·威克",
    "Jurassic King": "侏罗纪之王",
    "Kaiju King": "怪兽王",
    "Katniss Everllama": "凯特尼斯·艾弗拉玛",
    "King": "国王",
    "L-800": "L-800",
    "Leon the": "莱昂",
    "Llama Bride": "羊驼新娘",
    "Llama in Black": "黑羊驼",
    "Mad Llamax": "疯狂大羊驼",
    "Marilyn": "玛丽莲",
    "Marty McLlama": "马蒂·麦克拉玛",
    "Mask": "面具",
    "Maverick": "特立独行",
    "Minion": "小黄人",
    "Mockingjay": "嘲笑鸟",
    "Mr. Bean": "憨豆先生",
    "Neo": "Neo",
    "Parasite": "寄生虫",
    "Rambo": "兰博",
    "Road Warrior": "公路勇士",
    "RoboLlama": "机器羊驼",
    "Sensei": "唤醒",
    "Shawshank Llamas": "肖申克的羊驼",
    "Shrek": "怪物史莱克",
    "T-Rex": "霸王龙",
    "TermiLlama": "TermiLlama",
    "The Archaeologist": "考古学家",
    "The Avenger": "复仇者",
    "The Clutz": "克拉兹",
    "The Cyborg": "改造人",
    "The Diva": "天后",
    "The Don": "老头子",
    "The Extraterrestrial": "外星人",
    "The Girl": "这个女孩",
    "The Godllama": "哥达拉马",
    "The Green One": "绿色的人",
    "The Helper": "助手",
    "The Inventor": "发明者",
    "The Llama Ranger": "羊驼护林员",
    "The Martian": "火星",
    "The Millionaire": "百万富翁",
    "The Ogre": "食人魔",
    "The One": "真命天子",
    "The Pirate": "海盗",
    "The Prisoners": "囚犯们",
    "The Professional": "专业的",
    "The Reporter": "记者",
    "The Rider": "骑手",
    "The Romantic": "浪漫主义者",
    "The Runner": "跑步者",
    "The Spaniard": "西班牙人",
    "The Tenant": "租户",
    "The Tramp": "流浪汉",
    "Time Traveler": "时间旅行者",
    "Top Gun": "壮志凌云",
    "Unchained": "解除束缚",
    "Vincent": "文森特",
    "War Machine": "战争机器",
    "Zorro": "佐罗",
    "Eminence": "显赫",
    "Enlightened": "开明",
    "Fighter": "斗士",
    "Gold Maker": "黄金生产商",
    "Green Thumb": "园艺高手",
    "Heavyweight": "重量级人物",
    "Multi-Headed": "多头",
    "Outdoorsman": "户外运动",
    "Sea Bear": "北极熊",
    "Snowllama": "雪驼",
    "Stargazer": "观星师",
    "The Aviator": "飞行员",
    "The Bavarian": "巴伐利亚人",
    "The Builder": "建筑商",
    "The Chiller": "冷水机",
    "The Globetrotter": "环球旅行家",
    "The Gourmet": "美食家",
    "The Knower": "知情者",
    "The Law": "法律",
    "The Mechanic": "机修工",
    "The Mixer": "搅拌机",
    "The Overreactor": "过度反应堆",
    "The Patient": "病人",
    "The Planner": "计划者",
    "The Scanner": "扫描仪",
    "The Seer": "先知",
    "The Shadow": "影子",
    "The Spaceman": "太空人",
    "The Stylist": "发型师",
    "The Trendsetter": "潮流引领者",
    "The Wall": "墙",
    "The Watcher": "守望者",
    "The Wave Rider": "浪人",
    "The Wise": "智者",
    "LIMITED EDITION": "限量版",
    "file": "文件",
    "Collect Reward": "领取奖励",
    "Plays his organ synthesizer all day long.": "整天玩他的风琴合成器。",
    "Sherlock": "神探夏洛克",
    "Special Reward": "特殊奖励",
    "The Bandleader": "乐队指挥",
    "The Detective": "侦探",
    "Max Rebollama": "马克斯·雷博拉玛",
    "The Completer": "完成者",
    "The Creator": "造物主",
    "Awarded for completing Season 1. A masterpiece of collection.": "完成第一季的奖励。收藏佳作。",
    "00Llama": "00羊驼",
    "And the winner is... Awarded for completing Hollywool.": "获胜者是……因完成好莱坞电影而获奖。",
    "Dictator Llamadeen": "独裁者拉玛丁",
    "Rocky": "洛基",
    "Silver Oscar": "奥斯卡银奖",
    "Silver Statue": "银像",
    "Tarzan": "人猿泰山",
    "Tyler Durden": "泰勒·德登",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "PROMO": "PROMO",
    "mos": "mos",
    "mo": "mo",
    "UPG": "升级",
    "Zombie": "僵尸",
    "Griffin": "格里芬",
    "General": "将军",
    "Ghost": "幽灵",
    "Doctor": "医生",
    "Dragon": "龙",
    "Disco": "迪斯科",
    "DJ": "DJ",
    "Sultan": "苏丹",
    "WOOL": "羊毛",
    "X / Twitter": "X / Twitter",
    "Itch.io": "Itch.io",
    "ID:": "ID:",
    "GEM-MT": "宝石-MT",
    "NM-MT": "NM-MT",
    "LamaZ Auth.": "LamaZ Auth.",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "Gityx": "Gityx",
    "G8hh": "G8hh",
    "🦙": "🦙",
    "#": "#",
    "☕": "☕",
    "🎓": "🎓",
    "🏢": "🏢",
    "🏦": "🏦",
    "💼": "💼",
    "📈": "📈",
    "🥄": "🥄",
    "✨": "✨",
    "/": "/",
    "\"": "\"",
    "🎁": "🎁",
    "?": "?",
    "∞": "∞",
    "• ©": "• ©",
    "🚀": "🚀",
    "🎬": "🎬",
    "👑": "👑",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    ">>": ">>",
    ">": ">",
    "<<": "<<",
    "<": "<",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Sore Finger": "手指酸痛",
    "Big Investor": "大投资者",
    "Buying Frenzy": "购物狂潮",
    "Llama Millionaire": "羊驼百万富翁",
    "Llama Tycoon": "羊驼大亨",
    "Money Machine": "赚钱机器",
    "Passive Income": "被动收入",
    "Small Investor": "小投资者",
    "Rebel Alliance": "反叛联盟",
    "Tech Mogul": "科技巨头",
    "A-Lister": "一线明星",
    "Almost There": "快到了",
    "Archivist": "档案员",
    "Black Gold": "黑金",
    "Blockbuster": "轰动一时",
    "Blue Blood": "蓝色血脉",
    "Business & Idle": "商业 & 放置",
    "Card Shark": "卡片高手",
    "Casting Call": "选角呼叫",
    "Click Pro": "点击专业版",
    "Condition & Grading": "条件与评分",
    "Council of Legends": "传奇委员会",
    "Dead Center": "死亡中心",
    "Divine Intervention": "神的干预",
    "Double Trouble": "双重麻烦",
    "Epic Collection": "史诗收藏",
    "Epic Moment": "史诗时刻",
    "Extra": "额外",
    "Fanclub": "歌迷会",
    "Finger of Steel": "钢铁之指",
    "Finger Workout": "手指运动",
    "First Clap": "第一次拍",
    "First Paycheck": "第一份薪水",
    "First Steps": "第一步",
    "First Trial": "初试",
    "Flawless Page": "完美页面",
    "Full House": "浪漫满屋",
    "Galactic Peace": "银河和平",
    "Galactic Perfection": "银河完美",
    "Golden Mean": "黄金分割",
    "Halfway There": "成功了一半",
    "Hard Worker": "努力工作",
    "Hoarder": "囤积狂",
    "Imperial Fleet": "帝国舰队",
    "Jedi Knight": "绝地武士",
    "Jedi Master": "绝地大师",
    "Leading Role": "主导作用",
    "Llama Billionaire": "羊驼亿万富翁",
    "Llama Herd": "羊驼群",
    "Llama Legend": "羊驼传奇",
    "Magic Trio": "魔术三重奏",
    "Market Shark": "市场大佬",
    "Master of the Order": "骑士团团长",
    "Maxed Out": "达到极限",
    "Mint Condition": "完好无损",
    "Monday Production": "周一生产",
    "Money Bin": "钱箱",
    "Mouse Destroyer": "鼠标驱逐舰",
    "Museum Director": "博物馆馆长",
    "Olympus": "奥林匹斯山",
    "Oscar Worthy": "奥斯卡级",
    "Quality Control": "质量控制",
    "Rising Star": "后起之秀",
    "Safety First": "安全第一",
    "Shiny Hand": "闪亮之手",
    "Shopping Spree": "疯狂购物",
    "Small Pile": "小桩",
    "Solid Average": "稳定平均",
    "Something Special": "特别的东西",
    "Stacks on Stacks": "层层叠加",
    "Supporting Role": "配角",
    "The Beginning": "开始",
    "The Force Awakens": "原力觉醒",
    "The People": "人",
    "Total Trash": "垃圾总量",
    "Trash Hoarder": "垃圾囤积者",
    "Wall Street Wolf": "华尔街之狼",
    "Honey Collector": "采蜜者",
    "Pro": "高级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " Llama": " 羊驼",
    " New Year's": "新年",
    " UNLOCKED!": " 已解锁!",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^\#([\d\.,]+)$/,
    /^P\-([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) Llama Legends!$/, '$1 羊驼传奇!'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h left$/, '剩余 $1天 $2小时'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)h Cooldown$/, '$1小时 冷却时间'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Achievements!$/, '$1 成就!'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.,]+) Llama Coins$/, '+$1 羊驼币'],
    [/^([\d\.,]+) Llama Coins$/, '$1 羊驼币'],
    [/^ \(\+([\d\.,]+) Llama Coins\)$/, ' (+$1 羊驼币)'],
    [/^\-([\d\.,]+) elves$/, '-$1 精灵'],
    [/^Click the Llama ([\d\.,]+) times.$/, '点击羊驼 $1 次。'],
    [/^Click the Llama ([\d\.,]+) times in total.$/, '总计点击羊驼 $1 次。'],
    [/^Purchase ([\d\.,]+) upgrades in total.$/, '总计购买 $1 升级。'],
    [/^Earn ([\d\.,]+) Llama Coins total.$/, '总计赚取 $1 羊驼币。'],
    [/^Reach ([\d\.,]+) Llama Coins per Click.$/, '达到每次点击获得 $1 羊驼币。'],
    [/^Reach ([\d\.,]+) Llama Coin per Second.$/, '达到每秒获得 $1 羊驼币。'],
    [/^Reach ([\d\.,]+) Llama Coins per Second.$/, '达到每秒获得 $1 羊驼币。'],
    [/^Own ([\d\.,]+) different cards from Season ([\d\.,]+).$/, '在赛季 $2 拥有 $1 不同的卡片。'],
    [/^Own ([\d\.,]+) cards in total.$/, '总计拥有 $1 卡片。'],
    [/^Own ([\d\.,]+) different Rare cards.$/, '拥有 $1 不同的稀有卡片。'],
    [/^Own ([\d\.,]+) different Legendary cards.$/, '拥有 $1 不同的传说卡片。'],
    [/^Own ([\d\.,]+) different Epic cards.$/, '拥有 $1 不同的史诗卡片。'],
    [/^Own ([\d\.,]+) different cards from Season ([\d\.,]+).$/, '拥有 $1 不同的卡片从赛季 $2。'],
    [/^Own ([\d\.,]+) different perfect cards from Season ([\d\.,]+).$/, '拥有 $1 不同的完美卡片从赛季 $2。'],
    [/^Own ([\d\.,]+) different perfect cards from Llama Wars.$/, '拥有 $1 不同的完美卡片从 羊驼大战。'],
    [/^Own ([\d\.,]+) different perfect cards from Hollywool.$/, '拥有 $1 不同的完美卡片从 好莱坞。'],
    [/^Own ([\d\.,]+) different cards from Llama Wars.$/, '拥有 $1 不同的卡片从 羊驼大战。'],
    [/^Own ([\d\.,]+) different cards from Hollywool.$/, '拥有 $1 不同的卡片从 好莱坞。'],
    [/^Own ([\d\.,]+) cards from Llama Wars.$/, '拥有 $1 卡片从 羊驼大战。'],
    [/^Own ([\d\.,]+) cards from Hollywool.$/, '拥有 $1 卡片从 好莱坞。'],
    [/^Own ([\d\.,]+) perfect card from Llama Wars.$/, '拥有 $1 完美卡片从 羊驼大战。'],
    [/^Own ([\d\.,]+) perfect card from Hollywool.$/, '拥有 $1 完美卡片从 好莱坞。'],
    [/^Own ([\d\.,]+) different perfect cards from Season ([\d\.,]+).$/, '拥有 $1 不同的完美卡片从赛季 $2。'],
    [/^Own ([\d\.,]+) perfect card from Season ([\d\.,]+).$/, '拥有 $1 完美卡片从赛季 $2。'],
    [/^Own a card with Grade ([\d\.,]+).$/, '拥有一张评分为 $1 的卡片。'],
    [/^Own a card with exactly Grade ([\d\.,]+).$/, '拥有一张评分刚好为 $1 的卡片。'],
    [/^Own a card with Grade ([\d\.,]+) or better.$/, '拥有一张评分为 $1 或更高的卡片。'],
    [/^Own ([\d\.,]+) cards with Grade ([\d\.,]+) or better.$/, '拥有 $1 张评分为 $2 或更高的卡片。'],
    [/^Purchase all ([\d\.,]+) upgrades.$/, '购买全部 $1 升级。'],
    [/^Open ([\d\.,]+) Again$/, '再打开 $1 次'],
    [/^Open ([\d\.,]+) Packs$/, '打开 $1 卡包'],
    [/^Open ([\d\.,]+) Booster Packs$/, '打开 $1 助推器卡包'],
    [/^Sell ([\d\.,]+) Cards$/, '出售 $1 卡片'],
    [/^Earn ([\d\.,]+) Llama Coins by working$/, '通过工作赚取 $1 羊驼币'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Season ([\d\.,]+)$/, '赛季 $1'],
    [/^Season ([\d\.,]+) Perfection$/, '赛季 $1 完美度'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();