// ==UserScript==
// @name         Merge Civ 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.34
// @description  网页游戏 Merge Civ (https://mergeciv.io/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Merge Civ.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://mergeciv.io/icon_v2.png
// @license      MIT
// @include      *https://mergeciv.io/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/merge-civ-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/merge-civ-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2026/01/21 15:04
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "/s": "/秒",
    "Food": "食物",
    "food": "食物",
    "Grid": "网格",
    "HIRE": "雇佣",
    "Lvl": "等级",
    "ore": "矿石",
    "Ore": "矿石",
    "Resources": "资源",
    "Scout": "搜寻",
    "Stockyer Stockpiles": "仓库库存",
    "Upgrades": "升级",
    "Wood": "木头",
    "wood": "木头",
    "Villagers merge into Houses.": "村民们聚居在房屋里。",
    "Unlock Apprentice": "解锁学徒",
    "Unlock Houses": "解锁房屋",
    "Unlock Auto-Scout": "解锁自动搜寻",
    "The world reveals itself to the curious.": "这个世界会向好奇者展现其真实面貌。",
    "Increases base capacity of Stockpiles.": "提高储存库的基础容量。",
    "Hires an apprentice to merge basic tiles.": "雇佣一名学徒来合并基础地块。",
    "Claim Surrounding Land": "占领周边土地",
    "BUILD": "建造",
    "Gityx游戏": "",
    "MergeCiv": "合并文明",
    "You can find wood in the forest": "你可以在森林里找到木材。",
    "Unlock Villager": "解锁村民",
    "More hands make less work.": "人手越多，工作越少。",
    "Discovery Chances": "发现几率",
    "Clear Brush": "清理灌木丛",
    "Unlock Forest": "解锁森林",
    "Per Click:": "每次点击:",
    "Buildings Constructed": "建造的建筑物",
    "Data": "存档",
    "ENABLED": "启用",
    "Export Save": "导出存档",
    "Force Save": "强制保存",
    "General": "常规",
    "Hard Reset Game": "硬重置游戏",
    "Import Save": "导入存档",
    "Now": "现在",
    "Last Save:": "最近保存:",
    "Privacy Policy": "隐私政策",
    "Sound Effects": "音效",
    "Stats": "统计",
    "Total Merges": "合并总数",
    "Total Resettlements": "总安置人数",
    "Updates": "更新日志",
    "Upgrades Purchased": "购买的升级",
    "Villagers Spawned": "村民产生",
    "/s Food": "/秒 食物",
    "Allows finding Ore in mines.": "允许在矿井中发现矿石。",
    "Base Capacity": "基础容量",
    "Base Rate": "基础速率",
    "Capacity: +": "容量: +",
    "Harvests resource to the right": "采集右侧资源",
    "Consumes:": "消耗:",
    "Claim Wilderness": "占领荒野",
    "Increases resource storage limits.": "提高资源存储上限。",
    "Total: +": "总计: +",
    "Unlock Ore Mine": "解锁矿石矿井",
    "Unlock Stockpile": "解锁仓库",
    "Villager": "村民",
    "PAUSE": "暂停",
    "RESUME": "返回",
    "WORK": "工作",
    "Unlock Village": "解锁村庄",
    "Smart Apprentice": "聪明的学徒",
    "Houses merge into Villages.": "房屋汇聚成村庄。",
    "Apprentice Status": "学徒状态",
    "Apprentice protects working tiles.": "学徒保护着正在使用的地块。",
    "Apprentice Control": "学徒控制",
    "Allows pausing/resuming the Apprentice.": "允许暂停/恢复“学徒”模式。",
    "REST": "休息",
    "Gold": "黄金",
    "Genius Apprentice": "天才学徒",
    "Apprentice can merge worked tiles (overrides Smart Apprentice).": "学徒可以合并已合并的地块（可替代智能学徒的功能）。",
    "All Resources": "所有资源",
    "Archive": "存档",
    "Civilization Stagnated": "文明停滞",
    "Culture": "文化",
    "Culture Calculation": "文化计算",
    "Empire Upgrades": "帝国升级",
    "Est. Gold": "估计价值：黄金",
    "From Total Empire Value": "来自帝国总价值",
    "Gold & Magic Upgrades": "黄金 & 魔法升级",
    "KEPT": "保留",
    "Lifetime Stats": "生涯统计",
    "LOST": "失去",
    "Population": "人口",
    "RESETTLE": "重新定居",
    "Standard Upgrades": "标准升级",
    "Your grid is full, and expansion is impossible. The era has ended.": "你的网格已经满了，扩展是不可能的。这个时代已经结束了。",
    "Grid Layout & Tiles": "网格布局 & 地块",
    "Empire": "帝国",
    "gold": "黄金",
    "Rush Delivery": "快速配送",
    "Unlock ": "解锁 ",
    "Reduces exploration click delay.": "减少探索点击延迟。",
    "History (": "历史 (",
    "Buy": "购买",
    "Unlocks": "解锁",
    "Unlocked": "已解锁",
    "The Empire": "帝国",
    "Unlocks Tower": "解锁塔",
    "Locked": "未解锁",
    "Mage Tower Access": "法师塔权限",
    "Ascension": "转生",
    "Agricultural Tradition": "农业传统",
    "Animal Husbandry": "畜牧业",
    "Apprentice Education": "学徒教育",
    "Apprentice starts Unlocked.": "学徒模式已解锁。",
    "Auto-Scout starts Unlocked.": "自动侦查功能已开启。",
    "Border Expansion": "边境扩张",
    "Chief's Order": "酋长的命令",
    "Craftsmanship": "工艺",
    "Cultural Heritage": "文化遗产",
    "Cultural Renown": "文化声誉",
    "Divine Mandate": "天命",
    "Fellow Pilgrims": "朝圣者们",
    "Forestry Tradition": "林业传统",
    "Improves automatic scouting speed.": "提高自动搜寻速度。",
    "Increases Culture gain from Prestige.": "通过声望增加文化收益。",
    "Increases Grid Width and Height by 1.": "将网格的宽度和高度各增加1。",
    "Mining Tradition": "挖掘传统",
    "New Foundation": "新基础",
    "Not everyone was lost.": "并非所有人都迷路了。",
    "Oral Tradition": "口头传统",
    "Passive Food Generation per second.": "每秒被动生成食物。",
    "Passive Ore Generation per second.": "每秒被动生成矿石。",
    "Passive Wood Generation per second.": "每秒被动生成木头。",
    "Reinforced Stockpiles": "加强库存",
    "Start with 1 Villager": "开始时有1个村民",
    "Start with 1 Village (Worth 4 Villagers)": "开始时有1个村民 (相当于 4 村民)",
    "Starts the run with smarter apprentices.": "运行开始时有更聪明的学徒。",
    "Stockpiles scale better at higher tiers.": "库存规模在更高级别时更为可观。",
    "Unlocks Forest & Quarry immediately.": "立即解锁森林和采石场。",
    "Unlocks Workshop immediately.": "立即解锁作坊。",
    "Gold/s": "黄金/秒",
    "Unlock Ore ": "解锁矿石",
    "Taxes": "税收",
    "Stockpiles add Gold Storage.": "库存增加了黄金储存。",
    "Secure Vaults": "安全金库",
    "Scouts for Hire": "招募侦查员",
    "Reduces Auto Scout cooldown.": "缩短自动侦察技能的冷却时间。",
    "Population generates Gold.": "人口创造财富。",
    "Grain Silos": "谷仓",
    "Doubles Food Storage Capacity.": "食物储存容量翻倍。",
    "Reduce Apprentice Loop Interval.": "减少学徒循环间隔。",
    "Magic Book": "魔法书",
    "Efficient Bureaucracy": "高效行政机构",
    "Apprentice accumulates charges when idle. Study enough to attempt the MANA (Magic Accumulation Natural Ability) test.": "学徒在闲置状态下会累积能量值。要学习足够多的知识才能尝试进行“魔力积累自然能力”测试。",
    "Early Resettlement": "早期安置",
    "Unlock Castle": "解锁城堡",
    "Allows Resettling before Grid Lock.": "允许在网格锁定前进行重新安置。",
    "Villages merge into Castles (4x Yield, 8 Neighbors).": "村庄融合成城堡（每回合可增加 4 个资源，拥有 8 个相邻区域）。",
    "/s)": "/秒)",
    "%):": "%):",
    "Charge Up": "蓄力",
    "MAXED": "满级",
    "MAX": "最大",
    "Charges": "充能",
    "Charged Storage": "充能仓库",
    "Magic infused stockpiles hold more.": "魔法注入的库存可以容纳更多的东西。",
    "Renown (+": "声望 (+",
    "Priorifies non-stockpile merges. Only merges stockpiles if grid is full.": "优先考虑非库存合并。只有在网格满的情况下才合并库存。",
    "Space Conscious Apprentice": "空间意识学徒",
    "Start with 1 House (Worth 2 Villagers)": "从 1 个房屋开始（价值 2 名村民）",
    "Stockpile Production": "库存生产",
    "Assign a Villager to produce Stockpiles.": "指定一名村民负责管理物资储备。",
    "Accelerate Magic Charge accumulation by 30% per level.": "每升一级加速魔法充能30%。",
    "(Weight:": "(重量:",
    "Adds": "添加",
    "House": "房屋",
    "Harvests & Boosts resources (Left/Right)": "收获 & 提升资源 (左/右)",
    "Start with 1 House + 1 Villager": "从 1 个房屋 + 1 个村民开始",
    "to Stockpile Chance": "到储存几率",
    "Worked Tile Bonus: +": "工作地块奖励：+",
    "Worker Bonus: +": "工人奖励: +",
    "Village": "村庄",
    "Harvests & Boosts adjacent resources": "收获并提升相邻资源",
    "Mage Status": "法师状态",
    "Mana": "法力",
    "MANA Test": "法力测试",
    "Mages generate Mana while working. Rest button removed.": "法师在工作时产生法力值。休息按钮被移除。",
    "Mage Tower": "法师塔",
    "Resettle": "重新安置",
    "A conduit for higher energies. Level 10 unlocks Ascension.": "一种传递更高能量的通道。等级 10 解锁转生。",
    "Cancel": "取消",
    "Ready to Resettle": "准备重新安置",
    "Choose to resettle and claim your legacy.": "选择重新定居并继承你的遗产。",
    "legacy": "遗产",
    "Tile Palette": "地块面板",
    "Requires Early Resettlement Upgrade": "需要早期安置升级",
    "Infused Harvest": "灌注采集",
    "Mana Pool": "法力池",
    "Spells": "法术",
    "Upheaval": "颠覆",
    "Upheaval:": "颠覆:",
    "UPHEAVAL": "颠覆",
    "Destroys a tile to make space.": "摧毁一个地块以腾出空间。",
    "Unlock Spell: Harvest with Tier Multiplier (Cost: 100 Mana).": "解锁法术：收获与层数乘数（消耗：100法力值）。",
    "HARVEST": "收获",
    "Infuse": "灌注",
    "Resettle for": "重新安置并获得",
    "Castle": "城堡",
    "Harvests (4x) & Boosts 8 surrounding resources": "收获（4x）并提升周边 8 种资源的产量",
    "Infuse:": "灌注:",
    "Tap any tile to DESTROY it.": "点击任意一个地块以 摧毁 它。",
    "Next tap yields massive resources.": "接下来点击即可获得大量资源。",
    "ASCEND NOW": "立即转生",
    "CHARGE:": "充能:",
    "Crystal Infusion": "水晶灌注",
    "INFUSE MANA (-": "灌注法力 (-",
    "MANA": "法力",
    "NEXT:": "下一个:",
    "Requires Pending Crystals": "需要等待水晶",
    "Spent:": "花费:",
    "Owned": "拥有",
    "Pending": "等待",
    "Max Mana": "最大法力",
    "from Crystals": "从水晶",
    "Crystal Storage": "水晶存储",
    "Ancient Grimoire": "上古魔法书",
    "Assistance Ritual": "援助仪式",
    "Auto-Buy T1 Upgrades": "自动购买T1升级",
    "Bureaucratic Ritual": "官僚仪式",
    "Projected Start": "预计开始",
    "Reset your empire to gain Magic Crystals and unlock permanent power.": "重置你的帝国以获得魔法水晶并解锁永久力量。",
    "Resonance Rituals": "共鸣仪式",
    "Ritual of Capacity": "容量仪式",
    "Ritual of Culture": "文化仪式",
    "Ritual of Intellect": "智力仪式",
    "Ritual of Space": "空间仪式",
    "Scouting Ritual": "探险仪式",
    "Starting Resources": "初始资源",
    "Total Next Run:": "下一次运行总计：",
    "Warning: Ascending resets your grid, standard resources, gold upgrades, and culture points.": "警告：转生会重置你的网格，标准资源，黄金升级和文化点。",
    "A massive structure that channels earth energy. Persists through Ascension.": "一个能够引导地球能量的巨大结构。持续至转生。",
    "A neo-economic shift focusing on reinvestment. Increases all resource yields.": "一种以再投资为核心的新经济模式。能提高所有资源的产出量。",
    "Crystal": "水晶",
    "Mana Monolith": "法力巨石",
    "Reinvestment": "再投资",
    "Ritual of Quality": "质量仪式",
    "Maxxed Magic Book": "满级魔法书",
    "Current:": "当前:",
    "Next:": "下一级:",
    "Fission": "裂变",
    "INFUSE": "灌注",
    "Mana Syphon": "法力虹吸",
    "When mana is maxxed out, extra will automatically charge the crystal.": "当法力值达到最大值时，额外的法力值会自动充能水晶。",
    "Automatically purchases affordable Tier 1 upgrades every 10 seconds.": "每隔 10 秒钟会自动购买价格合理的顶级升级物品。",
    "Inspect Grid": "检查网格",
    "Increases Prestige Culture gain.": "增加声望文化增益。",
    "Splits a tile into two lower tier tiles.": "将一个地块分割成两个较低层级的地块。",
    "Tree": "树",
    "FISSION": "裂变",
    "Ascension / Crystals": "转生 / 水晶",
    "Rank": "等阶",
    "Magical Upheaval": "魔法剧变",
    "Better equipment and breaks let the Apprentice work faster.": "更先进的设备和更频繁的休息让这位学徒能够工作得更快了。",
    "Equip scouts with swift steeds to hasten their exploration.": "给侦察员配备速度较快的马匹，以便加快他们的侦察速度。",
    "Improve Working Conditions": "改善工作条件",
    "Mounted Scouting": "骑马侦察",
    "Research Tree": "研究树",
    "Resettlement / Gold": "重新安置 / 黄金",
    "Unlock Spell: Delete any tile (Cost: 100 Mana). Prevents Grid Lock.": "解锁法术：删除任意地块（消耗法力值 100）。解除地块锁定状态。",
    "Unlock Spell: Split a tile into two lower tier tiles (Cost: 2000 Mana).": "解锁法术：将一个地块拆成两个较低层级的地块（消耗：2000法力值）。",
    "Unlocks Crystal Upgrades.": "解锁水晶升级。",
    "Unlocks Gold Upgrades.": "解锁黄金升级。",
    "Soft Reset (Retry)": "软重置 (重试)",
    "SPEED BOOST:": "速度提升:",
    "Claim Resources": "收集资源",
    "Earned 1s per 4s offline (25%)": "离线收益现对于在线只有1/4（25%）。",
    "for": "持续",
    "Max": "最大",
    "Speed Boost Acquired": "获得速度提升",
    "Welcome Back!": "欢迎回来!",
    "You were gone for": "你离开了",
    "(Max)": "(最大)",
    "% charged": "% 充能",
    "Ascend": "转生",
    "Capacitative Efficiency": "容能效率",
    "Conservation of Magic": "魔法保护",
    "Houses": "房屋",
    "Decays as boost depletes": "随着增益的减少而衰减",
    "Department of Magical Appraisals": "魔法鉴定司",
    "Increased mana capacity allows for small breakthroughs in mana throughput.": "增加法力容量可以在法力吞吐量上有小的突破。",
    "Magical Upheaval refunds the mana energy binding the tile (1 Mana per theoretical merge).": "魔法剧变会返还绑定地块的法力值（每次理论合并1法力值）。",
    "Mana Earned": "获得的法力",
    "Offline": "离线",
    "Research": "研究",
    "SCOUT": "侦察兵",
    "Transcend for Power": "超越力量",
    "Up to": "最多",
    "Unlocks full appraisal of all magical artifacts.": "解锁对所有魔法物品的全面评估功能。",
    "x Speed": "x 速度",
    "When your mana pool is full, extra will automatically charge the crystal.": "当你的法力池已满时，多余的法力会自动充入水晶中。",
    "☁ Waiting": "☁ 等待中",
    "Limit:": "上限:",
    "Player ID": "玩家ID",
    "Save Now": "立即保存",
    "Share Your Civilization": "分享你的文明",
    "Sign in with Apple": "用苹果账户登录",
    "Sign in with Google": "用谷歌账户登录",
    "Total Clicks": "总计点击次数",
    "Total Playtime": "总计游戏时长",
    "Copy": "复制",
    "Base:": "基础:",
    "Capacity": "容量",
    "Account": "账户（仅限英文版）",
    "Cloud Save Account": "云保存账户",
    "Current Resettlement": "当前重新安置",
    "Current Citadel Tier": "当前城堡层级",
    "Current Ascension": "当前转生",
    "Switch seamlessly between devices — pick up on your phone exactly where you left off on your computer.": "轻松在不同设备之间切换——在手机上继续操作时，能无缝衔接至电脑上中断的进度。",
    "Citadel": "城堡",
    "Culture Earned": "获得的文化",
    "Current Culture": "当前文化",
    "Plans for Citadel": "城堡计划",
    "Plans for Mage Tower": "法师塔计划",
    "Restart for Progress": "重启进程",
    "Tribute Earned": "已获得的献祭",
    "Unlocks build Citadel research": "解锁建造城堡的研究",
    "Unlocks build Mage Tower research": "解锁建造法师塔的研究",
    "Infuse (": "注入 (",
    "✓ Saved!": "✓ 已保存!",
    "Saved!": "已保存!",
    "Available:": "可用:",
    "Cost:": "成本:",
    "Next tap yields massive resources based on tier.": "接下来点击操作会根据等级提供大量资源。",
    "Apprentice": "学徒",
    "Auto-Scout": "自动侦查",
    "Synced": "已同步",
    "Cloud save enabled": "云保存已启用",
    "just now": "刚刚",
    "Save Transfer (Dev)": "存档传输（开发）",
    "Artifacts": "神器",
    "Artifacts:": "神器:",
    "Base (Active)": "基础 (主动)",
    "BUY": "购买",
    "Common": "普通",
    "Crystals": "水晶",
    "Uncommon": "罕见",
    "Time Boost:": "时间提升:",
    "Monolith:": "巨石:",
    "Efficiency:": "效率:",
    "Total:": "总计:",
    "Stacked Stockpiles": "堆叠库存",
    "Mana Generation": "法力生成",
    "Increases stockpile cost by 2x and adds a Mana cost, but spawns a T+1 stockpile instead.": "将库存成本提高 2 倍，并增加法力值消耗，但会生成一个数量多出 1 个的库存。",
    "Subterranean Stockpiles": "地下储存库",
    "Moves all stockpiles to a dedicated subterranean grid.": "将所有库存物资转移至专门的地下存储区域。",
    "XP": "经验值",
    "Wooden Box": "木箱",
    "Artifact": "神器",
    "Bottomless Grain Bag": "无底粮袋",
    "Current Effect": "当前效果",
    "Evergrowing Stick": "常青藤",
    "Experience": "经验",
    "Find duplicates of this artifact to gain XP": "找到这个神器的副本来获得经验值",
    "Infused Jerky": "浸渍牛肉干",
    "Lucky Gold Coin": "幸运黄金",
    "More XP Required": "需要更多经验值",
    "Multiplies Infused Harvest Spell yield and cost.": "增加注入收割法术的产量和成本。",
    "Reduces base stockpile cost by 2 Wood per level.": "每级降低2木材的基本库存成本。",
    "% Each": "% 每个",
    "Accelerating Timepiece": "加速计时器",
    "Bottomless Purse": "无底钱包",
    "Cold Stone": "冷石",
    "Cracked Orb": "破裂球体",
    "Dense Stone": "致密石块",
    "Golden Crown": "黄金王冠",
    "Multiplies Culture gained on resettlement over time in current run.": "在当前回合内，根据重新定居时所获得的文化值，会随着时间的推移而不断增加。",
    "Treated Lumber": "处理过的木材",
    "Unlock via Department of Magical Appraisals": "通过魔法鉴定部解锁",
    "Next →": "下一个 →",
    "available": "可用",
    "Auto-Scout Unlocked": "自动侦查已解锁",
    "Auto-Buy T1 & T2 Upgrades": "自动购买 T1 & T2 升级",
    "Auto-Buy T1, T2 & T3 Upgrades": "自动购买 T1, T2 & T3 升级",
    "Mage Tower Lvl 10 Needed": "需要 10 级魔法塔",
    "A bond forged in starlight — no force of nature can sever the ties between master and apprentice.": "在星光中铸就的纽带——任何自然之力都无法切断师傅与学徒之间的联系。",
    "A labyrinth of scribes and clerks, stamping scrolls faster than any ruler could decree.": "一群书吏和文员忙碌着，比任何统治者下达的命令还要迅速地盖章着卷轴。",
    "Apprentice & Controls Unlocked": "学徒与控制解锁",
    "Apprentice perks persist through Ascension.": "学徒的特殊能力在晋升过程中持续生效。",
    "Auto-Scout (Divine Mandate) remains unlocked after Ascension.": "自动侦察（神谕指令）在晋升后仍保持开启状态。",
    "Automatically purchases affordable upgrades.": "自动购买价格实惠的升级物品。",
    "Eyes in the sky, feet on the ground. Your scouts know every trail before it is forged.": "天空有眼，脚踏实地。你的侦察员在道路形成之前就知晓每一条路径。",
    "Gives a chance to scout higher quality tiles.": "有机会侦察到更优质的土地。",
    "Increases Grid Size by 1 per level.": "每升一级，网格大小增加 1 个单位。",
    "Its pages turn of their own accord, whispering the secrets of ages past to any who dare listen.": "其页面会自行翻动，向任何愿意倾听的人讲述往昔的秘密。",
    "Keep Genius & Space Conscious": "保持天才与空间意识",
    "Keeps Apprentice Education levels after Ascension.": "晋升后仍保留学徒教育等级。",
    "Knowledge, once kindled, can never truly be extinguished. The mind remembers what the world forgets.": "知识一旦点燃，就永远不会真正熄灭。心灵会记住这个世界所遗忘的东西。",
    "Massively increases Food, Wood, and Ore storage limits.": "大幅增加食物、木材和矿石的存储上限。",
    "Mastered Magic Book": "精通魔法书",
    "Merchants from across the land speak of your wares. An unmatched attention to detail, effective, and long lasting.": "来自各地的商人谈起你的商品。对细节的无与伦比的关注，有效且持久。",
    "Ritual Budget": "仪式预算",
    "Songs echo through the ages, carrying the legacy of your people to lands unseen.": "歌曲在岁月中回荡，将你们民族的遗产传递到未知的土地上。",
    "Start every run with the Magic Book fully mastered (Level 100).": "每次开始游戏时，将魔法手册完全掌握（达到 100 级）。",
    "Tap to reveal": "点击查看",
    "Tap to see art": "点击查看艺术品",
    "The elders inscribe ancient boundary stones, and the land itself yields to their authority.": "长老们刻上古老的地界石，土地也臣服于他们的权威。",
    "Warehouses stretch beyond what the eye can see, an endless appetite for the spoils of empire.": "仓库绵延至视线所及之外，对帝国战利品的渴望永无止境。",
    "Epic": "史诗",
    "Legendary": "传说",
    "leather": "皮革",
    "Mana Multiplier": "法力乘数",
    "Mythic": "神话",
    "Rare": "稀有",
    "Golem": "魔像",
    "Chance to spawn tiles +1 Tier Higher per level.": "每升级1级，有概率生成品质+1的地块",
    "Crystal Infuser": "晶体灌注器",
    "Gain interest of 1% of current gold per minute per level.": "每分钟根据等级获得当前金币的 1% 的利息。",
    "Golden Compass": "黄金罗盘",
    "Historic Compendium": "历史图鉴",
    "Interest Accumulator": "利息累积器",
    "Itemized Paystub": "明细工资单",
    "No artifacts in this rarity yet.": "目前此稀有度中没有神器。",
    "Printing Press": "印刷机",
    "Stone of Worship": "崇拜之石",
    "taxes": "税费",
    "Ore ": "矿石 ",
    "Multipliers:": "乘数:",
    "Generation": "生成",
    "Base (Passive)": "基础 (被动)",
    "artifacts": "神器",
    "Active": "活跃",
    "Acquire": "获得",
    "Charge Up:": "充能：",
    "Fission:": "裂变：",
    "From Population": "来自人口",
    "Stockpiles:": "库存:", 
    "Tap a tile to SPLIT it.": "点击一个地块来拆分它。",
    "Build Citadel": "建造要塞",
    "Construct the Citadel. Unlocks a hidden 3x3 grid centered on the Citadel.": "建造要塞。解锁一个位于要塞中心的隐藏 3x3 方格区域。",
    "Global Mult:": "全局乘数:",
    "Bonus Time": "加成时间",
    "FREE": "免费",
    "Work": "工作",
    "Faster production while boost is active": "当提升激活时，更快的生产",
    "Living Rock": "活岩",
    "Card tilt, shimmer & glow": "卡片倾斜，闪烁和发光",
    "Fancy Effects": "梦幻效果",
    "Higher tiers store more resources": "更高的层级储存更多的资源",
    "Tier": "层级",
    "Increases resource storage capacity": "提高资源存储容量",
    "consumption": "消耗",
    "Multiplier:": "乘数:",
    "passive": "被动",
    "villagers": "村民",
    "Rest": "休息",
    "Culture Points": "文化点数",
    "Download": "下载",
    "Grid ·": "网格 ·",
    "Past Civilizations": "过去的文明",
    "played": "已玩",
    "Playtime": "游戏时长",
    "Share": "分享",
    "Resettlements": "重新安置",
    "Stored Underground": "地下储存",
    "Massive resources based on tier.": "基于层级的大量资源。",
    "← Back": "← 返回",
    "← Back to Rituals": "← 返回仪式",
    "Are you sure you want to ascend?": "你确定要转生吗？",
    "Confirm Ascension": "确认转生",
    "Gold Upgrades": "黄金升级",
    "Grid & All Tiles": "网格 & 所有地块",
    "Kept": "保留",
    "Reset": "重置",
    "Mana, Wood, Ore, Food, Gold": "法力, 木头, 矿石, 食物, 黄金",
    "Ritual Assignments": "仪式分配",
    "You will gain": "你将获得",
    "Upgrades/Artifacts:": "升级/神器:",
    "Merge": "合并",
    "Resettlement": "重新安置",
    "Unlocks the Empire panel where you can leave everything behind in exchange for gold and culture.": "解锁帝国面板，在那里你可以放弃一切，以换取黄金和文化。",
    "Next Level": "下一级",
    "Library": "图书馆",
    "Knowledge/s": "知识/秒",
    "Know/s": "知识/秒",
    "Knowledge": "知识",
    "RESET": "重置",
    "Warning:": "警告:",
    "your:": "你的:",
    "the Citadel will": "城堡将",
    "Culture / hour": "文化 / 小时",
    "Capacity:": "容量:",
    "\"From the ashes of the old world, a new bastion of knowledge shall rise.\"": "“旧世界的灰烬之中，一座新的知识堡垒将会崛起。”",
    "\"Imbue every ounce of your power, every single crystal, all you've built, and all your knowledge into the Citadel, a structure that stands above all else.\"": "“将你全部的力量、每一颗水晶、你所建造的一切、你所掌握的一切知识，都注入**要塞**之中——这座凌驾于万物之上的建筑。”",
    "A legendary tale.": "一则传奇传说。",
    "All Tiles & Grid": "所有地块与网格",
    "Ancient Knowledge": "远古知识",
    "Appraise \"Glistening Gem\"": "鉴定「闪耀宝石」",
    "Artifacts and previous Citadel levels are preserved.": "神器与之前的要塞等级会被保留。",
    "Caps Stockpile spawn odds at baseline. Excess workshop power spawns higher tier Stockpiles.": "将储备箱生成概率锁定在基础值。工坊能量溢出时，生成更高阶的储备箱。",
    "Citadel Imbue": "要塞注入",
    "Coalesce Knowledge": "凝聚知识",
    "Construct Citadel": "建造要塞",
    "CONSTRUCT CITADEL": "建造要塞",
    "Constructing": "建造中",
    "Construction Event": "建造事件",
    "Culture Points & Crystals": "文化点数与水晶",
    "Current Level": "当前等级",
    "Detect Magic": "侦测魔法",
    "Expand the Citadel grid to 5x5.": "将要塞网格扩展至 5×5。",
    "Fiction": "传说",
    "Generates": "生成",
    "IMBUE CITADEL": "注入要塞",
    "Imbuing": "注入中",
    "Increases Knowledge Capacity.": "提升知识容量",
    "Prestige Action": "荣耀行动",
    "Requires 'Build Citadel' Level 10": "需要「建造要塞」等级 10",
    "Residential Planning": "居住规划",
    "Spawn higher-tier settlements directly. Level 1: Houses, Level 2: Villages, Level 3: Castles.": "直接生成更高阶的定居点。1级：房屋，2级：村庄，3级：城堡。",
    "Tales of a Boundless Book": "无尽之书的传说",
    "This is a permanent structure that persists across resets.": "这是跨重置永久保留的建筑。",
    "Unlocks advanced storytelling. Libraries generate 1 Culture per Level per hour.": "解锁高级故事创作。图书馆每等级每小时生成 1 点文化值。",
    "Unlocks Common tier Artifacts.": "解锁普通级神器。",
    "Unlocks Rare tier Artifacts.": "解锁稀有级神器。",
    "Unlocks the true potential of the Glistening Gem artifact.": "解锁闪耀宝石神器的真正潜力。",
    "Unlocks Uncommon tier Artifacts.": "解锁精良级神器。",
    "Workshop Assembly Lines": "工坊流水线",
    "citadel": "城堡",
    "Requires Resettlement Upgrade": "需要重新安置升级",
    "Grid Full": "网格已满",
    "Unlocks Epic tier Artifacts.": "解锁史诗层级神器。",
    "tribute": "贡品",
    "Build Library": "建造图书馆",
    "Culture / hr": "文化 / 小时",
    "Current Libraries:": "当前图书馆:",
    "Increases Knowledge Cap by": "提高知识上限",
    "Merges": "合并",
    "Profile": "个人资料",
    "Unnamed Civilization": "未命名文明",
    "Terms of Service": "服务条款",
    "base rate": "基础速率",
    "Birds": "鸟",
    "Birds ready:": "小鸟就绪：",
    "level": "等级",
    "Each level adds 5% to a resource's base production.": "每个等级会将资源的基础产量增加5%。",
    "Each resource has its own starting cost; every level adds the same amount again.": "每个资源都有其初始成本；每提升一个等级，成本再次增加相同金额。",
    "Fallen Feathers": "坠落的羽毛",
    "Level": "等级",
    "Map": "地图",
    "Loading feather upgrades…": "正在加载羽毛升级...",
    "Need": "需要",
    "Production upgrades": "生产升级",
    "The next bird arrives in": "距离下一只鸟抵达还有",
    "Use the arrow keys to move between occupied tiles. Press Enter or Space for the tile's primary action. Press M to select a merge source, move to a matching tile, and press Enter to merge. Press Escape to cancel.": "使用方向键在已占用的方块之间移动。按回车键或空格键执行该方块的主要操作。按 M 键选择合并源，移动到匹配的方块，然后按回车键进行合并。按 Esc 键取消操作。",
    "Account Linked": "账户已连接",
    "Copied!": "已复制!",
    "Delete Account": "删除账户",
    "Your cloud saves are backed up via": "您的云存储备份通过",
    "☁ Synced": "☁ 已同步",
    "Auto": "自动",
    "CREN9CFG": "CREN9CFG",
    "Copy link": "复制链接",
    "Dark": "深色",
    "Mode": "模式",
    "On": "打开",
    "Guide": "指南",
    "Light": "浅色",
    "Use device": "使用设备",
    "Your invite code": "你的邀请码",
    "Visual effects": "视觉效果",
    "% in every category, immediately.": "立即解锁全分类百分比加成",
    "a young civilization": "新生文明",
    "About MergeCiv": "《MergeCiv》介绍",
    "Artifact Collection": "神器藏品",
    "Ascension & Magic": "飞升与魔法",
    "Auto · Full detail": "自动·极致画质",
    "Auto adjusts only after repeated evidence and restores detail when performance stabilizes.": "仅在多次出现性能卡顿后自动降低画质，性能稳定后恢复高清细节",
    "Balanced": "均衡画质",
    "Beginner's guide": "新手教程",
    "Board style": "棋盘界面风格",
    "Boosts Claimed": "已领取增益效果",
    "Build with a plan": "规划建造",
    "c60bba3f-0b8a-4a9b-83bb-c3167c85cccc": "c60bba3f-0b8a-4a9b-83bb-c3167c85cccc",
    "Card tilt, shimmer, and glow": "卡牌倾斜、微光与发光特效",
    "Choose how the illustrated board balances detail and responsiveness.": "自定义棋盘画面精细度与流畅度平衡",
    "Choose the right reset moment and turn Culture into lasting momentum.": "找准重置时机，将文化值转化为长期发展优势",
    "Choose what you hear and how lively the interface feels.": "自定义音效与界面鲜活度",
    "Citadel Imbues": "堡垒灌注",
    "Citadel Level": "堡垒等级",
    "Clear answers for your next merge, reset, or progression milestone.": "清晰指引下一次合成、重置或进阶目标",
    "Erase all progress": "清除全部存档进度",
    "Erasing progress removes your save, upgrades, and lifetime history. This cannot be undone.": "清除进度会删除存档、所有升级与累计数据，操作不可撤销",
    "Fast answers for a stronger run": "快速攻略，助力本局高效发展",
    "Feathers Collected": "已收集羽饰",
    "Field manual": "游戏指南",
    "Founder benefits and purchase recovery.": "创始者专属福利与购买售后找回",
    "Founder's Pack": "创始礼包",
    "Full detail": "极致画质",
    "Go deeper on the system that is shaping your current run.": "深入了解本局核心养成体系",
    "Idle progression": "放置离线收益",
    "Interface": "界面设置",
    "Invited by a friend? Enter their code:": "好友邀请？输入好友邀请码：",
    "Join the community": "加入玩家社群",
    "Know when to combine tiles and when holding position produces more.": "掌握合成地块与囤资源的取舍技巧",
    "Link up": "账号绑定",
    "Linked civilizations strengthen each other. Each milestone a recruit reaches grants you +1% in its category (up to +5% each across your roster) — and having a mentor grants you +": "关联文明可互相增益。招募单位达成任一里程碑，对应分类加成+1%（全部文明单项上限+5%）；拥有导师还可额外获得加成",
    "Living map & oak": "实景大地图与橡木风格",
    "Loading settings…": "正在加载设置……",
    "Make the most of the hidden grids and their specialized systems.": "充分利用隐藏网格及其专属机制",
    "Map rendering": "地图渲染设置",
    "Mentor Bonds": "导师羁绊",
    "Merge strategy": "合成思路",
    "Merges, taps, and build cues": "合成、点击与建造提示",
    "Plan offline earnings, boosts, and a reliable return routine.": "规划离线收益、增益道具，稳定循环发育",
    "Preferences, progress, and your field guide": "偏好设置、存档进度与游戏手册",
    "Privacy policy": "隐私政策",
    "Progress, saves, offline play, and more": "存档、离线游玩等相关说明",
    "Quick answers": "快捷指引",
    "Resettlement & Culture": "移民重置与文化值",
    "Resource guide": "资源指南",
    "Restart current run": "重新开启本局",
    "Restart the current run or erase every saved civilization.": "仅重置当前对局，或清空所有文明存档",
    "Run controls": "对局操作面板",
    "See every resource, storage limit, and the best ways to earn more.": "查看全部资源、存储上限及高效获取途径",
    "Set the interface lighting and the board's material style.": "调整界面光影与棋盘材质风格",
    "Settler": "移民单位",
    "Share strategies, feedback, and bug reports on Discord": "前往Discord分享攻略、反馈建议、提交bug",
    "Sound & motion": "音效与动效",
    "Sound effects": "音效设置",
    "Start here": "新手入门指引",
    "Strategy library": "攻略文库",
    "Strategy tips": "进阶技巧",
    "Support MergeCiv": "赞助支持《MergeCiv》",
    "Terms of service": "服务条款",
    "The game, its systems, and the solo developer behind it": "游戏玩法体系与独立开发者介绍",
    "Total Ascensions": "总飞升次数",
    "Underground & Citadel": "地下区域与堡垒系统",
    "Understand Magic, Artifacts, Rituals, and the next progression layer.": "解析魔法、神器、仪式及下一阶段养成内容",
    "Your first hour, from the opening grid to a confident first resettlement.": "新手首小时教程：从初始地块到顺利完成首次移民重置",
    "1h of resources instantly": "立即获得1小时的资源",
    "grid ·": "网格 ·",
    "Story": "故事",
    "Square": "正方形",
    "Wide": "长方形",
    "Royal Shop": "皇家商店",
    "You earned": "你获得了",
    "Game Speed": "游戏速度",
    "cooldowns.": "冷却时间.",
    "grants": "给予",
    "Boost": "提升",
    "AutoScout": "自动侦查",
    "AutoMerge": "自动合成",
    "Boost Reward!": "提升奖励!",
    "and": "和",
    "and increases game speed — decreasing": "并提升游戏速度，缩减耗时",
    "Boost Charges": "增益次数",
    "Boost Time Remaining": "剩余增益时长",
    "Boost time stacks — claiming again adds more.": "增益时长可叠加，重复领取会追加时长",
    "Catch this bird — one click, then it flies away. Available briefly.": "捕捉飞鸟：点击一次后它便飞走，限时出现",
    "Claim Free 1h Boost": "领取1小时免费增益",
    "Loading bonus time…": "正在加载奖励时长……",
    "Loading magic…": "正在加载魔法效果……",
    "Loading offline earnings…": "正在加载离线收益……",
    "Loading share card…": "正在加载分享卡片……",
    "of resources + boost": "资源加成与增益效果",
    "The focused tile changed. Focus moved to the next available tile.": "聚焦地块已切换，焦点自动移至下一块可用地块",
    "charge": "充能",
    "Extra Boosts — Founder's Pack": "额外的提升 - 创始人包",
    "Free boost in": "免费提升还有",
    "Next charge in": "下一次充能还有",
    "Unlock your remaining": "解锁你的剩余",
    "with the Founder's Pack": "通过 创始人包",
    "Resource": "资源",
    "Permanent": "永久",
    "Recharge": "重新充能",
    "Roost upgrades": "栖息地升级",
    "Goal": "目标",
    "first": "首先",
    "Feathers Dropped": "掉落羽毛",
    "feathers": "羽毛",
    "each": "每个",
    "current": "当前",
    "Bird Cap": "飞鸟便帽",
    "max": "最大",
    "min": "最小",
    "Hit each resource achievement; the resource stays yours and feathers pay for the upgrade.": "命中各资源成就；该资源将永久归你所有，羽毛用于升级。",
    "Tips": "提示",
    "© 2026 MergeCiv. All rights reserved.": "© 2026 MergeCiv. All rights reserved.",
    "About": "关于",
    "FAQ": "常见问题",
    "The Citadel is built with 100 million Ore and 10,000 Mana. It is a 3x3 grid (expandable to 5x5) that houses Libraries, Theatres, and the Citadel center. Libraries generate Research, Theatres boost Culture capacity, and Magic Crystals can be assigned to Ritual slots here for permanent bonuses that persist through every reset.": "要建造要塞，需要100m矿石和1万法力值。它是一个3x3的网格（可扩展为5x5），内部包含图书馆、剧院以及要塞中心。图书馆可生成研究资源，剧院可提升文化容量，而魔法水晶可被分配到仪式槽位中，以获得永久性加成，该加成在每次重置后仍持续有效。",
    "Artifacts are permanent items discovered through the Detect Magic upgrade. They come in six rarities — Common, Uncommon, Rare, Epic, Legendary, and Mythic — and provide passive bonuses that grow stronger as you level them up. Standout artifacts include the Golem (1.2x resource generation per level) and the Golden Compass (better Scout spawns).": "神器是通过“探测魔法”升级后发现的永久性物品，共有六种稀有度——普通、稀有、罕见、史诗、传奇和神话，并且随着等级提升，提供的被动加成效果会不断增强。其中突出的神器包括地精（每级生成资源1.2倍）和金罗盘（更优质的侦察兵生成）。",
    "After your first Ascension, Magic becomes available. Mana is generated passively by the Apprentice when it is idle and is spent on powerful spells like Magical Upheaval, Infused Harvest, and Fission. Your maximum Mana is 100 per Magic Crystal you own, so invest in Mana capacity upgrades and use spells strategically.": "首次升阶后，魔法将变得可用。学徒在闲置时会被动生成法力值，并用于施放诸如“魔法动荡”、“注入丰收”和“裂变”等强力法术。每拥有一个魔法水晶，你的最大法力值为100，因此请投资于法力容量提升，并战略性地使用法术。",
    "Ascension is the second, deeper reset layer, available after multiple Prestiges. Ascending resets your Culture but unlocks an entirely new dimension of power: the Magic system, Artifacts, Rituals, and the Citadel. Items gained through Ascension, such as Artifacts and Magic Crystals, persist permanently across all future resets.": "转生是第二层、更深层的重置，需通过多次声望后方可获得。转生会重置你的文化（Culture），并解锁一个全新的力量维度：魔法系统、神器、仪式以及要塞。通过转生获得的物品，如神器和魔法水晶，将在所有未来的重置中永久保留。",
    "Drag one tile onto an identical tile of the same type and tier to combine them into a single higher-tier version. Only tiles of the same type and tier can merge. Each tier roughly doubles production, so you should always merge when possible to keep growing.": "将一个相同类型和等级的方块拖到另一个相同类型的方块上，即可合并成一个更高等级的新版本。只有相同类型和等级的方块才能合并。每个等级的生产量大约翻倍，因此应尽可能地进行合并，以保持持续成长。",
    "Every resource has a storage capacity limit, and when storage is full any excess production is lost. Build and merge Stockpiles early to raise your caps, and watch the resource bars at the top of the screen. Underground Stockpiles, unlocked later, provide massive additional storage for the late game.": "每种资源都有存储容量上限，当存储满时，超出部分的产量将被浪费。尽早建造并合并储藏堆以提升上限，并留意屏幕顶部的资源条。地下储藏堆在后期解锁后可提供大量额外存储空间，适合游戏后期使用。",
    "MergeCiv has seven resources, each with a distinct purpose: Food (spawns Villagers), Wood (builds Stockpiles and housing), Ore (advanced upgrades and the Citadel), Metal (mid-to-late game upgrades), Gold (gold-tier upgrades), Research (Citadel improvements), and Culture (permanent legacy upgrades). Managing production and storage capacity is the key to steady progression.": "MergeCiv拥有七种资源，每种资源都有其独特用途：食物（生成村民）、木材（建造储物仓和住房）、矿石（高级升级和要塞）、金属（中期至后期游戏升级）、黄金（黄金等级升级）、研究（要塞改进）以及文化（永久性遗产升级）。合理管理生产与存储能力是稳定推进的关键。",
    "MergeCiv has three grid layers. The Surface is your main play area, starting at 3x3 and expandable up to 6x6. The Underground, unlocked via Subterranean Stockpiles, only accepts Stockpile tiles but offers massive storage. The Citadel is an advanced layer for Libraries, Theatres, and Rituals.": "MergeCiv 有三层网格结构。表面是主要的活动区域，初始为3x3，可扩展至6x6。地下层通过地下储备点解锁，仅接受储备点方块，但提供巨大的存储空间。要塞层则用于图书馆、剧院和仪式等高级建筑。",
    "Prestige is MergeCiv's first reset layer, unlocked via the Resettlement upgrade. Do not Prestige the moment it becomes available — the Culture you earn scales with your Villager population, and higher-tier Villagers contribute exponentially more. Wait until your growth noticeably stalls, then Prestige for a large Culture payout.": "声望是MergeCiv的第一个重置层，通过重新定居升级解锁。当声望可用时不要立即提升——你获得的文化值会随着村民数量增长而增加，而高等级村民的贡献则呈指数级上升。等到你的增长明显停滞后，再提升声望，即可获得高额文化收益。",
    "These are MergeCiv's automation features. The Apprentice automatically merges matching tiles, and upgrades like Smart Apprentice and Space Conscious make it smarter about which tiles to touch. The Scout automatically spawns new tiles every 10 seconds and is attracted to neighboring tiles of the same type, creating natural merge clusters.": "以下是MergeCiv的自动化功能。学徒会自动合并匹配的方块，而智能学徒和空间意识等升级功能则使其更智能地决定触碰哪些方块。侦察兵每10秒自动生成新方块，并会被相同类型的相邻方块吸引，从而形成自然的合并群组。",
    "When you close the game, your civilization keeps producing resources. On your next visit you are shown a summary of everything earned while away and can claim it all at once. Earnings cap out based on your storage limits, so expand your storage before long breaks to avoid missing out on production.": "当你关闭游戏时，你的文明会继续生产资源。下次登录时，系统会显示你离开期间获得的所有收益，并允许你一次性领取全部收入。由于收益受存储空间限制，因此在休息前请提前扩展存储容量，以免错过生产机会。",
    "Yes. MergeCiv is completely free to play, with optional rewarded ads and supporter packs. There are no paywalls — every feature in the game can be earned through gameplay alone. It is available on Web, on iOS via the App Store, and on Android (coming soon).": "是。MergeCiv 全部免费畅玩，可选择观看付费广告或购买支持者礼包。游戏没有付费墙，所有功能均可通过游戏本身获得。游戏可在网页端、iOS平台（通过App Store）以及安卓平台（即将上线）上运行。",
    "Yes. MergeCiv supports cloud save sync across devices, so you can play on web, iOS, or Android and keep the same progress. Account linking via Apple or Google enables the cloud save, though it is optional — you can also play entirely on a single device.": "是。MergeCiv 支持跨设备的云端保存与同步，因此您可以在网页、iOS 或 Android 设备上播放，并保持进度一致。通过 Apple 或 Google 进行账户绑定可启用云端保存功能，但此选项为可选——您也可以完全在单一设备上播放。",
    "Beginner's Guide": "新手教程",
    "Can I play across multiple devices?": "我可以多设备游玩吗？",
    "Common questions about MergeCiv's mechanics, progression, and systems. For deeper detail, see the": "关于《MergeCiv》机制、养成与系统的常见问题，更多详情可查看",
    "Frequently Asked Questions": "常见问答",
    "How do I merge tiles?": "如何合成地块？",
    "How do offline earnings work?": "离线收益如何计算？",
    "How does the Citadel work?": "堡垒系统如何运作？",
    "How does the Magic system work?": "魔法系统怎么玩？",
    "Is MergeCiv free to play?": "《MergeCiv》是否免费游玩？",
    "Play MergeCiv": "开始游戏",
    "Privacy": "隐私相关",
    "Quick answers about playing MergeCiv": "游戏简易答疑",
    "Strategy Tips": "攻略技巧",
    "Terms": "服务条款",
    "What are Artifacts?": "神器是什么？",
    "What are the different grid layers?": "网格分为哪些层级？",
    "What do the Apprentice and Scout do?": "学徒和侦察兵有什么作用？",
    "What is Ascension?": "飞升是什么？",
    "What resources are there and what are they for?": "有哪些资源，各自用途是什么？",
    "When should I Prestige?": "什么时候适合转生重置？",
    "Why are my resources being wasted?": "为什么我的资源会无故损耗？",
    "or": "或",
    "artifact, the game favors ones you don't own yet — so you complete those high-value sets instead of repeatedly rolling duplicates. Your first Epic is always the Interest Accumulator, and your first Legendary is always the Printing Press. Once a tier is fully collected, duplicates start leveling it up again. Lower rarities always roll evenly, since their duplicates are what level them. The odds of": "神器，游戏倾向于你还没有拥有的东西，所以你完成那些高价值的集合，而不是反复滚动副本。你的第一张史诗卡总是兴趣累积器，第一张传奇卡总是印刷机。一旦某个稀有度等级被完全收集，重复的卡牌就会再次提升该等级。较低的稀有度总是均匀地滚动，因为它们的副本是它们的等级。发生的几率",
    "Ascension is the second, deeper reset layer. After multiple Prestiges, you can Ascend to unlock the Magic system, Artifacts, Rituals, and the Citadel. Ascending resets your Culture but grants access to an entirely new dimension of power. Items gained through Ascension — like Artifacts and Magic Crystals — persist permanently.": "转生是第二层、更深层次的重置。在多次获得尊贵之后，你可以通过转生来解锁魔法系统、神器、仪式以及要塞。转生会重置你的文化，但同时赋予你一个全新的力量维度。通过转生获得的物品——如神器和魔法水晶——将永久保留。",
    "Prestige is unlocked via the Resettlement upgrade. The Culture you earn scales with your Villager population — specifically, higher-tier Villagers contribute exponentially more. Wait until growth stalls, then Prestige for a big Culture payout.": "转生功能通过移民重置升级解锁。文化值产出与村民数量挂钩，高阶村民的产出收益呈指数级增长。等发展陷入停滞时再转生，可一次性获取大量文化值。",
    "Merging is the heart of MergeCiv. Your grid starts as a 3x3 board filled with basic tiles. Drag one tile onto an identical tile of the same type and tier to combine them into a single higher-tier version. Higher tiers produce dramatically more resources thanks to exponential scaling.": "合成是《MergeCiv》的核心玩法。初始棋盘为3×3基础地块，将同类型、同等级的地块互相拖拽即可合成，产出更高等级地块。高等级地块依靠指数增长机制，资源产出会大幅提升。",
    "Artifacts are permanent items discovered through the Detect Magic upgrade. They come in six rarities — Common, Uncommon, Rare, Epic, Legendary, and Mythic — and provide passive bonuses that grow stronger as you level them up.": "神器为永久道具，解锁侦测魔法升级后可获取。神器分为六种品质：普通、精良、稀有、史诗、传说、神话，升级神器可强化其常驻加成效果。",
    "Every resource has a capacity limit. When storage is full, excess production is lost. Build and merge Stockpiles early to prevent waste. Underground Stockpiles (unlocked later) provide massive additional storage.": "所有资源均设有存储上限，仓库存满后多余产出会直接消失。尽早建造并合成仓库，避免资源浪费。后期解锁地下仓库，可大幅扩充存储容量。",
    "Built with 100 million Ore and 10,000 Mana. A 3x3 grid (expandable to 5x5) that houses Libraries, Theatres, and the Citadel center. Libraries generate Research, Theatres boost Culture capacity, and Magic Crystals can be assigned to Rituals here for persistent bonuses.": "消耗一亿矿石与一万魔力建造，自带3×3区域（可扩容至5×5），用于放置图书馆、剧院与核心堡垒。图书馆产出研究值，剧院提升文化存储上限，还可在此将魔法水晶投入仪式，获取永久增益。",
    "Unlocked via the Apprentice upgrade. The Apprentice automatically merges matching tiles on your grid. Upgrade to Smart Apprentice (protects tiles you are working on), Genius Apprentice (can merge worked tiles), and Space Conscious (prioritizes non-stockpile merges to prevent grid clutter).": "通过学徒升级解锁。学徒会自动合并棋盘上相同地块。升级智能学徒可保护正在操作的地块；天才学徒可合并标记地块；空间感知学徒优先合成非仓库地块，避免棋盘堆满杂物。",
    "The Scout automatically spawns new tiles onto your grid every 10 seconds. The Scout is attracted to neighboring tiles of the same type, creating natural merge clusters. Workshop Assembly Lines add tier bonuses to spawned tiles.": "侦察兵每十秒自动在棋盘生成新地块，更倾向于在同类地块旁刷新，方便形成可合成地块集群。工坊生产线能提升刷新地块的等级加成。",
    "— Adds 1% Culture production per minute. Speeds up legacy upgrades over time.": "每分钟文化产出提升1%，随时间加速传承升级进度。",
    "— Convert raw materials into Metal, unlocking mid-game upgrades and empire infrastructure.": "将原材料冶炼为金属，解锁中期升级与帝国基建。",
    "— Destroy any tile on the grid. Essential for clearing deadlocks when your grid is full of unmergeable tiles.": "销毁棋盘任意地块，棋盘堆满无法合成的地块时，用来解除卡死局面。",
    "— Generate Food, your most basic resource. Food is used to spawn Villagers and fuel early upgrades.": "产出食物，基础核心资源，用于生成村民、完成前期升级。",
    "— Grants bonus Mana based on your population. Synergizes with Villager-heavy strategies.": "根据人口数量提供魔力加成，适配多村民发育流派。",
    "— Harvest a tile's resources with a bonus multiplier based on tier. Great for squeezing extra value from high-tier tiles.": "按地块等级倍率额外收获资源，适合榨取高阶地块剩余收益。",
    "— Improves the quality of tiles the Scout spawns. Higher average tiers mean faster merges.": "提升侦察兵刷新地块品质，平均等级更高，合成节奏更快。",
    "— Increase your resource storage capacity. Without stockpiles, production overflows and resources are wasted.": "扩充资源存储上限，无仓库会导致产出溢出、资源流失。",
    "— Multiplies resource generation by 1.2x per level. One of the strongest general-purpose artifacts.": "每级资源产出倍率×1.2，泛用性极强的强力神器。",
    "— Produce Wood, essential for building Stockpiles and expanding storage capacity.": "产出木材，建造仓库、扩容存储空间的必备材料。",
    "— Provide housing for Villagers, increasing your population cap.": "为村民提供住所，提升人口上限。",
    "— Split one tile into two copies of one tier lower. Useful for duplicating valuable high-tier tiles to set up future merges.": "将一块地块拆分为两块低一级地块，可复制高阶地块方便后续合成。",
    "— Yield Ore, a rarer resource needed for advanced upgrades and eventually building your Citadel.": "产出矿石，稀有资源，用于高阶升级，最终建造堡垒。",
    "— Your workforce. Each Villager boosts production and contributes to Population, which determines Prestige rewards.": "劳动力单位，每名村民提升产出，计入总人口，决定转生收益。",
    "After your first Ascension, the Magic system becomes available. Mana is generated passively by the Apprentice when idle and is spent on powerful spells.": "首次飞升后解锁魔法系统。学徒闲置时会持续产出魔力，魔力可释放强力法术。",
    "As your civilization grows, automation features let the game play itself while you focus on strategic decisions.": "文明发展到一定阶段后，各类自动功能将解放双手，你只需专注规划策略。",
    "Automation": "自动系统",
    "Each tier roughly doubles production, so always merge when possible.": "地块每升一级产出近乎翻倍，有合成机会尽量合成。",
    "Earned permanently when you Prestige. Spent on legacy upgrades that persist across resets, like Traditions and Cultural Renown.": "转生永久获取，用于跨重置生效的传承升级，如传统、文明声望。",
    "Earned through Prestige and Taxes. Spent on powerful gold-tier upgrades like Secure Vaults, Grain Silos, and Reinvestment.": "通过转生与税收获取，兑换金色强力升级，如安全金库、粮仓、再投资机制。",
    "Everything you need to start building your civilization": "文明起步全流程指南",
    "Fission (2,000 Mana)": "裂变（消耗2000魔力）",
    "Forests": "森林地块",
    "From Ore Deposits. Rarer and harder to stockpile. Required for advanced upgrades and eventually building the Citadel.": "产自矿脉，稀有且存储难度高，高阶升级、建造堡垒必需资源。",
    "Generated by Wheat Fields. Spent on spawning Villagers and basic upgrades. You will need a lot of it.": "麦田产出，用于生成村民与基础升级，需求量极大。",
    "Grid Layers": "多层网格",
    "Infused Harvest (100 Mana)": "灌注收割（消耗100魔力）",
    "Keep your grid tidy — a full grid with no merges means you are stuck.": "保持棋盘整洁，铺满无法合成的地块会直接卡住发育。",
    "Legacy Upgrades": "传承升级",
    "Magic System": "魔法系统",
    "Magic Upgrades": "魔法强化",
    "Magical Upheaval (100 Mana)": "魔力剧变（消耗100魔力）",
    "Mana Management": "魔力运营",
    "MergeCiv features three distinct grid layers, each with unique mechanics.": "本作包含三层独立网格，每层拥有专属机制。",
    "MergeCiv has seven resources, each serving a distinct purpose. Managing production and storage capacity is key to steady progression.": "游戏共有七种资源，用途各不相同，把控产出与存储上限是稳步发育的关键。",
    "Merging Tips": "合成技巧",
    "Metal": "金属",
    "New to MergeCiv? This guide walks you through the core mechanics, from your first tile merge all the way to mastering Ascension and Magic. Bookmark this page and come back as you unlock new systems.": "刚接触游戏？这份教程详解全部核心机制，从初次合成地块到精通飞升与魔法。收藏页面，解锁新系统时随时查阅。",
    "Notable Artifacts": "强力神器一览",
    "Offline Earnings": "离线收益",
    "One-time purchases that unlock new tile types and core mechanics. Examples include unlocking Forests, Ore Deposits, Villagers, the Apprentice (auto-merge), and Grid Expansion.": "一次性付费解锁全新地块类型与核心玩法，例如森林、矿脉、村民、自动合成学徒、网格扩容等功能。",
    "Only tiles of the same type and tier can merge.": "仅同类型、同等级地块可进行合成。",
    "Ore Deposits": "矿脉",
    "Prestige and Ascension": "转生与转生",
    "Prestige is MergeCiv's first reset layer. When your civilization has grown as far as it can go efficiently, you Prestige to earn Culture Points and Gold, then start fresh with permanent bonuses.": "转生是游戏第一层重置机制。当文明发展至效率瓶颈时，即可转生获取文化点数与金币，重新开局并获得永久加成。",
    "Produced by Forests. Used for Stockpiles, housing, and expanding your grid. Keep Wood production high to avoid storage bottlenecks.": "森林产出木材，用于建造仓库、民居、扩容网格。维持木材高产出，避免存储容量不足。",
    "Purchased with Culture Points and persist permanently across Prestiges. Traditions give passive resource income, Divine Mandate enables auto-scouting, and Cultural Renown boosts Prestige rewards by 50%.": "消耗文化点数购买，转生后永久生效。传统提供常驻资源收益；天命开启自动侦察；文明声望提升50%转生奖励。",
    "Purchased with Gold earned from Prestige. Includes Taxes (passive Gold income), Secure Vaults (Gold capacity), Grain Silos (resource caps), and Reinvestment (multiplies all production by 1.1x per level).": "消耗转生所得金币购买，包含税收（金币持续产出）、安全金库（金币存储上限）、粮仓（各类资源上限）、再投资（每级全资源产出倍率×1.1）。",
    "Repeatable upgrades with increasing costs. Stockier Stockpiles, Stacked Stockpiles, and Workshop Assembly Lines all scale up, providing compounding benefits the more you invest.": "可重复升级，消耗逐级递增。大容量仓库、堆叠仓库、工坊生产线均可持续强化，投入越多收益叠加越高。",
    "Resources and Economy": "资源与经济体系",
    "Scalable Upgrades": "可循环升级",
    "Stockpiles": "仓库",
    "Stockpiles can be merged too. Higher-tier stockpiles hold more resources.": "仓库同样能够合成，高阶仓库拥有更大存储容量。",
    "Storage Matters": "存储容量至关重要",
    "Surface": "地表层",
    "The Apprentice (Auto-Merge)": "自动合成学徒",
    "The Scout (Auto-Spawn)": "自动生成侦察兵",
    "Tile Merging Basics": "地块合成基础规则",
    "Tile Types": "地块种类",
    "Underground": "地下",
    "Unlocked after Ascension. Includes the Magic Book (Mana generation), individual Spells, and Mana capacity increases.": "飞升后解锁，包含魔法典籍（魔力产出）、各类法术、魔力上限提升。",
    "Unlocked by building Libraries inside your Citadel. Fuels advanced research upgrades and Citadel improvements.": "在堡垒内建造图书馆解锁，用于高阶科研升级与堡垒改造。",
    "Unlocked via the Subterranean Stockpiles upgrade. Only accepts Stockpile tiles, but provides massive additional storage capacity. Essential for late-game resource management.": "解锁地下仓库升级后开放，仅可放置仓库地块，大幅扩充存储空间，是后期资源管理核心。",
    "Upgrades are organized into five categories, each with different costs and effects. Prioritizing the right upgrades at the right time accelerates your growth.": "升级分为五大类别，消耗与效果各不相同，合理规划升级顺序能加快发展速度。",
    "Villagers": "村民",
    "Wheat Fields": "麦田",
    "When to Prestige": "声望时机",
    "When you close the game, your civilization keeps producing. On your next visit you will be shown a summary of everything earned while away and can claim it all at once.": "关闭游戏后文明仍持续产出资源，再次上线可查看离线总收益并一键领取。",
    "When you discover an": "当你发现一个",
    "which rarity": "哪个稀有度",
    "Workshops": "工坊",
    "Workshops convert raw resources into Metal. Needed for mid-to-late game upgrades and infrastructure.": "工坊可将原材料转化为金属，用于游戏中期至后期的升级和基础设施建设。",
    "you find are unchanged — this only affects which artifact of that rarity you receive.": "你找到的物品保持不变——这仅影响你获得的稀有度物品。",
    "Your main gameplay area. Starts at 3x3 and can expand up to 6x6 through upgrades. All tile types can be placed and merged here.": "主游玩区域，初始3×3，升级后最大扩容至6×6，所有地块均可在此摆放、合成。",
    "Your max Mana is 100 per Magic Crystal you own. Crystals are rare and persist across resets. Invest in Mana capacity upgrades and use spells strategically rather than spending Mana the moment you earn it.": "每颗魔法水晶提供100魔力上限，水晶稀有且跨重置保留。优先提升魔力上限，合理规划法术释放，不要魔力一到手就全部消耗。",
    "(coming soon)": "(敬请期待)",
    "Community": "社区",
    "Available on": "可在",
    ", and Android": ", 和安卓",
    "iOS": "iOS",
    "Web": "网页",
    "Inspired by classic merge and idle games, MergeCiv layers on rich progression\n                systems — from upgrading your resource production and unlocking underground\n                stockpiles, to mastering arcane magic and ascending to entirely new dimensions\n                of play. Whether you enjoy active strategy or prefer to let your civilization\n                grow while you're away, MergeCiv adapts to your playstyle with robust offline\n                earnings and automation upgrades.": "受经典合并与闲置类游戏启发，MergeCiv融入了丰富的升级系统——从提升资源产量、解锁地下储备，到掌握神秘魔法，逐步进入全新的游戏维度。无论你喜欢主动策略，还是更愿意在你不在时让文明自然发展，MergeCiv都能通过强大的离线收益和自动化升级，灵活适应你的游戏风格。",
    "Drag matching tiles together to combine them into higher-tier versions.\n                    Higher-tier tiles produce more resources per second. Your grid starts small\n                    but expands as you progress, giving you more room to merge and grow.": "将匹配的方块拖拽合并，以组合成更高级别的版本。更高阶的方块每秒能生成更多资源。你的网格起初较小，但随着游戏推进会不断扩展，为你提供更多的合并和成长空间。",
    "MergeCiv is a strategic idle game that blends tile-merging puzzles with deep\n                civilization-building mechanics. Start with a small settlement, merge tiles to\n                harvest resources, recruit villagers, and build your way toward a thriving empire.\n                Every decision you make shapes the growth and prosperity of your civilization.": "《MergeCiv》是一款融合了方块合并解谜与深度文明建设机制的战略休闲游戏。从一个小型定居点开始，通过合并方块来采集资源、招募村民，并逐步建立繁荣的帝国。你所做的每一个决定都将影响文明的成长与兴盛。",
    "MergeCiv is an indie game built by a solo developer passionate about strategy games,\n                incremental mechanics, and polished user experiences. The game is actively developed\n                with regular updates, new features, and balance improvements driven by community\n                feedback.": "MergeCiv 是一款由独立开发者打造的独立游戏，开发者对策略类游戏、渐进式玩法以及精良的用户体验充满热情。游戏持续开发中，定期更新新功能，并根据社区反馈进行平衡性优化。",
    "Recruit villagers to boost resource production, build stockpiles to increase\n                    your storage limits, and construct libraries to generate Knowledge. Unlock\n                    underground layers for additional stockpiling space, and raise a Citadel\n                    to access advanced research and culture upgrades.": "招募村民以提升资源产量，建立储备以增加存储容量，并建造图书馆以获取知识。解锁地下层以获得额外的储存空间，并建造要塞以获取高级研究和文化升级。",
    "When your civilization reaches its peak, prestige to earn Culture Points\n                    and permanent empire upgrades. Ascend beyond prestige to unlock the Magic\n                    system, powerful Artifacts, and Rituals that reshape the very rules of the\n                    game. Each layer of progression multiplies your power for the next run.": "当你的文明达到巅峰时，声望将为你赢得文化点数，并永久提升帝国等级。超越声望，解锁魔法系统、强大的神器和仪式，彻底改变游戏规则。每一层进阶都将使你在下一次运行中获得更强大的力量。",
    "— Combine tiles to unlock higher tiers with exponentially better production.": "— 合成地块解锁高阶形态，产出呈指数级大幅提升",
    "— Earn resources even while offline — your civilization never sleeps.": "— 离线也能持续获取资源，文明发展永不间断",
    "— Harness mana, cast spells, and perform rituals for powerful bonuses.": "— 掌控魔力、释放法术、举行仪式，获取强力增益",
    "— Play on web, iOS, or Android with cloud save sync across devices.": "— 支持网页、苹果、安卓端游玩，云端存档跨设备同步",
    "— Prestige, Ascension, Artifacts, and Rituals across multiple reset layers.": "— 多层重置体系：转生、飞升、神器、仪式一应俱全",
    "— Surface, underground, and citadel layers each with unique mechanics.": "— 地表、地下、堡垒三层网格，各有专属玩法机制",
    "1. Merge Tiles": "1. 合成地块",
    "2. Harvest Resources": "2. 收集资源",
    "3. Build & Expand": "3. 建造扩张",
    "4. Prestige & Ascend": "4. 转生飞升",
    "About the Developer": "开发者介绍",
    "Cross-Platform": "全平台互通",
    "Deep Progression": "深度养成体系",
    "How to Play": "游玩教程",
    "Idle Civilization Strategy Game": "放置文明策略游戏",
    "Idle Earnings": "离线收益",
    "Join our Discord Server": "加入Discord社群",
    "Join our growing community of MergeCiv players! Share strategies, report bugs,\n                suggest features, and connect with other civilization builders.": "加入持续壮大的《MergeCiv》玩家社区！分享攻略、反馈BUG、提议新功能，结识其他文明建造爱好者。",
    "Key Features": "核心特色",
    "MergeCiv is completely free to play with optional rewarded ads and supporter packs.\n                There are no paywalls — every feature can be earned through gameplay alone.": "《MergeCiv》完全免费游玩，设有可选奖励广告与赞助礼包。无付费锁机制，全部内容均可通过游戏内游玩解锁。",
    "Multi-Layer Grids": "多层网格系统",
    "Tile Merging": "地块合成机制",
    "What is MergeCiv?": "《MergeCiv》游戏简介",
    "Your tiles automatically generate Food, Wood, Ore, and Gold over time.\n                    These resources fuel everything — spawning villagers, building structures,\n                    purchasing upgrades, and expanding your territory.": "地块会随时间自动产出食物、木材、矿石与金币。所有发展都依托这些资源：招募村民、建造建筑、购买升级、扩张领地。",
    "Your 3x3 starting grid fills up fast. Saving resources for Grid Expansion upgrades should be your top priority. A 4x4 grid more than doubles your working space, and 5x5 changes the game entirely. More space means more tiles, more merges, and less chance of gridlock.": "你的3x3起始网格会很快填满。为网格扩展升级节省资源应是你的首要任务。4x4的网格将工作空间扩大一倍以上，而5x5则彻底改变了游戏格局。更多空间意味着更多方块、更多合并机会，以及更低的卡顿风险。",
    "Ore Deposits unlock mid-tier upgrades that gate most of your progression. Many players over-invest in Food and Wood early on, then hit a wall when they need Ore. Start spawning Ore tiles as soon as the upgrade becomes available, even if it feels slow at first.": "矿石资源可解锁中等进阶升级，而这些升级会限制你的大部分进度。许多玩家在早期过度投资食物和木材，之后当需要矿石时却遇到瓶颈。一旦升级可用，就应立即开始生成矿石方块，即使一开始感觉进展缓慢也应如此。",
    "Not all Artifacts are created equal. Golem (1.2x resource generation per level) and Golden Compass (better Scout spawns) have outsized impact. When you unlock higher Detect Magic tiers, the chance of finding Rare+ Artifacts increases. Focus on leveling your best Artifacts rather than spreading upgrades across all of them.": "并非所有神器的生成效果都相同。例如，哥布林（每级1.2倍资源生成）和金罗盘（更优的侦察兵生成）的影响尤为显著。当你解锁更高等级的探测魔法时，发现稀有+神器的概率也会随之提高。建议优先提升你最强神器的等级，而非将升级分散到所有神器上。",
    "Nine Rituals are available, and each Crystal can only be assigned to one. If you play actively, Space Expansion (bigger grid) and Quality Scouting (higher-tier spawns) are powerful. If you prefer idle play, Apprentice Persistence and Scout Persistence keep automation running across resets. Education Persistence preserves upgrade progress.": "共有九种仪式可供选择，每块水晶只能分配给一种。如果你喜欢主动游玩，空间扩展（更大的网格）和品质侦察（更高等级的生成点）效果显著。如果你偏好闲置玩法，学徒耐力和侦察耐力可确保重置后自动运行。教育耐力则能保留升级进度。",
    "If your storage is full, every resource your tiles produce is wasted. Build Stockpiles early and merge them aggressively. A single high-tier Stockpile is worth more than several low-tier ones taking up grid space. Watch the resource bars at the top of the screen — if they are full, you are losing production.": "如果存储空间已满，你所有瓷砖产生的资源都会被浪费。请尽早建立库存，并积极合并它们。一个高等级的库存比多个低等级库存占用网格空间更有价值。注意屏幕顶部的资源条——如果它们已满，说明你的生产正在减少。",
    "Fission costs 2,000 Mana but is the most impactful spell. Splitting a high-tier tile creates two copies of one tier lower, essentially doubling your high-value tiles. Magical Upheaval (100 Mana) is cheaper but should be reserved for emergencies when your grid is truly locked.": "裂变消耗2000点法力，但是最具影响力的法术。将一个高等级格子分裂成两个低一级的副本，相当于将你宝贵的高价值格子数量翻倍。魔法动荡（100点法力）成本较低，但应仅在网格完全被锁定时才用于紧急情况。",
    "Culture earned from Prestige scales with your Villager population, and higher-tier Villagers contribute exponentially more. Do not Prestige the moment it becomes available — push until growth noticeably stalls. A single well-timed Prestige can earn more Culture than five early ones combined.": "通过村民人口获得的声望值（Prestige）文化，高级别村民的贡献呈指数级增长。不要在声望值可用时立即提升——应持续推动直到增长明显停滞。一次恰到好处的声望提升，其带来的文化收益可能超过五次早期提升的总和。",
    "Ascension is a deeper reset than Prestige. It resets Culture but unlocks the Magic system, Artifacts, and the Citadel. Ascend when additional Prestiges are yielding diminishing returns. The power spike from your first Ascension is enormous — Magic and Artifacts multiply everything.": "转生比荣耀更深层次的重置。它会重置文化，但会解锁魔法系统、神器以及要塞。当额外的荣耀带来的回报逐渐递减时，就该进行转生了。首次转生带来的力量爆发极为巨大——魔法和神器将一切倍增。",
    "Reinvestment multiplies all production by 1.1x per level. This might sound modest, but it stacks multiplicatively — ten levels means a 2.6x multiplier on everything. Prioritize Reinvestment whenever you have spare Gold. Taxes and Secure Vaults help sustain your Gold income to fund more levels.": "再投资会使每级生产量提升1.1倍。这听起来或许不太可观，但其效果是累积叠加的——十级之后，所有产出将乘以2.6倍。当你有剩余金币时，应优先使用再投资。税收和安全宝箱有助于维持你的金币收入，从而支持更多等级的建设。",
    "Rewarded ad boosts provide a significant resource injection with a 5-minute cooldown. On mobile, these are video ads; on web, they use the H5 Games placement. Time your boosts for maximum impact — use them when your storage has room and your multipliers are highest.": "奖励广告提升可提供大量资源注入，冷却时间为5分钟。在移动端，这些是视频广告；在网页端，则使用H5游戏投放方式。合理安排提升时机以获得最大效果——当你的存储空间充足且倍率最高时，再进行使用。",
    "The basic Apprentice merges anything it can, which sometimes disrupts your plans. Upgrade to Smart Apprentice as soon as possible — it protects tiles you are actively working with. Later, Space Conscious mode prevents the Apprentice from merging Stockpiles, keeping your grid focused on production tiles.": "基础学徒会尽可能地合并所有物品，这有时会打乱你的计划。请尽快升级为智能学徒——它能保护你正在操作的方块。之后，空间意识模式可防止学徒合并库存堆叠，让你的网格专注于生产方块。",
    "The Citadel costs 100 million Ore and 10,000 Mana — a steep price, but it unlocks Libraries (Research), Theatres (Culture capacity), and most importantly, Ritual slots for Magic Crystals. Every Crystal assigned to a Ritual provides a permanent bonus that persists through all future resets.": "要建造这座要塞需要1亿矿石和1万法力值——价格不菲，但它能解锁图书馆（研究）、剧院（文化容量），最重要的是，还能为魔法水晶提供仪式槽位。每个分配给仪式的水晶都会提供永久加成，该加成在所有后续重置中持续有效。",
    "Traditions provide passive resource income that works from the very start of each new run. This dramatically speeds up your early game after Prestige, letting you reach higher tiers faster each cycle. Cultural Renown (50% more Prestige rewards) is powerful too, but Traditions compound over many runs.": "传统能提供被动资源收入，从每次新游戏开始就持续发挥作用。这极大地加快了你在声望提升后的早期游戏进度，使你每轮更快地达到更高等级。文化声望（比声望奖励多50%）也很强大，但传统会在多个游戏中不断累积。",
    "Villagers seem like just another tile, but your population is the primary driver of Prestige rewards. Higher-tier Villagers contribute exponentially more — a Tier 5 Villager counts as 16 population while a Tier 1 counts as 1. Always merge Villagers when possible and keep spawning them.": "村民看起来就像普通的方块一样，但你的人口是获取声望奖励的主要因素。更高等级的村民贡献的声望奖励会呈指数级增长——一个5级村民相当于16个普通村民，而一级村民仅相当于1个。尽可能合并村民，并持续生成更多村民。",
    "By late game your resource production will vastly outpace surface Stockpile capacity. The Underground layer is exclusively for Stockpiles and provides massive storage. Merge Underground Stockpiles aggressively — a single high-tier underground Stockpile can hold more than your entire surface grid.": "到了后期，你的资源产量将远远超过地表储藏容量。地下层专用于储存资源，提供巨大的存储空间。请积极合并地下储藏点——单个高阶地下储藏点的容量甚至可以超过整个地表网格的总和。",
    "Advanced tactics to accelerate your civilization": "加速文明发展的高阶技巧",
    "Already know the basics? These strategies will help you progress faster, prestige more efficiently, and make the most of every game system. Tips are organized from early-game through late-game and endgame.": "已经掌握基础玩法？这些攻略能让你发育提速、转生收益最大化，充分利用全部游戏机制。攻略按前期、中期、后期、终局划分。",
    "Always check if any merges are available before spawning a new tile. Spawning into a nearly-full grid risks a deadlock where no merges are possible. Keep at least one or two empty spaces as a buffer.": "刷新地块前先检查可合成地块。格子快满时刷新容易卡死无地块可合，至少预留一到两个空位作为缓冲。",
    "Build the Citadel as Soon as You Can Afford It": "经济达标后尽快建造堡垒",
    "Choose Rituals That Match Your Playstyle": "选择契合自身玩法的仪式",
    "Claim Offline Earnings Regularly": "定期领取离线收益",
    "Do Not Neglect Villagers": "切勿忽视村民发展",
    "Early Game — Getting Started Right": "前期——平稳起步",
    "Endgame — Citadel and Rituals": "终局——堡垒与仪式体系",
    "General Efficiency Tips": "通用高效发育技巧",
    "Gold Upgrades Are Multiplicative": "金币升级拥有倍率加成",
    "Invest Culture in Traditions First": "优先消耗文化点数解锁传统",
    "Late Game — Magic and Ascension": "后期——魔法与飞升体系",
    "Merge Before You Spawn": "先合成，再刷新地块",
    "Mid Game — Prestige Strategy": "中期——转生规划思路",
    "Never Let Storage Cap Out": "切勿让资源存满溢出",
    "Offline earnings accumulate while you are away, but they cap out based on your storage limits. If your storage is full when you return, you missed out on potential production. Check in periodically or expand storage before long breaks.": "离线收益会持续累积，但存在存储上限。上线时仓库已满会损失大量产出。长时间离线前记得定期上线收资源或扩容仓库。",
    "Plan Your Grid Layout": "规划棋盘布局",
    "Prioritize Grid Expansion": "优先解锁网格扩容",
    "Save Mana for Fission": "留存魔力用于裂变法术",
    "Target High-Value Artifacts": "优先获取高收益神器",
    "Tiles the Scout spawns are attracted to neighboring tiles of the same type. Use this to your advantage by clustering similar tiles together. This creates natural merge chains and reduces the amount of manual rearranging you need to do.": "侦察兵倾向在同类地块旁刷新，可主动将同类地块集中摆放，形成连锁合成链，减少手动整理操作。",
    "Time Your Prestiges": "把控转生时机",
    "Underground Storage Is Not Optional": "地下仓库是必备设施",
    "Unlock Ore Before You Stall": "发展停滞前解锁矿石产出",
    "Use the Apprentice Wisely": "合理运用学徒自动合成功能",
    "Watch for the Boost Button": "留意增益领取按钮",
    "When Growth Flattens": "发展进入瓶颈期时",
    "Full detail will remain on until you change it.": "完整详情将一直保留，直到您更改为止。",
    "Balanced rendering will remain on until you change it.": "平衡渲染将一直保持，直到您更改为止。",
    "— every purchase grows your Founder bonuses": "— 每一次购买都会提升创始者加成",
    "$1 each — banked for the Boost menu anytime.": "1美元兑换增益时长，可在增益面板随时取用",
    "bonus": "加成效果",
    "Bonus Boosts": "增益道具",
    "Chest": "宝箱",
    "Crowns": "王冠",
    "Crowns and levels your Founder bonuses.": "王冠可提升创始者加成等级",
    "Every purchase earns": "任意消费均可获取",
    "Exclusive Founder Badge": "专属创始者徽章",
    "Feathers": "羽饰",
    "Food, Wood, Ore, Gold": "食物、木材、矿石、金币",
    "Founder access": "创始者专属权限",
    "Founder rewards": "创始者福利",
    "Founder's Pack unlocks shop purchases.": "购买创始礼包后解锁商城全部购买项",
    "Founders": "创始者",
    "Get Founder's Pack — $14.99": "入手创始礼包——售价14.99美元",
    "Handful": "小额物资包",
    "Loading Founder's Pack…": "正在加载创始礼包……",
    "Loading shop…": "正在加载商城……",
    "No Ads": "移除广告",
    "Permanent perks": "永久特权",
    "Permanent perks and supplies for your civilization.": "为你的文明提供永久特权与物资",
    "Preview tiers": "等级预览",
    "Royal bundles": "皇家礼包",
    "Royal Hoard": "皇家宝库",
    "Satchel": "中型行囊",
    "Stock up whenever your next upgrade calls.": "升级物资短缺时随时囤货",
    "Support MergeCiv & unlock permanent perks": "支持《MergeCiv》并解锁永久特权",
    "Unlocks Royal bundles and Crown rewards.": "解锁皇家礼包与王冠奖励",
    "Wagon": "大型货车",
    "worldwide — each adds +1s boost": "全球通用，每份额外增加1秒增益时长",
    "Highest Tile (T": "最高级地块 (T",
    "First Resettlement!": "第一次重新安置！",
    "From Highest Tile": "来自最高地块",
    "Loading empire…": "帝国加载中...",
    "Population (": "人口 (",
    "Your first society enters the history books. Capture the moment?": "你的第一个社会将载入史册。捕捉这个瞬间？",
    "Population Sufficient": "人口充足",
    "joined": "已加入",
    "Chieftain": "酋长",
    "Mentor of": "导师 ",
    "qualified": "合格",
    "Recruits start counting once they Resettle after a few days of real play.": "招募人员在实际游戏几天后重新安置后开始计数。",
    "Chance to find Stockpiles when worked": "工作时有机会找到库存",
    "Contributing": "贡献",
    "Upgrade": "升级",
    "Upgrading…": "升级中...",
    "weight to Stockpile odds": "重量与库存比例",
    "Hover Scout to see combined odds": "悬停侦察看到合并的几率",
    "Off": "关闭",
    "Apple": "苹果",
    "A much larger hawk that crosses the board more slowly": "一只体型更大的鹰，移动速度较慢",
    "Big hawk": "大鹰",
    "Set the interface lighting.": "设置界面照明。",
    "Roster:": "名单：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+N sec": "+N 秒",
    "mergeciv.io": "mergeciv.io",
    "of": "/",
    "0f82e0fe-48f7-425d-9e1f-e966b6f8f6fc": "0f82e0fe-48f7-425d-9e1f-e966b6f8f6fc",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "Gityx": "Gityx",
    "G8hh": "G8hh",
    "--:--": "--:--",
    "(+": "(+",
    "%)": "%)",
    "×": "×",
    "🍎": "🍎",
    "🪨": "🪨",
    "🪵": "🪵",
    "x)": "x)",
    "▶": "▶",
    "⬥": "⬥",
    "→": "→",
    "▼": "▼",
    "x ·": "x ·",
    "⚠️": "⚠️",
    "·": "·",
    "▾": "▾",
    "🏛️": "🏛️",
    "": "",
    "": "",
    "#7c85cccc": "#7c85cccc",
    "•": "•",
    "—": "—",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    ">>": ">>",
    ">": ">",
    "<<": "<<",
    "<": "<",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'IX': 'IX',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树地块: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Increases grid size to ": "增加网格尺寸到 ",
    "Base (Pop  ": "基础 (Pop  ",
    "Max Charges: ": "最大充能: ",
    "Scouts Tiers ": "侦查层级 ",
    "Reinvestment (": "再投资 (",
    "Capped at ": "上限是 ",
    "Highest Tile × ": "最高地块 × ",
    "Ascend ": "转生 ",
    "Golem Artifact ": "魔像神器 ",
    "Ascended Upgrades ": "转生的升级 ",
    "Confirm Ascend ": "确认转生 ",
    "Magic Crystals": "魔法水晶",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    "Wheat Field": "麦田",
    " per Level)": " 每级)",
    "Forest": "森林",
    "Ore Deposit": "矿床",
    "Mine": "矿井",
    "Stockpile": "仓库",
    "Workshop": "作坊",
    " Gold/population/level.": " 黄金/人口/每级.",
    " Food/Wood/Ore Gen per level.": " 食物/木头/矿石 生成 每级.",
    " Culture Gain level.": " 文化增益 每级.",
    " Gold/s per level.": " 黄金/秒 每级.",
    " Mana/s per level.": " 法力/秒 每级.",
    " Food/s per level.": " 食物/秒 每级.",
    " Wood/s per level.": " 木头/秒 每级.",
    " Ore/s per level.": " 矿石/秒 每级.",
    " Culture Gain per level.": " 文化增益 每级.",
    " Food Capacity per level.": " 食物容量 每级.",
    " Gold Capacity per level.": " 黄金容量 每级.",
    " Ore Capacity per level.": " 矿石容量 每级.",
    " Wood Capacity per level.": " 木头容量 每级.",
    " culture / min per level.": " 文化 / 分钟 每级.",
    " Mana/Population per level.": " 法力/人口 每级.",
    " Requirement for Crystal per level.": " 水晶要求 每级.",
    " Mana Gen (Global) per level.": " 法力生成 (全局) 每级.",
    " Base Cost": " 基础成本",
    " Mana/s": " 法力/秒",
    "x Culture": "x 文化",
    "x Food Cap": "x 食物上限",
    "x Ore Cap": "x 矿石上限",
    "x Wood Cap": "x 木头上限",
    "x Gold Cap": "x 黄金上限",
    "x Mana Gen": "x 法力生成",
    "x Res. Gen": "x 资源生成",
    " Gold/Pop": " 黄金/人口",
    " culture / min": " 文化 / 分钟",
    " Mana / Pop": " 法力 / 人口",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^最大(.+)$/,
    /^当前(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^x([\d\.]+)\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+)k$/,
    /^\+([\d\.]+)k$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)×$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+)t$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\#([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x([\d\.,]+).$/,
    /^([\d\.,]+)\-([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\(\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\/ ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^\+(.+)\% Wood\/Food\/Ore · \+(.+)\% Mana · \+(.+)\% Gold Cap$/, '+$1% 木头/食物/矿石 · +$2% 法力 · +$3% 黄金上限'],
    [/^Current: (.+) Mana Gen Multiplier$/, '当前: $1 法力生成乘数'],
    [/^Current: (.+) Base Cap$/, '当前: $1 基础上限'],
    [/^Current: (.+) Resource Yield$/, '当前: $1 资源产出'],
    [/^Current: (.+) Mana Gen$/, '当前: $1 法力生成'],
    [/^Current: (.+) Scout Click Cooldown$/, '当前: $1 侦查点击冷却'],
    [/^Current: (.+) Storage$/, '当前: $1 存储'],
    [/^Current: (.+) Bonus per Tier$/, '当前: $1 加成每个层级'],
    [/^Current: (.+) Tier$/, '当前: $1 层级'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^\(Cost x([\d\.]+), Mana: ([\d\.]+)\)$/, '(成本 x$1, 法力: $2)'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)x Spell Yield \& Cost$/, '$1x 法术产出 & 成本'],
    [/^([\d\.]+)x Gold from Tribute \(Resettling\) per level.$/, '$1x 每级献祭（重新安置）获得的黄金。'],
    [/^([\d\.]+)x Tribute$/, '$1x 献祭'],
    [/^([\d\.]+)x Scout Speed$/, '$1x 搜寻速度'],
    [/^\+([\d\.]+) Grid Width$/, '+$1 网格宽度'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+) Grid Size$/, '+$1 网格尺寸'],
    [/^\+([\d\.]+) Wood\/s$/, '+$1 木头/秒'],
    [/^\+([\d\.]+) Gold\/s$/, '+$1 黄金/秒'],
    [/^\+([\d\.]+) Food\/s$/, '+$1 食物/秒'],
    [/^\+([\d\.]+) Ore\/s$/, '+$1 矿石/秒'],
    [/^\+([\d\.]+) Wood\/s$/, '+$1 木头/秒'],
    [/^\+([\d\.]+)\% Culture Gain$/, '+$1% 文化增益'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Culture$/, '+$1% 文化'],
    [/^\+([\d\.]+)\% Scaling$/, '+$1% 扩张'],
    [/^Next level · \+([\d\.]+)\%$/, '下一级 · +$1%'],
    [/^Current: \+([\d\.]+)\% Bonus per Tier$/, '当前: +$1% 奖励每层级'],
    [/^Current: \+([\d\.]+)\% Speed at Rest$/, '当前: +$1% 休息速度'],
    [/^Current: \-([\d\.]+)\% Interval$/, '当前: -$1% 间隔时间'],
    [/^Current: \-([\d\.]+)\% Cooldown$/, '当前: -$1% 冷却时间'],
    [/^Current: \+([\d\.]+) Gold Cap$/, '当前: +$1 黄金上限'],
    [/^Current: \+([\d\.]+) Gold$/, '当前: +$1 黄金'],
    [/^Current: \+([\d\.]+) Gold \/ sec per Population$/, '当前: +$1 黄金 / 每秒每人口'],
    [/^Tier Bonus \(\+([\d\.]+)\%\)$/, '层级加成 (+$1%)'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)h ([\d\.]+)s$/, '$1小时 $2秒'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)m ([\d\.]+)s ago$/, '$1分钟 $2秒 前'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+)x Speed$/, '$1x 速度'],
    [/^([\d\.,]+) resettlement$/, '$1 重新安置'],
    [/^([\d\.,]+) hour$/, '$1 小时'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+) feathers$/, '$1 羽毛'],
    [/^([\d\.,]+) feather$/, '$1 羽毛'],
    [/^([\d\.,]+) resettlements$/, '$1 重新安置'],
    [/^([\d\.,]+) Mana$/, '$1 法力'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Saved ([\d\.,]+)s ago$/, '保存于 $1秒 前'],
    [/^([\d\.,]+)x Storage Capacity$/, '$1x 存储容量'],
    [/^\+([\d\.,]+) Knowledge$/, '+$1 知识'],
    [/^\+([\d\.,]+) bird$/, '+$1 小鸟'],
    [/^\+([\d\.,]+) feather$/, '+$1 羽毛'],
    [/^\+([\d\.,]+) Feather$/, '+$1 羽毛'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^\−([\d\.,]+) min$/, '-$1 分钟'],
    [/^\-([\d\.,]+) elves$/, '-$1 精灵'],
    [/^\-(.+) Knowledge$/, '-$1 知识'],
    [/^Villager \(T([\d\.,]+)\)$/, '村民 (层级 $1)'],
    [/^Secure Vault \(L([\d\.,]+)\)$/, '安全金库 (等级 $1)'],
    [/^Stockyer \(L([\d\.,]+)\)$/, '仓库 (等级 $1)'],
    [/^Tier ([\d\.,]+) $/, '层级 $1 '],
    [/^Tier ([\d\.,]+) $/, '层级 $1 '],
    [/^Tier ([\d\.,]+) Library$/, '层级 $1 图书馆'],
    [/^Tier ([\d\.,]+) Citadel$/, '层级 $1 城堡'],
    [/^T([\d\.,]+) \- T([\d\.,]+) Upgrades$/, '$1 - T2 升级 '],
    [/^T([\d\.,]+) \– T([\d\.,]+) Upgrades$/, '$1 - T2 升级 '],
    [/^Population  ([\d\.,]+)$/, '人口 $1'],
    [/^Base ([\d\.,]+) \+$/, '基础 $1 +'],
    [/^Requires Mage Tower Lvl ([\d\.,]+)$/, '要求 法师塔 等级 $1'],
    [/^Last saved: ([\d\.,]+)s ago$/, '上次保存于: $1秒 前'],
    [/^Last saved: \-([\d\.,]+)s ago$/, '上次保存于: -$1秒 前'],
    [/^Tier ([\d\.,]+)\-$/, '层级 $1-'],
    [/^Current: ([\d\.,]+)$/, '当前: $1'],
    [/^MergeCiv ([\d\.,]+)$/, '合并文明 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) Mana$/, '成本：$1 法力'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();