// ==UserScript==
// @name         Vanya Online 简中汉化脚本
// @namespace    https://www.g8hh.com.cn/
// @version      0.0.1
// @description  网页游戏 Vanya Online (https://www.xxxxx.com/) 的简体中文汉化脚本。Simplified Chinese i18n script for web game Vanya Online.
// @author       好阳光的小锅巴 & 麦子
// @copyright    锅巴汉化
// @contributionUR    https://gityx.com/donate/intro.html
// @icon         https://vanyaonline.com/favicon.ico
// @license      MIT
// @include      *https://vanyaonline.com/*
// @grant        none
// @website      https://www.gityx.com/
// @updateURL    https://g8hh.com.cn/zh/tampermonkey/vanya-online-chs.user.js
// @downloadURL    https://g8hh.com.cn/zh/tampermonkey/vanya-online-chs.user.js
// ==/UserScript==
/**
 * ---------------------------
 * Time: 2025/11/14 13:48
 * Author: guoba
 * View: https://www.gityx.com/
 * ---------------------------
 */
//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "OR": "或",
    "and": "和",
    "Black Knight": "黑骑士",
    "Type": "类型",
    "Normal": "普通",
    "Non-PvP": "无PVP",
    "Login": "登录",
    "Items:": "物品:",
    "Close": "关闭",
    "CHOOSE YOUR STYLE": "选择你的风格",
    "SELECTED": "已选择",
    "The use of any unauthorized third-party programs, scripts, bots, or software designed to modify game data or automate gameplay is strictly forbidden. This includes, but is not limited to:": "使用任何未经授权的第三方程序、脚本、机器人或软件来修改游戏数据或自动游戏是严格禁止的。这包括但不限于：",
    "Accessing Developer Tools (DevTools):Attempting to open or interact with the browser's developer console (e.g., via F12, Ctrl+Shift+I, or right-click inspection) to inspect server communications will result in an immediate and permanent ban from Vanya Online.": "访问开发者工具（DevTools）：试图打开或与浏览器的开发者控制台交互（例如，通过F12， Ctrl+Shift+I，或右键检查）来检查服务器通信将导致立即永久禁止玩 万尼亚在线。",
    "To significantly boost the initial flow and development for all players, we are implementing a Daily Experience Boost feature.\nEvery player will receive 60 minutes of a 50% Experience Boost in the Hunting zones, daily, this bonus is designed to fast track your initial char progress and make early progression much smoother and more rewarding.": "为了显著促进所有玩家的初始流程和开发，我们正在执行每日经验提升功能。\n每个玩家每天都会在狩猎区获得60分钟的50%经验提升，这种奖励旨在快速跟踪您的初始角色进度，并使早期进展更加顺畅和更有回报。",
    "World": "世界",
    "World List": "世界列表",
    "Worlds:": "世界:",
    "Worlds Status": "世界状态",
    "1. Account Usage and Conduct": "1. 帐户使用及行为",
    "1. Data Collection": "1. 数据收集",
    "2. Data Usage and Security": "2. 数据使用与安全",
    "2. Prohibited Software and Cheating": "2. 禁止使用的软件和作弊",
    "3. Account Termination": "3. 帐户终止",
    "3. Third-Party Services": "3. 第三方服务",
    "A Demona Vosz Letter": "一封迪蒙娜·沃斯的信",
    "Account Data: Username and secure password hash.": "账号数据：用户名和安全密码哈希值。",
    "By continuing to play, you consent to the collection and use of information as outlined in this policy.": "如果您继续玩游戏，即表示您同意本政策中所述的信息收集和使用。",
    "by taking them down!": "干掉他们！",
    "Clockwork Raven Studios": "Clockwork Raven工作室",
    "Composer: Pablo de Mello Heredia": "作曲家：Pablo de Mello Heredia",
    "Create Account": "创建账户",
    "Credits & Licensing": "信用和许可",
    "Customer Support": "客户支持",
    "Daily Experience Boost": "每日经验提升",
    "Demona Vosz": "恶魔娜·沃斯",
    "Enter Vanya": "进入万尼亚",
    "False Detection Fix": "错误检测修复",
    "fully licensed content": "完全授权内容",
    "Gameplay Data: Inventory, gold, hunt status, and last activity timestamp.": "玩法数据：库存、金币、狩猎状态和最后一次活动时间戳。",
    "Harrassing or spamming other players.": "骚扰或骚扰其他玩家。",
    "I agree to the": "我同意",
    "Icons & Future Collectible Cards:": "图标和未来收集卡：",
    "Lakechant, PK Status, and Echos Everywhere": "莱克禅，PK状态和共鸣 无处不在",
    "Latest News": "最新消息",
    "Macro programs or any form of client-side automation.": "宏程序或任何形式的客户端自动化。",
    "Muse Archer": "缪斯射手",
    "New Hunter": "新猎人",
    "Privacy Policy": "隐私政策",
    "Security Data: IP address, recorded during logins and specifically when suspicious activity (such as the detection of DevTools access) is logged to the server.": "安全数据：IP地址，在登录过程中记录，特别是当可疑活动（如检测到DevTools访问）记录到服务器时。",
    "Security logging of suspicious activities (like attempts to open DevTools) is performed to protect the integrity of the game and its economy.": "执行可疑活动（如试图打开DevTools）的安全日志记录以保护游戏及其经济的完整性。",
    "Sharing personal information about yourself or others.": "分享自己或他人的个人信息。",
    "Sprites, Characters, Images, Sound & Music:": "精灵、角色、图像、声音和音乐：",
    "Terms of Use": "使用条款",
    "Thank you for playing Vanya!": "谢谢你玩 万尼亚！",
    "Today's Boosted Boss:": "今日提升的Boss：",
    "Undead Necro": "不死的死灵法师",
    "Using offensive, vulgar, or inappropriate language (swearing).": "使用冒犯性的、粗俗的或不恰当的语言（咒骂）。",
    "Vanya is built with original and ": "万尼亚是建立与原始和",
    "Vanya News": "万尼亚新闻",
    "Vanya Online reserves the right to terminate your account access at any time, for any reason, particularly for violations of these Terms of Use, without notice or liability.": "万雅在线保留在任何时候以任何理由终止您的帐户访问的权利，特别是在违反这些使用条款的情况下，恕不另行通知或承担责任。",
    "Privacy Policy": "隐私政策",
    "Terms of Use": "使用条款",
    "Vanya Server Upgrade": "万尼亚服务器升级",
    "Violations of this section will result in permanent account suspension without prior warning.": "违反此条款将导致永久封号，无需事先警告。",
    "Wabby Wabbo": "兔兔宝宝",
    "We collect minimal data necessary for core gameplay and security:": "我们收集核心玩法和安全性所需的最少数据：",
    "We do not currently integrate with third-party tracking or advertising services. If this changes, we will update this policy.": "我们目前没有整合第三方跟踪或广告服务。如果情况发生变化，我们将更新此政策。",
    "Worlds only divide player rankings, markets, guilds and enable or disable PvP.": "世界只划分玩家排名、市场、公会，并启用或禁用PvP。",
    "You are responsible for all activity conducted through your account. You agree to abide by the rules of conduct, which include, but are not limited to, refraining from:": "您对通过您的帐户进行的所有活动负责。您同意遵守行为规则，包括但不限于避免：",
    "Your data is used solely for the purpose of running Vanya Online and ensuring fair play. We do not sell or share your personal data with third parties, except as required by law.": "您的数据仅用于运行万尼亚在线和确保公平竞争。除法律规定外，我们不会向第三方出售或分享您的个人资料。",
    "Your Hunts Are Now Persistent": "你的狩猎现在是持续性的",
    "Account Created!": "账号已创建！",
    "Your Vanya account has been successfully created. You can now log in!": "您的 万尼亚 帐户已成功创建。您现在可以登录了！",
    "Before you begin your journey, confirm your email to secure your account. Click below to receive the activation link.": "在开始您的旅程之前，请确认您的电子邮件以确保您的帐户安全。点击下面接收激活链接。",
    "Got It (Next Step)": "明白了（下一步）",
    "Send Activation Email": "发送验证邮件",
    "Skip verification (Not recommended)": "跳过验证 (不推荐)",
    "Vanya is only available in English": "万尼亚 只有英文版本",
    "Waiting for confirmation...": "等待确认...",
    "Sending...": "发送中...",
    "Error sending email.": "发送邮件出错。",
    "Please wait before requesting another email.": "请稍候才能再请求另一封邮件。",
    "Sending activation email...": "正在发送验证邮件...",
    "Magic": "魔法",
    "Level Exp": "等级经验",
    "Player Skills": "玩家技能",
    "Profile": "个人资料",
    "Progress": "进度",
    "Life": "生命",
    "Inventory": "库存",
    "HELMET": "头盔",
    "GLOVES": "手套",
    "Fishing": "钓鱼",
    "RING": "戒指",
    "SHIELD": "盾牌",
    "Stamina": "耐力",
    "Support": "支持",
    "SWORD": "剑",
    "Sword": "剑",
    "Total Skills Bonus": "总技能加成",
    "VANYA": "万尼亚",
    "Defense": "防御",
    "BOW": "弓",
    "Bow": "弓",
    "BOOTS": "靴子",
    "Base + Item": "基础 + 物品",
    "WEAPON": "武器",
    "Your backpack is empty.": "你的背包是空的。",
    "Rankings": "排行",
    "Pub": "酒馆",
    "Your": "你的",
    "Your story begins in the": "你的故事开始于",
    "⟁ Vault": "⟁ 金库",
    "⛯ Abyss Boss": "⛯ 深渊Boss",
    "⛬ Dark Market": "⛬ 黑市",
    "⛨ Idle Hunt": "⛨ 放置狩猎",
    "⟊ Guild Hall": "⟊ 公会大厅",
    "⟒ Community": "⟒ 社区",
    "⟡ Ranking": "⟡ 排行榜",
    "⟢ Logout": "⟢ 登出",
    "⧫ The Pub": "⧫ 酒馆",
    "⟣ My House": "⟣ 我的家",
    "YOU DIED": "你挂了",
    "ATTACK": "攻击",
    "ATTACK (Cooldown:": "攻击 (冷却:",
    "Gold.": "金币.",
    "Player Status": "玩家状态",
    "XP and": "经验值和",
    "Your Life:": "你的生命值:",
    "Target Life:": "目标生命值:",
    "ARMOR": "盔甲",
    "AMULET": "护身符",
    "Actions": "动作",
    "is your personal space and a retreat between hunts. Train with your private dummy, switch outfits, and display your favorite gear and Hunting Trophies. It’s a place to show off your progress.": "是你的私人空间和狩猎间隙的休息场所。与你的私人假人训练，交换时装，并展示你最喜欢的装备和狩猎奖杯。这是一个展示你进度的地方。",
    "Die": "死亡",
    "Back to Home": "返回首页",
    "World Drakmor": "世界 德拉克莫尔",
    "[Noctra]": "[诺克特拉]",
    "[Drakmor]": "[德拉克莫尔]",
    "HUNT STATUS": "狩猎状态",
    "STOP HUNT & CLAIM LOOT": "停止狩猎 & 领取战利品",
    "⚠ Maximum hunt duration is": "⚠ 最大狩猎持续时间为",
    "ECHO": "共鸣",
    "is the social heart of Vanya. This is where your Stamina and Life regenerates over time. Use the dedicated area here to train your skills (which consume Stamina) and increase your skill points.": "是万尼亚的社交中心。这是你的耐力和生命随着时间恢复的地方。使用这里的专用区域来训练你的技能（消耗耐力）和增加你的技能点。",
    "is where true challenge lives. Players from across the world fight together against colossal bosses. Every strike counts, but only the final hit grants a chance at rare loot. Each battle consumes Stamina.": "才是真正的挑战所在。来自世界各地的玩家一起对抗巨大的boss。每次攻击都有价值，但只有最后一次命中才有机会获得稀有战利品。每场战斗都消耗耐力。",
    "Hunt": "狩猎",
    "Abyss Boss": "深渊Boss",
    "House": "房屋",
    "Forge": "锻造",
    "6. Rankings": "6. 排行榜",
    "5. The Pub (Skills & Rest)": "5. 酒馆 (技能 & 休息)",
    "4. The Updex & Forge": "4. Updex & 锻造",
    "3. Housing & Trophies": "3. 房屋 & 奖杯",
    ". In": ". 在",
    "1. The Hunt": "1. 狩猎",
    "2. Abyss Boss & Stamina": "2. 深渊Boss & 耐力",
    "no skill caps": "无技能上限",
    "no level limits": "无等级上限",
    "lets you merge": "让你合并",
    "no account resets": "无账号重置",
    "Equipment": "装备",
    "Equipped Slots & Bonuses": "装备槽 & 加成",
    "Shadow Book": "暗影之书",
    "Initiating PvP Battle...": "初始化PvP战斗...",
    "Service Unavailable": "服务不可用",
    "The server is temporarily busy, try again later!": "服务器暂时繁忙，请稍后再试！",
    "You have been hunting for": "你已狩猎了",
    "You must loot before time runs out.": "你必须在时间耗尽之前掠夺一切。",
    ", and": ", 和",
    ", progress is endless, your strength only stops where your will does. Every moment, every choice, every fight leaves a mark that never fades.": "进步是无止境的，你的力量只止于你的意志。每一刻，每一次选择，每一次战斗都会留下永不褪色的印记。",
    ". Each level and skill trained pushes you closer to legend.": "。每一个级别和技能训练推动你更接近传奇。",
    ". Here, your character fights automatically. You’ll earn Gold, Experience, and loot as time passes. The Hunt doesn’t consume Stamina, meaning you can always keep progressing.": "。在这里，你的角色会自动战斗。随着时间的推移，你将获得金币、经验和战利品。狩猎不消耗耐力，这意味着你可以一直前进。",
    "Everything you do echoes in the": "你做的每件事都会在",
    "for upgrades. Success enhances gear, failure destroys them. No shortcuts, just risk and reward.": "用于升级。成功可强化装备，失败可摧毁装备。没有捷径，只有风险和回报。",
    "is your collection. Sealing an item grants a Stamina bonus. The": "是你的收藏。封印物品可以获得耐力加成。",
    "Welcome, hunter. You’re about to step into a world with": "欢迎光临，猎人。你即将踏入一个",
    "Acknowledge": "确认",
    "Muse Archer • Level 1": "缪斯射手•1级",
    "No items are currently equipped.": "目前没有装备任何物品。",
    "No total skill bonuses applied.": "没有累计技能加成",
    "Quick access": "快速访问",
    "Set Bonuses": "套装加成",
    "Shadow Scroll Unveiled": "暗影卷轴已揭秘",
    "Used in Abyss and Dummy Training": "用于深渊和假人训练",
    "Accumulated:": "累计：",
    "Battle Log (Last 20 entries)": "战斗日志（最近20条）",
    "Death causes loss of all loot, XP, and gold.": "死亡会导致所有战利品、经验值和金币的损失。",
    "Hide players from other worlds": "隐藏来自其他世界的玩家",
    "Dark Forest": "黑暗森林",
    "PvP is disabled in the Drakmor world.": "在 德拉克莫尔 世界中PvP被禁用。",
    "Slayed a monster and took no damage.": "杀死一个怪物并且没有受到伤害。",
    "Tyken": "Tyken",
    "Your hunt status is maintained even if you leave the page, but will be cancelled if you": "即使你离开页面，你的狩猎状态也会保持，但是如果你离开页面，状态会被取消",
    "epic Guardian Amulet": "史诗守护者护身符",
    "No players here.": "此处无玩家。",
    "May Drop:": "可能掉落:",
    "May drop:": "可能掉落:",
    "HUNT": "狩猎",
    "Daily EXP Bonus Active": "每日经验加成活跃",
    "Dark Forest": "黑暗森林",
    "Dead River": "死亡之河",
    "⛨ Hunting Grounds": "⛨ 狩猎场",
    "← Back to Home": "← 返回首页",
    "Ashen Wastelands": "灰色荒原",
    "Abyssal Gate": "深渊之门",
    "Celestial Ruins": "天体遗迹",
    "Crimson Depths": "深红之境",
    "Dragon Peaks": "龙之峰巅",
    "Eternal Void": "空灵虚空",
    "Forgotten Caverns": "遗忘洞穴",
    "LEVEL UP": "升级了",
    "Equip": "装备",
    "Guardian Amulet": "守护者护身符",
    "Abyssal Lord, Demon Overlord, Soul Eater": "深渊领主，恶魔领主，食魂者",
    "Ash Golem, Lava Serpent, Infernal Knight": "灰烬魔像，熔岩蛇，地狱骑士",
    "Blood Lich, Abyssal Horror, Dark Siren": "血巫妖，深渊恐怖，黑暗塞壬",
    "Fallen Angel, Void Guardian, Astral Warden": "堕落天使，虚空守护者，星界守护者",
    "Goblin, Forest Spider": "哥布林，森林蜘蛛",
    "Night Wolf, Black Wolf, Giant Rat": "夜狼，黑狼，巨鼠",
    "Shadow Titan, Void Dragon, Eternal Reaper": "暗影泰坦，虚空巨龙，永恒死神",
    "Stone Golem, Lizard, Ogre": "石头魔像，蜥蜴，食人魔",
    "Young Dragon, Fire Elemental, Drake Rider": "幼龙，火元素，龙骑",
    "All accumulated XP and Gold from the hunt were lost.": "狩猎过程中积累的经验和金币全部丢失。",
    "RETURN TO HOME": "返回首页",
    "You were bleeding heavily and were finished off by a terrible monster..": "你失血过多，被一个可怕的怪物杀死了。",
    "⬅ Back to Home": "⬅ 返回首页",
    "Dummy": "假人",
    "Drako: ": "德拉科: ",
    "Gold: ": "金币: ",
    "Hotel": "旅店",
    "House Style": "房屋风格",
    "The Pub": "酒馆",
    "Current": "当前",
    "⚙️ House Skin": "⚙️ 房屋皮肤",
    "Logout": "登出",
    "Items": "物品",
    "Management": "管理",
    "Private Dummy": "私人假人",
    "Select": "选择",
    "Ship": "船",
    "Tent": "帐篷",
    "Outfit": "时装",
    "Finances": "财务",
    "Bar": "酒吧",
    "Bank": "银行",
    "Conteúdo do modal...": "模态内容加载...",
    "In your House, you can change your skin, decorate it with your hunt trophies.": "在你的房子里，你可以改变你的皮肤，用你的狩猎战利品装饰它。",
    "No Private training dummy available. Purchase one to start training.": "没有私人培训假人可用。购买一个开始训练。",
    "Private bank, outfits and dummy.": "私人银行，时装和假人。",
    "Updex": "优普德",
    "Updex records": "优普德记录",
    "Updex Collection": "优普德收藏",
    "Cost:": "成本:",
    ".\n  Each": ".\n  每个",
    "← Back to House": "← 返回房屋",
    "Use": "使用",
    "unique weapon": "独特武器",
    "Wolf Sword": "狼剑",
    "Zulu Hat": "祖鲁帽",
    "Sealed": "已封印",
    "Seal Echo": "封印共鸣",
    "seal an item": "封印一个物品",
    "SEAL TO UPDEX": "封印到优普德",
    ", but it becomes part of your": "，但它成为你的一部分",
    "+200 temporary Stamina points": "+ 200临时耐力点",
    "10 identical items": "10件相同的物品",
    "Alligator Echo": "鳄鱼共鸣",
    "allows you to": "允许你",
    "as a bonus.": "作为奖励。",
    "ATTEMPT UPGRADE (Consumes 10)": "尝试升级（消耗10）",
    "Base Success Chance": "基础成功几率",
    "combine 10 identical items": "组合10件相同的物品",
    "destroyed": "已摧毁",
    "Drako": "德拉科",
    "Final Success Chance": "最终成功几率",
    "Fox Echo": "狐狸共鸣",
    "Gold": "金币",
    "Heart of Vanya": "万尼亚之心",
    "Insufficient": "不足",
    "lets you": "让你",
    "Life Potion": "生命药水",
    "Mantus": "曼图斯",
    "Max total chance:": "最大总几率：",
    "Missing": "缺失",
    "Nightfire": "夜火",
    "No item with quantity ≥ 10": "没有物品的数量 ≥ 10",
    "Orchid": "兰花",
    "Penguin Echo": "企鹅共鸣",
    "Rabbit Echo": "兔子共鸣",
    "Rat Echo": "老鼠共鸣",
    "Rino Echo": "绿诺共鸣",
    "Select item to upgrade": "请选择要升级的物品",
    "Squirrel Echo": "松鼠共鸣",
    "to attempt an upgrade (+1). You can upgrade +1 → +2, +2 → +3, etc. If the attempt fails, the 10 items are destroyed.": "尝试升级（+1）。你可以升级+1→+2、+2→+3等等。如果尝试失败，这10件物品将被销毁。",
    "to permanently add it to your collection.\n  Once sealed, the item is": "将其永久添加到您的收藏中。\n一旦密封，该项目是",
    "to upgrade them into a stronger version. Each upgrade gives +1 to all stats and +5 Life if your item have Life as bonus.": "将它们升级为更强的版本。每次升级给所有属性+1和+5生命，如果你的物品有生命作为奖励。",
    "Tower Shield": "塔盾",
    "Unique equipable items — sealed items are permanently recorded and grants +200 temporary Stamina points as a bonus": "独特的装备物品-密封物品永久记录，并给予+200临时耐力点作为奖励",
    "Use Drako Boost (+60%)": "使用德拉科提升（+60%）",
    "Use Gold Boost (+9%)": "使用金币加成（+9%）",
    "Vibrant Boots": "活力靴子",
    "you seal grants": "你封印授予",
    "✨ Sealed": "✨ 已封印",
    "Cancel": "取消",
    "Confirm": "确认",
    "SEALED": "已封印",
    "Confirm seal": "确认封印",
    "Confirm Item Seal": "确认物品封印",
    "This item will be permanently destroyed and added to your Updex Collection.": "此物品将被永久销毁并添加到您的优普德收藏中。",
    "OK": "确定",
    "Atual": "当前",
    "ITEM SEALED": "物品已封印",
    "Your Outfits:": "你的时装:",
    "Muse": "缪斯",
    "Wardrobe": "衣柜",
    "Your Inventory Items (Decoration)": "你的库存物品（装饰）",
    "Withdraw": "提现",
    "Deposit": "存入",
    "Treino": "训练",
    "Buy": "购买",
    "Buy Private Training Dummy": "购买私人训练假人",
    "Demona": "狄蒙娜",
    "Gold on Bank:": "银行金币：",
    "Gold on Inventory:": "背包金币：",
    "Your training space is empty. Choose a dummy to purchase: NOTE you can only have one": "你的训练空间是空的。选择要购买的假人：注意只能拥有一个",
    "Start Auto-Click": "开始自动点击",
    "Start Auto-Hit": "开始自动命中",
    "Start Training": "开始训练",
    "Sword Training": "剑术训练",
    "Bow Training": "弓箭训练",
    "Drako:": "德拉科:",
    "Gold:": "金币:",
    "Shadow": "暗影",
    "Training Dummy": "训练假人",
    "Lakechant": "湖灵絮语",
    "Lakechant Fishing": "湖灵絮语钓鱼",
    "Do you want to start training BOW? All clicks will count towards this skill. (Goal: 2,500 Clicks). Auto-Hit will start automatically.": "你想开始训练弓吗？所有的点击都会被计算到这个技能中。（目标：2500次点击）。自动命中将自动启动。",
    "Loading fishing spot...": "正在装载钓鱼点...",
    "Defense Training": "防御训练",
    "Magic Training": "魔法训练",
    "Need 2 more...": "还需要2个...",
    "The Pub Shop": "酒馆商店",
    "The Pub Meet": "酒馆聚会",
    "Post": "发送",
    "Share opinions": "分享观点",
    "Life and Stamina Regen (Accumulated)": "生命和耐力回复（累计）",
    "Users on The Pub:": "酒馆玩家:",
    "Regen Life and Stam while training skills in dummy.": "在假人中训练技能时恢复生命和耐力。",
    "Guilds": "公会",
    "Insufficient Drako": "德拉科不足",
    ". World: Drakmor.": ". 世界: 德拉克莫尔.",
    "Create Guild (250 Drako)": "创建公会 (250 德拉科)",
    "Active Guilds": "活跃公会",
    "Create New Guild": "创建新公会",
    "Loading guild list...": "加载公会列表...",
    "Guild Emblem (PNG/JPG, Max 500KB)": "公会徽章 (PNG/JPG, 最大 500KB)",
    "Description (Max 255 chars)": "描述（最多255个字符）",
    "Guild members cannot attack each other in any world.": "公会成员在任何世界中都不能互相攻击。",
    "Guild Name (Max 10 chars)": "公会名称（最多10个字符）",
    "List of guilds on Drakmor World, ordered by member count.": "德拉克摩尔世界的公会列表，按成员数量排序。",
    "No guilds found on this world. Be the first to create one": "这个世界上没有公会。做第一个创建它的人",
    "The guild will be created on your current world.": "公会将在你当前的世界中创建。",
    "You need 250 Drako to create a guild.": "你需要250德拉科来创建一个公会。",
    "Price": "价格",
    "-- Choose from Inventory --": "-- 从库存中选择 --",
    "(Listed by:": "(上架者:",
    "Ring": "戒指",
    "Shield": "盾牌",
    "Select Item:": "选择物品:",
    "Search by Name:": "按名称搜索:",
    "Weapon": "武器",
    "Your Gold:": "你的金币:",
    "Misc. Items": "其它物品",
    "LIST ITEM": "上架物品",
    "LIST DRAKO": "上架德拉科",
    "List an Item for Sale": "上架物品出售",
    "Items For Sale": "出售物品",
    "Helmet": "头盔",
    "Gloves": "手套",
    "Echo": "回响",
    "Filter by Type:": "按类型过滤:",
    "Drako Exchange": "德拉科兑换",
    "BUY": "购买",
    "Boots": "靴子",
    "Armor": "盔甲",
    "Amulet": "护身符",
    "All Listings": "所有挂单",
    "⛶ Transactions": "⛶ 交易",
    "List DRAKO for GOLD": "上架德拉科换取金币",
    "Transaction History": "交易历史",
    "⛬ Dark Market - Drakmor": "⛬ 黑市 - 德拉克莫尔",
    "(A 5% fee will be deducted from the final sale price.)": "（最终售价将扣除 5% 的交易税费用。）",
    "Logs are kept for the last 50 transactions.": "保存最近 50 次交易的日志。",
    "No transactions recorded yet.": "暂无交易记录。",
    "Defense:": "防御:",
    "Guardian Amulet.": "守护者护身符.",
    "☽ Shadow Book": "☽ 暗影之书",
    "AVAILABLE": "可用",
    "LOCKED": "未解锁",
    "Requirement:": "要求:",
    "Reward:": "奖励:",
    "Complete Previous Quest": "完成前一个任务",
    "Pending Requirements": "待定条件",
    "A new path opens, leading to the deeper, forgotten wards of the city. Only those who have reached a significant milestone can pass the Gate of Sighs.": "一条新的道路打开了，通向城市深处被遗忘的角落。只有那些达到重要里程碑的人才能通过叹息门。",
    "A simple ritual of binding a basic shadow creature requires a tool that has seen blood and betrayal. Sacrifice a humble dagger to empower the ritual.": "一个简单的束缚基本暗影生物的仪式需要一个见过鲜血和背叛的工具。牺牲一把不起眼的匕首来赋予仪式力量。",
    "A Skull is required for the next phase of the questline. Find and retrieve the Skull from the fallen Arch-Lich's vault.": "下一阶段的任务线需要骷髅。从倒下的巫妖大墓穴中找到并取回骷髅。",
    "An ancient order of healers sought the morning light but were corrupted by the Terror. To cleanse the artifact, it must be sacrificed, granting inner peace and wisdom.": "一个古老的治疗师团体寻求晨光，但被恐怖所腐蚀。为了净化神器，必须牺牲它，以获得内心的平静和智慧。",
    "Before the final confrontation, a true test of spirit and defense is needed. The primordial fear manifests; you must weather its psychic assault.": "在最后的对抗之前，需要一次真正的精神和防御的考验。原始的恐惧显现出来；你必须经受住它的精神攻击。",
    "Beyond basic survival, the true grit of a Vanya Hunter is tested. You must achieve an ironclad will, capable of enduring the city's ceaseless horrors.": "除了基本的生存之外，万尼亚猎人的真正勇气也受到了考验。你必须拥有坚不可摧的意志，能够承受这座城市无休止的恐怖。",
    "Deep within the city, a saint's crypt holds secrets. To breach the final defenses, you must reach a higher state of readiness and combat expertise.": "在城市的深处，有一个圣徒的地窖，里面藏着秘密。要突破最后的防御，你必须达到更高的战备状态和战斗技能。",
    "Follow the path of the Ancients to claim powerful rewards. Quests must be completed in sequence.": "跟随先祖的道路去获得强大的奖励。任务必须按顺序完成。",
    "Shadow Scroll (Read this scroll and receive a random rare item from the shadows.)": "暗影卷轴（阅读此卷轴并从暗影中获得随机稀有物品）",
    "The Arcane Sigil is a trap. To truly progress, you must destroy the seal, risking sanity for freedom and gaining immense, raw power.": "奥术印记是一个陷阱。为了真正的进步，你必须摧毁封印，冒着失去理智的危险获得自由，获得巨大的原始力量。",
    "The final blow requires the strength of all who came before. Channel your ancestral power to reach a physical strength capable of slaying a god.": "最后一击需要所有先行者的力量。引导你祖先的力量，获得可以杀死神的体力。",
    "The final fight requires a surge of adrenaline. Retrieve the Mad Alchemist's last batch of Elixir of Valor to ensure you can withstand the overwhelming terror.": "最后一战需要肾上腺素激增。找回疯狂炼金术士的最后一批英勇长生不老药，以确保你可以承受压倒性的恐怖。",
    "The hero's journey is nearing its end. The legend of the Black Aegis requires peak readiness for the greatest challenge, promising a treasure of ultimate protection.": "英雄的旅程即将结束。黑盾的传说要求你为最大的挑战做好充分的准备，并承诺提供终极保护。",
    "The long, cold nights of Vanya demand an unyielding spirit. Only those with immense stamina can withstand the draining presence of the shadow beasts.": "万尼亚漫长而寒冷的夜晚需要不屈不挠的精神。只有那些拥有巨大耐力的人才能承受阴影野兽的消耗。",
    "The path to the High Spires is treacherous, guarded by aerial specters. Your journey is judged on its difficulty, not just its length.": "通往高塔的路很危险，有空中的幽灵把守。判断你旅程的标准是它的困难程度，而不仅仅是它的长度。",
    "The pervasive fog of Vanya carries a sinister scent. To venture deeper into the cursed lands, one must be prepared for the first clash with the true darkness.": "万尼亚弥漫的浓雾带着一种不祥的气味。想要深入诅咒之地，你必须准备好迎接第一次与真正的黑暗的冲突。",
    "The secrets of Vanya are locked in scrolls only decipherable by minds trained against madness. Prove your intellect to unlock ancient knowledge.": "万尼亚的秘密被锁在卷轴里只有经过抗疯癫训练的头脑才能破译。证明你的智慧来开启古老的知识。",
    "The shades of Vanya attack the soul. Build a defense not just of steel, but of spirit, to resist the psychic drain of the true Dreadlords.": "瓦尼亚的影子攻击灵魂。建立一个不仅仅是钢铁的防御，而且是精神的防御，以抵抗真正的恐惧领主的精神消耗。",
    "To survive the Abyss, one must possess not only spirit but brute force. Only the strong can push through the phantom barricades blocking the path to the catacombs.": "要想在深渊里活下来，不仅要有精神，还要有蛮力。只有强壮的人才能穿过阻挡通往地下墓穴之路的幻影路障。",
    "To understand the enemy, one must delve into the forbidden lore. Only the most astute minds can decipher the warnings etched in the cursed texts.": "要了解敌人，必须深入研究禁忌之爱。只有最精明的人才能破译铭刻在被诅咒的文本中的警告。",
    "Use the Crimson Scale to forge the legendary shield, the Aegis of Vanya. This ancient ritual demands the scale's sacrifice, but grants ultimate defense.": "使用深红刻度铸造传说中的盾牌，万尼亚之盾。这个古老的仪式需要巨鳞的牺牲，但却能提供终极防御。",
    "Using the Skull, you must weave a temporary pact with the darkness to cross a perilous threshold. This pact requires the artifact itself as a temporary focus.": "使用骷髅，你必须与黑暗编织一个临时契约，以跨越危险的门槛。这个契约需要藏物本身作为暂时的焦点。",
    "Vanya's cursed mountain peak demands an endurance few possess. You must prove your stamina is limitless to even start the climb.": "万尼亚被诅咒的山峰需要很少人拥有的耐力。你必须证明你的耐力是无限的，甚至开始攀登。",
    "Whispered tales of a forgotten warrior whose defense was their greatest offense. Legend says only those who master the art of resistance can hear her call.": "一个被遗忘的战士的传说他的防御是他们最大的进攻。传说只有掌握抵抗之术的人才能听到她的呼唤。",
    "With the Aegis prepared, your quest culminates. To face the Shadow Lord, your defenses must be absolute—an unbreakable shell forged from fear and destiny.": "随着宙斯盾的准备，你的任务达到高潮。面对暗影之主，你的防御必须是绝对的——一个由恐惧和命运锻造而成的牢不可破的外壳。",
    "You have drawn the attention of the Shadow Lord. His minions are everywhere, but one specific beast holds a piece of his armor—the Crimson Scale.": "你已经引起了影子议员的注意。他的仆从无处不在，但有一只特殊的野兽拿着他的一块盔甲——深红鳞甲。",
    "Your power is immense, your legend certain. You must now stand at the very gates of the Shadow Lord's dominion. Only true masters may approach.": "你的力量是巨大的，你的传奇是确定的。你现在必须站在暗影魔王领地的大门口。只有真正的大师才能接近。",
    "Innkeeper": "旅店老板",
    "Auto-Hit Slowly": "缓慢地自动命中",
    "Abandon & Start": "放弃 & 开始",
    "Moonfin Shop": "月鳍鱼商店",
    "Move with arrows": "使用箭头键移动",
    "You must equip a Fishing Rod.": "你必须装备一个鱼竿。",
    "Welcome to the endless grind. Good luck.": "欢迎来到无尽的磨练。祝你好运。",
    "Click the sparkling spot to fish...": "点击闪闪发光的地方钓鱼...",
    "← Back to Lake": "← 返回湖边",
    "Your Moonfin:": "你的月鳍鱼:",
    "Stamina Potion ": "耐力药水 ",
    "Full Life Potion ": "满血药水 ",
    "Sparring Weapon (Instant 500 Hits on Dummy) ": "陪练武器（瞬间命中假人500次）",
    "Bow:": "弓:",
    "Fishing:": "钓鱼:",
    "Sword:": "剑:",
    "Skill Statistics": "技能统计",
    "Player Profile": "玩家资料",
    "Equipments — Swipe to see more": "装备 - 左右滑动查看更多",
    "Carregando...": "点击...",
    "Abandon BOW & Start SWORD": "放弃弓 & 开始用剑",
    "Abandon BOW & Start MAGIC": "放弃弓 & 开始用魔法",
    "Abandon MAGIC & Start SWORD": "放弃魔法 & 开始用剑",
    "Abandon MAGIC & Start BOW": "放弃魔法 & 开始用弓",
    "Abandon SWORD & Start BOW": "放弃剑 & 开始用弓",
    "Abandon SWORD & Start MAGIC": "放弃剑 & 开始用魔法",
    "Abandon SWORD & Start DEFENSE": "放弃剑 & 开始用防御",
    "MAGIC": "魔法",
    "Buy Now": "立即购买",
    "Change Nickname": "更改昵称",
    "LIMITED": "有限",
    "GET IT NOW": "立即获取",
    "Enter your card details securely via  ": "输入您的信用卡信息安全通过",
    "Insufficient Drako.": "德拉科不足。",
    "Insufficient Gold.": "金币不足。",
    "Limit: 5 purchases per day.": "每日限购5次。",
    "Refill Daily XP Boost": "补充每日经验提升",
    "Warning:": "警告:",
    "World Transfer": "世界转移",
    "Pay": "支付",
    "You must leave your guild. All your market listings will be deleted.": "你必须退出你的公会。您所有的市场挂单将被删除。",
    "Your character name (Nickname) will be permanently changed": "您的角色名称（昵称）将被永久更改",
    "Transactions are processed securely by Mercado Pago. All prices are in BRL.": "交易由 Mercado Pago 安全处理。所有价格均以 BRL 计价。",
    "Transactions are processed securely by Stripe. All prices are in USD.": "交易通过Stripe安全处理。所有价格均以 USD 计价。",
    "Premium Services": "高级服务",
    "Open Box": "打开宝箱",
    "November": "11月",
    "Transfer to Noctra": "转移至 诺克特拉",
    "Move your char to a different Vanya World.": "移动你的角色到一个不同的万尼亚世界。",
    "International": "国际",
    "Instantly adds 60 minutes of +50% XP Boost to your account, this boost cannot stack.": "立即增加 60 分钟 +50% 经验值的提升到你的帐户，这个提升不能叠加。",
    "Grants +39 Sword Skill and +34 Life": "授予 +39 剑术技能 和 +34 生命值",
    "Exclusive. Limited. Never returning.": "专属。限定。永远不会返回。",
    "Drako Refill ": "德拉科重装",
    "Brazil/Latam PIX": "巴西/拉丁美洲PIX",
    "Must be 3-15 characters (letters, numbers, spaces).": "必须是3-15个字符（字母、数字、空格）。",
    "Vanya Vault": "万尼亚金库",
    "Your character name (Nickname) will be permanently changed.": "您的角色名称（昵称）将被永久更改。",
    "Each attack costs 5 Stamina. Defeat the boss to unlock the next Abyss stage. The boss’s Life is shared globally across all worlds, but only the player who lands the final blow has a chance to obtain the loot.": "每次攻击消耗5点耐力。击败boss解锁下一个深渊关卡。boss的生命在所有世界中都是共享的，但只有完成最后一击的玩家才有机会获得战利品。",
    "of Players": "的玩家",
    "Kills:": "击杀:",
    "Last Killed By:": "最终击杀自:",
    "Completed by": "已完成的有",
    "+150 incremental Sword Skill": "+150 剑术技能",
    "Abyss Global Boss": "深渊全球Boss",
    "Boss Codex": "Boss图鉴",
    "Boss List": "Boss列表",
    "by taking them down": "通过打倒他们",
    "Defeat a boss 5000 times to complete their entry and gain": "击败 Boss 5000次以完成他们的入口并获得奖励",
    "Your Profile": "你的资料",
    "Topics": "主题",
    "Stats": "统计",
    "Talk about anything related to the game.": "谈论任何与游戏相关的内容。",
    "Report technical issues and bugs.": "报告技术问题和错误。",
    "Posts": "回帖",
    "Recruit new members and expand your guild.": "招募新成员，扩大你的公会。",
    "Official game announcements and updates.": "官方游戏公告和更新。",
    "News / Updates": "新闻 / 更新",
    "Guilds & Alliances": "公会 & 联盟",
    "Guild Recruitment": "公会招募",
    "General Discussion": "一般讨论",
    "General": "一般",
    "Game Development": "游戏开发",
    "Forum Board": "论坛版块",
    "DEV POSTS ONLY": "仅限开发动态",
    "Dark Market": "黑市",
    "Community": "社区",
    "Buy/Sell items on the Noctra world.": "在 诺克特拉 世界中 购买/出售 物品。",
    "Buy/Sell items on the Drakmor world.": "在 德拉克莫尔 世界中 购买/出售 物品。",
    "Bug Reports": "报告Bug",
    "Drakmor": "德拉克莫尔",
    "Noctra": "诺克特拉",
    "START NEW TOPIC": "发布新主题",
    "Guild Chat": "公会聊天",
    "House Dummy": "房屋假人",
    "Last Post": "最新回帖",
    "Topic": "主题",
    "Replies": "回复",
    "Views": "阅读",
    "Your inventory is empty. Go hunting": "你的库存是空的。前往狩猎",
    "Fisherman Outfit": "渔夫时装",
    "GLOBAL": "全球",
    "TOP BOW": "最高弓",
    "TOP DEFENSE": "最高防御",
    "TOP SWORD": "最高剑",
    "TOP GOLD": "最高金币",
    "TOP FISHING": "最高钓鱼",
    "TOP LEVEL": "最高等级",
    "TOP MAGIC": "最高魔法",
    "Top 50 by Sword on GLOBAL": "全球排名前 50 剑",
    "Top 50 by Defense on GLOBAL": "全球排名前 50 防御",
    "Top 50 by Bow on GLOBAL": "全球排名前 50 弓",
    "Top 50 by Fishing on GLOBAL": "全球排名前 50 钓鱼",
    "Top 50 by Gold on GLOBAL": "全球排名前 50 金币",
    "Top 50 by Level on GLOBAL": "全球排名前 50 等级",
    "Top 50 by Magic on GLOBAL": "全球排名前 50 魔法",
    "Vanya Global Leaderboards": "万尼亚全球排行榜",
    "Level": "等级",
    "Player": "玩家",
    "Filter by World:": "按世界过滤:",
    "Loot Found": "发现战利品",
    "You are dead by a monster": "你被怪物击败了",
    "You died during the hunt! All accumulated gains were lost.": "你在狩猎中死亡！所有积累的收益都付之东流。",
    "You were killed in PvP. Your accumulated Gold was lost..": "你在PvP中被杀了。你积累的金币丢失了...",
    "Your Status": "你的状态",
    "Death causes loss of all loot, XP, and gold": "死亡会导致所有战利品、经验值和金币的损失",
    "END HUNT & COLLECT ALL": "结束狩猎 & 收集全部",
    "Un-equip": "脱下",
    "Daily EXP Bonus depleted.": "每日经验奖励已耗尽。",
    "Reset is available tomorrow, or refill it at the": "等待明日重置，或者重装此效果在",
    "Vault": "金库",
    "No loot found yet...": "暂无发现战利品...",
    "Estimated:": "预估:",
    "Magic:": "魔法:",
    "DEFENSE": "防御",
    "You swapped Spider Wand for Wolf Sword.": "你把蜘蛛杖换成了狼剑。",
    "[ Leave ]": "[ 离开 ]",
    "Active Boss Attackers (Last 24h):": "活跃Boss攻击者（最近24小时）：",
    "Attack the ": "攻击",
    "Battle Log": "战斗日志",
    "Battle vs Goblin King started": "与哥布林之王的战斗开始了",
    "Boosted Boss! Loot drop chance increased by (+5%)": "被鼓舞的Boss！掉落物品的几率增加（+5%）",
    "Boss Life:": "Boss生命值：",
    "Defeated! You need to heal.": "被击败！你需要治疗。",
    "Last Boss Killed By:": "最近被击败的Boss：",
    "You've been defeated! You need to recover.": "你被击败了！你需要恢复。",
    "You are dead": "你挂掉了",
    "Attack (Defeated)": "攻击 (被击败)",
    "Your life is 0. You cant battle.": "你的生命值是0。你不能战斗了。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Lucky": "Lucky",
    "Shiro.": "Shiro.",
    "RughS.": "RughS.",
    "Potat.": "Potat.",
    "Fatbo.": "Fatbo.",
    "Aleks.": "Aleks.",
    "The": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "PvP": "PvP",
    "×": "×",
    "© 2025 Demona Vosz — All Rights Reserved": "© 2025 Demona Vosz — All Rights Reserved",
    "Gityx": "Gityx",
    "???": "???",
    "🎒": "🎒",
    "👚": "👚",
    "⚔️": "⚔️",
    "💰": "💰",
    "✨": "✨",
    "?": "?",
    "➡": "➡",
    "⬅": "⬅",
    "⬆": "⬆",
    "⬇": "⬇",
    "🛡️": "🛡️",
    "#": "#",
    "[E]": "[E]",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "%": "%",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t\t": "\t\t\t",
    "\t\t": "\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Population": "人口",
    "Drakmor": "德拉克莫尔",
    "Noctra": "诺克特拉",
    "Vanya Patch Notes: ": "万尼亚 更新日志: ",
    "Vanya Online: ": "万尼亚在线: ",
    "Last activity: ": "最近活跃: ",
    "Welcome, ": "欢迎, ",
    "Life:": "生命值:",
    "Players hunting": "玩家狩猎中",
    "Slayed a monster and found a ": "击杀了一个怪物并发现了一个 ",
    "Slayed a monster and found an ": "击杀了一个怪物并发现了一个 ",
    "Monsters: ": "怪物: ",
    "Muse Archer • Level ": "缪斯射手 • 等级 ",
    "Select Item (Min. ": "选择物品 (最低 ",
    "House: ": "房屋: ",
    "Inv: ": "库存: ",
    "Training Dummy: ": "训练假人: ",
    "Training: ": "训练: ",
    "Your Level: ": "你的等级: ",
    "WEAPON | ": "武器 | ",
    "SHIELD | ": "盾牌 | ",
    "AMULET | ": "护身符 | ",
    "BOOTS | ": "靴子 | ",
    "ARMOR | ": "盔甲 | ",
    "HELMET | ": "头盔 | ",
    "Goblin Helmet": "哥布林头盔",
    "Guardian Amulet": "守护者护身符",
    "DRAKO Amount to Sell (Current: ": "要出售的 德拉科 数量 (当前: ",
    "You have equipped ": "你已装备 ",
    "Brave Gloves": "勇者手套",
    "Black Helmet": "黑色头盔",
    "Amazon Armor": "亚马逊护甲",
    "Amazon Shield": "亚马逊之盾",
    "Avalanche Wand": "雪崩魔杖",
    "Battle Armor": "战斗盔甲",
    "Blood Banquet": "血之盛宴",
    "Bone Sword": "骨剑",
    "Brass Armor": "黄铜盔甲",
    "Carnivora Armor": "食肉兽护甲",
    "Crusader Helmet": "十字军头盔",
    "Decay Bow": "衰变弓",
    "Demon Eye": "恶魔之眼",
    "Devil Horn": "恶魔之角",
    "Divine Armor": "神圣铠甲",
    "Dragon Scale Gloves": "龙鳞手套",
    "Draymor Helmet": "德拉莫头盔",
    "Emerald Gloves": "翡翠手套",
    "Emerald Heart": "翡翠之心",
    "Fire Shield": "火盾",
    "Fire Sword": "火剑",
    "Fishing Rod": "鱼竿",
    "Frog Helmet": "青蛙头盔",
    "Fur Shield": "毛皮盾牌",
    "Goblin Boots": "哥布林靴子",
    "Golden Boots": "金靴子",
    "Golden Gloves": "金手套",
    "Golden Sword": "金剑",
    "High Heel": "高跟鞋",
    "Kriss": "波形刀",
    "Lizard Ring": "蜥蜴戒指",
    "Lotus Bow": "莲花弓",
    "Love Dress": "爱情裙",
    "Lunar Robe": "月宫袍",
    "Metal Mask": "金属面具",
    "Moon Bow": "月之弓",
    "Obsession Boots": "执念靴",
    "Ocean Shield": "海之盾",
    "Ogre Boots": "食人魔靴子",
    "Pirate Hat": "海盗帽子",
    "Poison Sword": "毒剑",
    "Rapier": "长剑",
    "Redsec Shield": "红牌盾",
    "Rose Shield": "玫瑰盾牌",
    "Sacred Shield": "神圣之盾",
    "Scarpet Ring": "猩红戒指",
    "Serpent Ring": "巨蛇戒指",
    "Serpent Sword": "蛇剑",
    "Skull Book": "骷髅书",
    "Skull Shield": "骷髅盾",
    "Skyfall Boots": "天陨战靴",
    "Slingshot": "弹弓",
    "Spider Amulet": "蜘蛛护身符",
    "Spider Wand": "蜘蛛魔杖",
    "Spike Amulet": "尖刺护身符",
    "Suddent Killer Rune": "突然杀手符文",
    "Sun Ring": "太阳戒指",
    "Supreme Amazon Armor": "超级亚马逊盔甲",
    "Terror Amulet": "恐怖护身符",
    "Rotworm Echo": "腐虫共鸣",
    "Training Skill: ": "训练技能: ",
    "Current Hit: ": "当前命中: ",
    "Magic: +": "魔法: +",
    "Defense: +": "防御: +",
    "Sword: +": "剑: +",
    "Bow: +": "弓: +",
    "Level: ": "等级: ",
    "Slot: ": "槽位: ",
    "Obtained from this collection: ": "从这个集合中得到: ",
    "Drako’s Treasury #": "德拉科的宝藏 #",
    "Required Level: ": "要求等级: ",
    "World: ": "世界: ",
    "Topics Started: ": "开始的主题: ",
    "Total Posts: ": "回帖总数: ",
    "Hunting in ": "狩猎于 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "!": "!",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec)": "/秒)",
    "% bonus": "% 奖励",
    " day(s)": " 天",
    " (PvP)": " (PvP)",
    " (Non-PvP)": " (无PvP)",
    " - Hello Vanyans!": " - 你好，万尼亚人！",
    " (Idle Farming)": " (放置扫荡)",
    " (World: Drakmor)": " (世界: 德拉克莫尔)",
    " (World: Noctra)": " (世界: 诺克特拉)",
    " (Added to inventory)": " (已放入库存)",
    "• Equippable": "• 可装备",
    " sealed": " 已封印",
    " Hits": " 命中",
    " (Upgrade)": " (升级)",
    "Goblin Helmet": "哥布林头盔",
    "Guardian Amulet": "守护者护身符",
    " (In use)": " (使用中)",
    " (GOLD):": " (金币):",
    " (Gold):": " (金币):",
    " (NPC)": " (NPC)",
    "Your Drako:": "你的德拉科:",
    "The Whispering Defenses": "低语防御",
    "The Crypt of the Forgotten Saint": "被遗忘圣人的墓穴",
    "The Mad Alchemist's Brew": "疯狂炼金术师的酿造",
    "Confronting the Dread": "直面恐惧",
    "The Black Aegis": "黑色圣盾",
    "The Ironclad Will": "坚不可摧的意志",
    "The Gate of Sighs": "叹息之门",
    "The Forbidden Archives": "被禁止的档案",
    "The Unseen Wall": "看不见的墙",
    "The Midnight Ascent": "午夜飞升",
    "Shattering the Bond": "打破束缚",
    "The First Scent of Dread": "最初的恐惧气息",
    "Heart of the Mountain": "山之心",
    "The Lord's Retaliation": "领主的报复",
    "Blade of the Ancestors": "祖先之刃",
    "The Shadow Throne": "暗影王座",
    "Forging the Truth": "锻造真理",
    "The Immortal Hunter": "不朽的猎人",
    "The Price of Steel": "钢铁价格",
    "Echoes in the Abyss": "深渊中的回声",
    "Purging the Tainted Vessel": "净化被污染的容器",
    "The Scholar's Secret": "学者的秘密",
    "The Skull": "骷髅头",
    "Night's Relentless Vigil": "夜的无情守夜",
    "Weaving the Shadow": "织影",
    " Lost Story": "失落故事",
    " Seasonal Loot": " 季节性战利品",
    "Goblin King": "哥布林之王",
    "Tyranus": "暴君",
    "The One": "救世主",
    "Helenita": "海伦妮塔",
    "Zulu Zaraza": "祖鲁·扎拉扎",
    "Hex Hexa": "Hex Hexa",
    "Damage Factor: ": "伤害系数: ",
    "Your Total Skill: ": "你的总技能: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^R\$ ([\d\.,]+)$/,
    /^\$([\d\.]+) USD$/,
    /^\(([\d\.]+)\)$/,
    /^ \(([\d\.]+)\):$/,
    /^ \(x([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+) \(\+([\d\.]+)\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)x $/,
    /^([\d\.,]+)\)$/,
    /^x([\d\.,]+)$/,
    /^x([\d\.,]+) $/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^ ([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = []

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You hit the Goblin King for (.+) damage. Boss life remaining: (.+)$/, '你攻击了 哥布林之王 并造成了 $1 伤害. Boss剩余生命值: $2'],
    [/^The Goblin King hit you for (.+) damage. Your new life: (.+)$/, '哥布林之王 攻击了并造成 $1 伤害. 你的新生命值: $2'],
    [/^Buscando dados de (.+)...$/, '正在查找关于 $1 的数据...'],
    [/^Seller Net: (.+) \(Fee: (.+)\)$/, '卖家净价: $1 (交易税: $2)'],
    [/^(.+) Life and (.+) Stamina in (.+)$/, '$1 生命值和 $2 耐力 还有 $3'],
    [/^Goblin Helmet successfully sealed and registered on Updex. You received (.+) temporary Stamina points to use as you wish.$/, '哥布林头盔成功封印并在优普德注册。你将获得 $1 临时耐力点，可以随意使用。'],
    [/^While you were away, you gained (.+) XP$/, '当你离开的时候，你获得了 $1 经验值'],
    [/^You are currently training DEFENSE \((.+) Hits\). Do you want to ABANDON this progress and start training BOW\? Auto-Hit will start automatically.$/, '你目前正在训练防御（$1 命中）。你想放弃这个进程并开始训练弓吗？自动命中将自动启动。'],
    [/^You are currently training MAGIC \((.+) Hits\). Do you want to ABANDON this progress and start training BOW\? Auto-Hit will start automatically.$/, '你目前正在训练魔法（$1 命中）。你想放弃这个进程并开始训练弓吗？自动命中将自动启动。'],
    [/^You are currently training MAGIC \((.+) Hits\). Do you want to ABANDON this progress and start training SWORD\? Auto-Hit will start automatically.$/, '你目前正在训练魔法（$1 命中）。你想放弃这个进程并开始训练剑吗？自动命中将自动启动。'],
    [/^You are currently training SWORD \((.+) Hits\). Do you want to ABANDON this progress and start training DEFENSE\? Auto-Hit will start automatically.$/, '你目前正在训练剑（$1 命中）。你想放弃这个进程并开始训练防御吗？自动命中将自动启动。'],
    [/^You are currently training SWORD \((.+) Hits\). Do you want to ABANDON this progress and start training BOW\? Auto-Hit will start automatically.$/, '你目前正在训练剑（$1 命中）。你想放弃这个进程并开始训练弓吗？自动命中将自动启动。'],
    [/^You are currently training SWORD \((.+) Hits\). Do you want to ABANDON this progress and start training MAGIC\? Auto-Hit will start automatically.$/, '你目前正在训练剑（$1 命中）。你想放弃这个进程并开始训练魔法吗？自动命中将自动启动。'],
    [/^You are currently training BOW \((.+) Hits\). Do you want to ABANDON this progress and start training MAGIC\? Auto-Hit will start automatically.$/, '你目前正在训练弓箭（$1 命中）。你想放弃这个进程并开始训练魔法吗？自动命中将自动启动。'],
    [/^You are currently training BOW \((.+) Hits\). Do you want to ABANDON this progress and start training SWORD\? Auto-Hit will start automatically.$/, '你目前正在训练弓箭（$1 命中）。你想放弃这个进程并开始训练剑术吗？自动命中将自动启动。'],
    [/^You are currently training BOW \((.+) Hits\). Do you want to ABANDON this progress and start training DEFENSE\? Auto-Hit will start automatically.$/, '你目前正在训练弓箭（$1 命中）。你想放弃这个进程并开始训练防御吗？自动命中将自动启动。'],
    [/^You are currently training BOW \((.+) Hits\). Auto-Hit will start automatically.$/, '你目前正在训练弓箭（$1 命中）。自动命中将自动启动。'],
    [/^You are currently training BOW \((.+) Hits\). Auto-Hit will start now.$/, '你目前正在训练弓箭（$1 命中）。自动命中将立即启动。'],
    [/^You are currently training MAGIC \((.+) Hits\). Auto-Hit will start now.$/, '你目前正在训练魔法（$1 命中）。自动命中将立即启动。'],
    [/^You are currently training SWORD \((.+) Hits\). Auto-Hit will start now.$/, '你目前正在训练剑术（$1 命中）。自动命中将立即启动。'],
    [/^You are currently training DEFENSE \((.+) Hits\). Auto-Hit will start now.$/, '你目前正在训练防御（$1 命中）。自动命中将立即启动。'],
    [/^Expected Gain: \n(.+) XP \/ \n(.+) Gold \n(.+)\/ min$/, '预期收益: \n$1 经验值 / \n$2 金币 \n$3/ 分钟'],
    [/^Expected Gain: \n(.+) XP \/ \n(.+) No Gold in this area \n(.+)\/ min$/, '预期收益: \n$1 经验值 / \n$2 此区域无金币 \n$3/ 分钟'],
    [/^\-\n(.+)You have (.+) minutes left of \+50\% XP.$/, '-\n$1你的 +50% 经验加成，还剩 $2 分钟.'],
    [/^You stopped hunting in Dark Forest after (.+). You won (.+) XP \( (.+) bonus applied for (.+)\) and (.+) Gold! Items Found: (.+)x Guardian Amulet, (.+)x Goblin Helmet$/, '你在黑暗森林中狩猎 $1 后停止了。你获得了 $2经验（$4 的时间获得了额外 $3 奖励）和 $5 金币！发现物品：$6x 守护护身符，$7x 哥布林头盔'],
    [/^You stopped hunting in Dark Forest after (.+). You won (.+) XP \( (.+) bonus applied for (.+)\) and (.+) Gold! Items Found: (.+)x Goblin Helmet$/, '你在黑暗森林中狩猎 $1 后停止了。你获得了 $2经验（$4 的时间获得了额外 $3 奖励）和 $5 金币！发现物品：$6x 哥布林头盔'],
    [/^You stopped hunting in Dark Forest after (.+). You won (.+) XP \( (.+) bonus applied for (.+)\) and (.+) Gold$/, '你在黑暗森林中狩猎 $1 后停止了。你获得了 $2经验（$4 的时间获得了额外 $3 奖励）和 $5 金币'],
    [/^You stopped hunting in Dark Forest after (.+). You won (.+) XP and (.+) Gold! Items Found: (.+)x Guardian Amulet, (.+)x Goblin Boots$/, '你在黑暗森林中狩猎 $1 后停止了。你获得了 $2经验 和 $3 金币! 发现物品: $4x 守护者护身符, $5x 哥布林靴子'],
    [/^Jan ([\d\.,]+)$/, '1 月 $1'],
    [/^Feb ([\d\.,]+)$/, '2 月 $1'],
    [/^Mar ([\d\.,]+)$/, '3 月 $1'],
    [/^Apr ([\d\.,]+)$/, '4 月 $1'],
    [/^May ([\d\.,]+)$/, '5 月 $1'],
    [/^Jun ([\d\.,]+)$/, '6 月 $1'],
    [/^Jul ([\d\.,]+)$/, '7 月 $1'],
    [/^Aug ([\d\.,]+)$/, '8 月 $1'],
    [/^Sep ([\d\.,]+)$/, '9 月 $1'],
    [/^Oct ([\d\.,]+)$/, '10 月 $1'],
    [/^Nov ([\d\.,]+)$/, '11 月 $1'],
    [/^Dec ([\d\.,]+)$/, '12 月 $1'],
    [/^January, ([\d\.,]+)$/, '$1 年 1 月'],
    [/^February, ([\d\.,]+)$/, '$1 年 2 月'],
    [/^March, ([\d\.,]+)$/, '$1 年 3 月'],
    [/^April, ([\d\.,]+)$/, '$1 年 4 月'],
    [/^May, ([\d\.,]+)$/, '$1 年 5 月'],
    [/^June, ([\d\.,]+)$/, '$1 年 6 月'],
    [/^July, ([\d\.,]+)$/, '$1 年 7 月'],
    [/^August, ([\d\.,]+)$/, '$1 年 8 月'],
    [/^September, ([\d\.,]+)$/, '$1 年 9 月'],
    [/^October, ([\d\.,]+)$/, ' $1 年 10 月'],
    [/^November, ([\d\.,]+)$/, ' $1 年 11 月'],
    [/^December, ([\d\.,]+)$/, ' $1 年 12 月'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '1月 $1 上午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '2月 $1 上午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '3月 $1 上午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '4月 $1 上午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '5月 $1 上午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '6月 $1 上午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '7月 $1 上午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '8月 $1 上午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '9月 $1 上午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '10月 $1 上午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '11月 $1 上午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) AM$/, '12月 $1 上午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '1月 $1 下午 $2:$3:$4'],
	[/^Feb ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '2月 $1 下午 $2:$3:$4'],
	[/^Mar ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '3月 $1 下午 $2:$3:$4'],
	[/^Apr ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '4月 $1 下午 $2:$3:$4'],
	[/^May ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '5月 $1 下午 $2:$3:$4'],
	[/^Jun ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '6月 $1 下午 $2:$3:$4'],
	[/^Jul ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '7月 $1 下午 $2:$3:$4'],
	[/^Aug ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '8月 $1 下午 $2:$3:$4'],
	[/^Sep ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '9月 $1 下午 $2:$3:$4'],
	[/^Oct ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '10月 $1 下午 $2:$3:$4'],
	[/^Nov ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '11月 $1 下午 $2:$3:$4'],
	[/^Dec ([\d\.]+), ([\d\.]+):([\d\.]+):([\d\.]+) PM$/, '12月 $1 下午 $2:$3:$4'],
	[/^Jan ([\d\.]+), ([\d\.]+) AM$/, '1月 $1 上午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) AM$/, '2月 $1 上午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) AM$/, '3月 $1 上午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) AM$/, '4月 $1 上午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) AM$/, '5月 $1 上午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) AM$/, '6月 $1 上午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) AM$/, '7月 $1 上午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) AM$/, '8月 $1 上午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) AM$/, '9月 $1 上午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) AM$/, '10月 $1 上午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) AM$/, '11月 $1 上午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) AM$/, '12月 $1 上午 $2'],
	[/^Jan ([\d\.]+), ([\d\.]+) PM$/, '1月 $1 下午 $2'],
	[/^Feb ([\d\.]+), ([\d\.]+) PM$/, '2月 $1 下午 $2'],
	[/^Mar ([\d\.]+), ([\d\.]+) PM$/, '3月 $1 下午 $2'],
	[/^Apr ([\d\.]+), ([\d\.]+) PM$/, '4月 $1 下午 $2'],
	[/^May ([\d\.]+), ([\d\.]+) PM$/, '5月 $1 下午 $2'],
	[/^Jun ([\d\.]+), ([\d\.]+) PM$/, '6月 $1 下午 $2'],
	[/^Jul ([\d\.]+), ([\d\.]+) PM$/, '7月 $1 下午 $2'],
	[/^Aug ([\d\.]+), ([\d\.]+) PM$/, '8月 $1 下午 $2'],
	[/^Sep ([\d\.]+), ([\d\.]+) PM$/, '9月 $1 下午 $2'],
	[/^Oct ([\d\.]+), ([\d\.]+) PM$/, '10月 $1 下午 $2'],
	[/^Nov ([\d\.]+), ([\d\.]+) PM$/, '11月 $1 下午 $2'],
	[/^Dec ([\d\.]+), ([\d\.]+) PM$/, '12月 $1 下午 $2'],
	[/^Jan (.+), ([\d\.]+)$/, '$2 年 1 月 $1'],
	[/^Feb (.+), ([\d\.]+)$/, '$2 年 2 月 $1'],
	[/^Mar (.+), ([\d\.]+)$/, '$2 年 3 月 $1'],
	[/^Apr (.+), ([\d\.]+)$/, '$2 年 4 月 $1'],
	[/^May (.+), ([\d\.]+)$/, '$2 年 5 月 $1'],
	[/^Jun (.+), ([\d\.]+)$/, '$2 年 6 月 $1'],
	[/^Jul (.+), ([\d\.]+)$/, '$2 年 7 月 $1'],
	[/^Aug (.+), ([\d\.]+)$/, '$2 年 8 月 $1'],
	[/^Sep (.+), ([\d\.]+)$/, '$2 年 9 月 $1'],
	[/^Oct (.+), ([\d\.]+)$/, '$2 年 10 月 $1'],
	[/^Nov (.+), ([\d\.]+)$/, '$2 年 11 月 $1'],
	[/^Dec (.+), ([\d\.]+)$/, '$2 年 12 月 $1'],
	[/^January ([\d\.]+) Theme$/, '$1 年 1 月 主题'],
	[/^February ([\d\.]+) Theme$/, '$1 年 2 月 主题'],
	[/^March ([\d\.]+) Theme$/, '$1 年 3 月 主题'],
	[/^April ([\d\.]+) Theme$/, '$1 年 4 月 主题'],
	[/^May ([\d\.]+) Theme$/, '$1 年 5 月 主题'],
	[/^June ([\d\.]+) Theme$/, '$1 年 6 月 主题'],
	[/^July ([\d\.]+) Theme$/, '$1 年 7 月 主题'],
	[/^August ([\d\.]+) Theme$/, '$1 年 8 月 主题'],
	[/^September ([\d\.]+) Theme$/, '$1 年 9 月 主题'],
	[/^October ([\d\.]+) Theme$/, '$1 年 10 月 主题'],
	[/^November ([\d\.]+) Theme$/, '$1 年 11 月 主题'],
	[/^December ([\d\.]+) Theme$/, '$1 年 12 月 主题'],
	[/^Jan ([\d\.]+) \- Jan ([\d\.]+)$/, '1 月 $1 \- 1 月 $2'],
	[/^Feb ([\d\.]+) \- Feb ([\d\.]+)$/, '2 月 $1 \- 2 月 $2'],
	[/^Mar ([\d\.]+) \- Mar ([\d\.]+)$/, '3 月 $1 \- 3 月 $2'],
	[/^Apr ([\d\.]+) \- Apr ([\d\.]+)$/, '4 月 $1 \- 4 月 $2'],
	[/^May ([\d\.]+) \- May ([\d\.]+)$/, '5 月 $1 \- 5 月 $2'],
	[/^Jun ([\d\.]+) \- Jun ([\d\.]+)$/, '6 月 $1 \- 6 月 $2'],
	[/^Jul ([\d\.]+) \- Jul ([\d\.]+)$/, '7 月 $1 \- 7 月 $2'],
	[/^Jun ([\d\.]+) \- Jul ([\d\.]+)$/, '6 月 $1 \- 7 月 $2'],
	[/^Aug ([\d\.]+) \- Aug ([\d\.]+)$/, '8 月 $1 \- 8 月 $2'],
	[/^Sep ([\d\.]+) \- Sep ([\d\.]+)$/, '9 月 $1 \- 9 月 $2'],
	[/^Oct ([\d\.]+) \- Oct ([\d\.]+)$/, '10 月 $1 \- 10 $2'],
	[/^Nov ([\d\.]+) \- Nov ([\d\.]+)$/, '11 月 $1 \- 11 $2'],
	[/^Dec ([\d\.]+) \- Dec ([\d\.]+)$/, '12 月 $1 \- 12 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) Defense$/, '+$1 防御'],
    [/^\+([\d\.]+) Magic$/, '+$1 魔法'],
    [/^\+([\d\.]+) Sword$/, '+$1 剑'],
    [/^\+([\d\.]+) Life$/, '+$1 生命值'],
    [/^\+([\d\.]+) Bow$/, '+$1 弓'],
    [/^\+([\d\.]+) Life • \+([\d\.]+) Magic$/, '+$1 生命值 • +$2 魔法'],
    [/^\+([\d\.]+)\% Drop Chance$/, '+$1% 掉率'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+)h, ([\d\.,]+)m, ([\d\.,]+)s$/, '$1小时 $2分 $3秒'],
    [/^([\d\.,]+)h, ([\d\.,]+)m$/, '$1小时 $2分'],
    [/^([\d\.,]+)m, ([\d\.,]+)s$/, '$1分 $2秒'],
    [/^([\d\.,]+) copies$/, '$1 份'],
    [/^([\d\.,]+) hours$/, '$1 小时'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Gold$/, '$1 金币'],
    [/^\n        ([\d\.,]+) Gold$/, '\n        $1 金币'],
    [/^\n        ([\d\.,]+) Drako$/, '\n        $1 德拉科'],
    [/^\n            Fishing: ([\d\.,]+)$/, '\n            钓鱼: $1'],
    [/^([\d\.,]+) GOLD$/, '$1 金币'],
    [/^([\d\.,]+) Gold.$/, '$1 金币。'],
    [/^([\d\.,]+) Experience for enduring the night.$/, '$1 经验 为了度过漫漫长夜。'],
    [/^([\d\.,]+) Experience for psychic fortitude.$/, '$1 经验 为了精神上的坚韧。'],
    [/^([\d\.,]+) Experience for your bravery.$/, '$1 经验 为了你的勇气。'],
    [/^([\d\.,]+) Experience and the Ancestral Blessing.$/, '$1 经验和祖先的祝福。'],
    [/^([\d\.,]+) Experience and the knowledge of Shadow Weaving.$/, '$1 经验和关于影织的知识。'],
    [/^([\d\.,]+) Experience points.$/, '$1 经验点数。'],
    [/^([\d\.,]+) Drako$/, '$1 德拉科'],
    [/^([\d\.,]+) HIGH RISK$/, '$1 高风险'],
    [/^ ([\d\.,]+) \| XP: ([\d\.,]+)$/, ' $1 | 经验值: $2'],
    [/^Magic: ([\d\.,]+) \| Defense: ([\d\.,]+)$/, '魔法: $1 | 防御: $2'],
    [/^Sword: ([\d\.,]+) \| Bow: ([\d\.,]+)$/, '剑: $1 | 弓: $2'],
    [/^\(([\d\.,]+) items\)$/, '($1 物品)'],
    [/^\(Life: ([\d\.,]+)\)$/, '(生命值: $1)'],
    [/^Suffered ([\d\.,]+) damage from a monster$/, '受到怪物的 $1 点伤害'],
    [/^\[Lv.([\d\.,]+)\]$/, '[等级 $1]'],
    [/^Buying Terror Amulets x([\d\.,]+).$/, '购买 恐怖护身符 x$1。'],
    [/^Level ([\d\.,]+)$/, '天数 $1'],
    [/^ \(Grants \+([\d\.,]+) Defense Skill\).$/, ' (授予 +$1 防御技能).'],
    [/^ \(Grants \+([\d\.,]+) Defense Skill and \+([\d\.,]+) Life.\).$/, ' (授予 +$1 防御技能 和 +$2 生命值.).'],
    [/^ \(Grants \+([\d\.,]+) Sword Skill and \+([\d\.,]+) Life.\).$/, ' (授予 +$1 剑术技能 和 +$2 生命值.).'],
    [/^You advanced to ([\d\.,]+) keep hunting$/, '你升到了 $1 级并继续狩猎'],
    [/^Destroy All \(([\d\.,]+)\)$/, '全部摧毁 ($1)'],
    [/^\(Lvl ([\d\.,]+)\)$/, '(等级 $1)'],
    [/^Place \(([\d\.,]+)\)$/, '放置 ($1)'],
    [/^Stage ([\d\.,]+): $/, '关卡 $1: '],
    [/^Chapter ([\d\.,]+): $/, '章节 $1: '],
    [/^Season ([\d\.,]+):$/, '赛季 $1:'],
    [/^Requires level ([\d\.,]+) \(You are in: ([\d\.,]+)\)$/, '要求 等级 $1 (你当前是: $2)'],
    [/^Requires Skull x([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 骷髅头 x$1 (你有: $2)'],
    [/^Requires Mantus x([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 曼图斯 x$1 (你有: $2)'],
    [/^Requires Ogre Boots x([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 食人魔靴子 x$1 (你有: $2)'],
    [/^Requires Amazon Armor x([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 亚马逊盔甲 x$1 (你有: $2)'],
    [/^Requires Terror Amulet x([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 恐怖护身符 x$1 (你有: $2)'],
    [/^Requires Draymor Helmet x([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 德拉莫头盔 x$1 (你有: $2)'],
    [/^Requires Lotus Bow x([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 连花弓 x$1 (你有: $2)'],
    [/^Requires magic skill ([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 魔法 技能 $1 (你有: $2)'],
    [/^Requires sword skill ([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 剑术 技能 $1 (你有: $2)'],
    [/^Requires defense skill ([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 防御 技能 $1 (你有: $2)'],
    [/^Requires bow skill ([\d\.,]+) \(You have: ([\d\.,]+)\)$/, '要求 弓 技能 $1 (你有: $2)'],
    [/^MAGIC \+([\d\.,]+) Point$/, '魔法 +$1 点数'],
    [/^SWORD \+([\d\.,]+) Point$/, '剑 +$1 点数'],
    [/^DEFENSE \+([\d\.,]+) Point$/, '防御 +$1 点数'],
    [/^BOW \+([\d\.,]+) Point$/, '弓 +$1 点数'],
    [/^Restores ([\d\.,]+) Stamina Points$/, '恢复 $1 耐力点数'],
    [/^Cooldown: ([\d\.,]+)s$/, '冷却时间: $1秒'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^DEFEAT! You were knocked out by the Goblin King. Your Life is ([\d\.,]+).$/, '失败！你被哥布林之王淘汰了。你的生命值是 $1。'],
    [/^Stage ([\d\.,]+) \- $/, '关卡 $1 - '],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) \(Lvl ([\d\.,]+)\)$/, '$1 (等级 $2)'],
    [/^(.+) \[Lv. ([\d\.,]+)\]$/, '$1 [等级 $2]'],
    [/^Price: FREE$/, '价格: 免费'],
    [/^Price: (.+) Drako$/, '价格: $1 德拉科'],
    [/^Price: (.+) Gold$/, '价格: $1 金币'],
    [/^Cost: (.+) Moonfin$/, '成本：$1 月鳍鱼'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);

var CNITEM_DEBUG = 0;

function cnItemByTag(text, itemgroup, node, textori) {
    for (let i in itemgroup) {
        if (i[0] == '.') { //匹配节点及其父节点的class
            let current_node = node;
            while (current_node) {
                if (current_node.classList && current_node.classList.contains(i.substr(1))) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '#') { //匹配节点及其父节点的id
            let current_node = node;
            while (current_node) {
                if (current_node.id == i.substr(1)) {
                    return itemgroup[i];
                } else if (current_node.parentElement && current_node.parentElement != document.documentElement) {
                    current_node = current_node.parentElement;
                } else {
                    break;
                }
            }
        } else if (i[0] == '$') { //执行document.querySelector
            if (document.querySelector(i.substr(1)) != null) {
                return itemgroup[i];
            }
        } else if (i[0] == '*') { //搜索原始文本
            if (textori.includes(i.substr(1))) {
                return itemgroup[i];
            }
        }
        // and more ...
        else {
            CNITEM_DEBUG && console.log({ text, itemgroup, dsc: "不识别的标签" + i })
        }
    }
    return null;
}

//2.采集新词
//20190320@JAR  rewrite by 麦子
var cnItem = function(text, node) {

    if (typeof(text) != "string")
        return text;
    let textori = text;
    //处理前缀
    let text_prefix = "";
    for (let prefix in cnPrefix) {
        if (text.substr(0, prefix.length) === prefix) {
            text_prefix += cnPrefix[prefix];
            text = text.substr(prefix.length);
        }
    }
    //处理后缀
    let text_postfix = "";
    for (let postfix in cnPostfix) {
        if (text.substr(-postfix.length) === postfix) {
            text_postfix = cnPostfix[postfix] + text_postfix;
            text = text.substr(0, text.length - postfix.length);
        }
    }
    //处理正则后缀
    let text_reg_exclude_postfix = "";
    for (let reg of cnExcludePostfix) {
        let result = text.match(reg);
        if (result) {
            text_reg_exclude_postfix = result[0] + text_reg_exclude_postfix;
            text = text.substr(0, text.length - result[0].length);
        }
    }

    //检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //检查是否排除
    for (let reg of cnExcludeWhole) {
        if (reg.test(text)) {
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;;
        }
    }

    //尝试正则替换
    for (let [key, value] of cnRegReplace.entries()) {
        if (key.test(text)) {
            return text_prefix + text.replace(key, value) + text_reg_exclude_postfix + text_postfix;
        }
    }

    //遍历尝试匹配
    for (let i in cnItems) {
        //字典已有词汇或译文、且译文不为空，则返回译文
        if (typeof(cnItems[i]) == "string" && (text == i || text == cnItems[i])) {
            return text_prefix + cnItems[i] + text_reg_exclude_postfix + text_postfix;
        } else if (typeof(cnItems[i]) == "object" && text == i) {
            let result = cnItemByTag(i, cnItems[i], node, textori);
            if (result != null) {
                return text_prefix + result + text_reg_exclude_postfix + text_postfix;
            } else {
                CNITEM_DEBUG && console.log({ text: i, cnitem: cnItems[i], node });
            }
        } else {
            // continue;
        }
    }

    //调整收录的词条，0=收录原文，1=收录去除前后缀的文本
    let save_cfg = 1;
    let save_text = save_cfg ? text : textori;
    //遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //已收录则直接返回
        if (save_text == cnItems._OTHER_[i])
            return text_prefix + text + text_reg_exclude_postfix + text_postfix;
    }

    if (cnItems._OTHER_.length < 1000) {
        //未收录则保存
        cnItems._OTHER_.push(save_text);
        cnItems._OTHER_.sort(
            function(a, b) {
                return a.localeCompare(b)
            }
        );
    }

    //开启生词打印
    CNITEM_DEBUG && console.log(
        '有需要汉化的英文：', text
    );

    //返回生词字串
    return text_prefix + text + text_reg_exclude_postfix + text_postfix;
};

transTaskMgr = {
    tasks: [],
    addTask: function(node, attr, text) {
        this.tasks.push({
            node,
            attr,
            text
        })
    },
    doTask: function() {
        let task = null;
        while (task = this.tasks.pop())
            task.node[task.attr] = task.text;
    },
}

function TransSubTextNode(node) {
    if (node.childNodes.length > 0) {
        for (let subnode of node.childNodes) {
            if (subnode.nodeName === "#text") {
                let text = subnode.textContent;
                let cnText = cnItem(text, subnode);
                cnText !== text && transTaskMgr.addTask(subnode, 'textContent', cnText);
                //console.log(subnode);
            } else if (subnode.nodeName !== "SCRIPT" && subnode.nodeName !== "STYLE" && subnode.nodeName !== "TEXTAREA") {
                if (!subnode.childNodes || subnode.childNodes.length == 0) {
                    let text = subnode.innerText;
                    let cnText = cnItem(text, subnode);
                    cnText !== text && transTaskMgr.addTask(subnode, 'innerText', cnText);
                    //console.log(subnode);
                } else {
                    TransSubTextNode(subnode);
                }
            } else {
                // do nothing;
            }
        }
    }
}

! function() {
    console.log("加载汉化模块");

    let observer_config = {
        attributes: false,
        characterData: true,
        childList: true,
        subtree: true
    };
    let targetNode = document.body;
    //汉化静态页面内容
    TransSubTextNode(targetNode);
    transTaskMgr.doTask();
    //监听页面变化并汉化动态内容
    let observer = new MutationObserver(function(e) {
        //window.beforeTransTime = performance.now();
        observer.disconnect();
        for (let mutation of e) {
            if (mutation.target.nodeName === "SCRIPT" || mutation.target.nodeName === "STYLE" || mutation.target.nodeName === "TEXTAREA") continue;
            if (mutation.target.nodeName === "#text") {
                mutation.target.textContent = cnItem(mutation.target.textContent, mutation.target);
            } else if (!mutation.target.childNodes || mutation.target.childNodes.length == 0) {
                mutation.target.innerText = cnItem(mutation.target.innerText, mutation.target);
            } else if (mutation.addedNodes.length > 0) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeName === "#text") {
                        node.textContent = cnItem(node.textContent, node);
                        //console.log(node);
                    } else if (node.nodeName !== "SCRIPT" && node.nodeName !== "STYLE" && node.nodeName !== "TEXTAREA") {
                        if (!node.childNodes || node.childNodes.length == 0) {
                            if (node.innerText)
                                node.innerText = cnItem(node.innerText, node);
                        } else {
                            TransSubTextNode(node);
                        }
                    }
                }
            }
        }
        transTaskMgr.doTask();
        observer.observe(targetNode, observer_config);
        //window.afterTransTime = performance.now();
        //console.log("捕获到页面变化并执行汉化，耗时" + (afterTransTime - beforeTransTime) + "毫秒");
    });
    observer.observe(targetNode, observer_config);
    window.cnItems = cnItems
}();